### ISSUE TITLE
aarch64 request for opensourcefoundries.com

### ISSUE THREAD

**Issue by doanac** [WorksOnArm/cluster#10]
### Name, email, company, job title
Andy Doan
andy@opensourcefoundries.com
Open Source Foundries
Senior Engineer

### Project Title and description
At Open Source Foundries, we are building a new platform to enable rapid product development with open source software, leveraging our team of expert open source developers. Our target hardware is Cortex-A for IoT and Cortex-M for IoT gateways.

We currently have CI loops that build both OpenEmbedded and Docker images for our IoT gateway. While in Linaro we took advantage of Linaro's developer cloud to handle this. As a new company we'd like to try out the packet.net infrastructure.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Our model is to make completely open releases every 6 months. We currently have some of our work output here:

 https://builds.linarotechnologies.org/End-to-end_IoT_system/

Most of our code is available at:

 https://github.com/linaro-technologies/

and is slowly moving over to:

 https://github.com/OpenSourceFoundries/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
We need access to an aarch64 server. We currently use an APM mustang, so anything as good or better would be fantastic. We run armhf builds inside KVM.

### Please state your contributions to the open source community and any other relevant initiatives
In addition to the GitHub repos listed above, members of the team have made contributions to Zephyr and MCUBoot such as the LWM2M stack, and have made numerous contributions to the 96Boards project. I deployed Linaro's original developer cloud in Austin, TX.

**Comment by doanac** [comment]
I've never gotten a response for this. Can I assume the request has been declined?

**Comment by vielmetti** [comment]
Hi Andy, I'm looking into this, but our 32-bit capable Arm infrastructure is limited right now.

**Comment by doanac** [comment]
Not sure if it helps, but we actually do our building on 64bit servers. In places where we need 32-bit binaries (docker images), we use a 32-bit qemu vm to do the work. 32bit qemu with virtio stuff is still faster than just building on something like an rpi3.

**Comment by doanac** [comment]
The server has been great. I didn't tell anyone about it. After putting it in our CI loop, I got a few "wow - this is soo much faster". Right now we are building a bunch of aarch64 containers on it:

 https://github.com/OpenSourceFoundries/core-containers
 https://github.com/OpenSourceFoundries/extra-containers/
 https://github.com/OpenSourceFoundries/gateway-containers/

We are will be building more stuff with them soon when I can find more cycles.

**Comment by vielmetti** [comment]
Terrific. Any chance we could get a brief writeup or acknowledgement in your blog? Doesn't have to be long (one line would be enough) but I'd love to be able to reinforce the QEMU 32-bit alternative that these 64-bit systems can provide.

**Comment by doanac** [comment]
@vielmetti - That seems like the least I can do considering your generosity. I'll let you know as we make progress on it.

**Comment by vielmetti** [comment]
Thanks @doanac - I have a few suggestions at https://github.com/WorksOnArm/cluster/blob/master/ACKNOWLEDGEMENT.md which might be helpful. We're happy to share anything you write through our usual channels.

**Comment by vielmetti** [comment]
@doanac - I'm preparing a monthly report on activity - if you have an update this is an opportune time!

**Comment by vielmetti** [comment]
Open issues from active users on the system are not supposed to auto-close, so I suspect I need to take manual action on this one.

**Comment by vielmetti** [comment]
Andy, are you using `jobserv` on this system? Would love to hear more about that work.

**Comment by EmbeddedAndroid** [comment]
Hi @vielmetti,

Thank you for allowing us the use of this server!

Here is a quick update on our usage, and a primer. 

At [foundries.io](https://foundries.io), we have created a scaleable continuous integration micro service called [jobserv](https://github.com/OpenSourceFoundries/jobserv). This service is used to queue, schedule, and distribute "jobs" across deployed nodes. A "job" defines the container environment that should be provided, and a script or scripts to be executed. The architecture jobserv implements allows upgrades to happen without downtime, and provide a Travis CI like experience with the ability to test on real hardware. Below are a couple of screen shots of the jobserv front end. 

![screenshot 2018-08-24 at 12 45 16 pm](https://user-images.githubusercontent.com/1061011/44604698-95cfe780-a79b-11e8-8273-936711e512c3.png)

![screenshot 2018-08-27 at 10 08 59 am](https://user-images.githubusercontent.com/1061011/44673758-3fec8100-a9e1-11e8-8412-5b2eff61e3bb.png)

The packet.net machine we use is deployed as a jobserv worker node, and it used everyday for continuous integration building and testing.

Typically, we use this machine to perform the aarch64 Docker image build permutation. The latest [images](https://hub.docker.com/u/opensourcefoundries/dashboard/) are built for armv7, aarch64, x86_64 and tied together with a manifest. This provides a seamless deployment of our reference applications across architectures. 

We really appreciate the use of this machine, and look forward to the future of ARM servers!
