### ISSUE TITLE
Requesting access for adding Sensu 2.x build

### ISSUE THREAD

**Issue by echlebek** [WorksOnArm/cluster#100]
### Name, email, company, job title

Hi, I'm Eric Chlebek, a software engineer at Sensu, Inc. I work on Sensu 2.x, the new version of Sensu, an open source monitoring solution.

### Project Title and description

Sensu 2.x is a reboot of the original Sensu, written in Go. Backed by an embedded etcd, it can easily form a cluster for high availability, high performance monitoring. See more details here: https://blog.sensuapp.org/announcing-sensu-2-0-beta-fce470c853fb

### Which members of the community would benefit from your work?

Anyone who wants to run Sensu 2.x on ARM hardware would benefit.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Sensu 2.x is MIT licensed. Its master repository can be found at https://github.com/sensu/sensu-go

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

If we had ongoing access to an ARM64 CI system we could maintain an ARM64 build for Sensu 2.x. Our build and test suite takes about 5 minutes to run on a 4 node Travis CI, for reference.

### Describe the continuous integration (CI) system in use or desired for this project.

We are running on Travis CI and are in the process of migrating to Circle CI. For our Windows builds we are using Appveyor.

### Please state your contributions to the open source community and any other relevant initiatives

Sensu has been a key component in open source monitoring solutions for many years now. A vibrant community of operators, plugin authors, and core contributers has grown up around the initial software. We are hoping to make Sensu 2.x even more of a success!

**Comment by vielmetti** [comment]
Hi @echlebek ! 

I've updated https://github.com/WorksOnArm/cluster/blob/master/CI.md and published it with some CI options for Works on Arm. Some hosted CI choices you have:

- CircleCI - I don't have current info about arm64 on Circle CI at the moment.
- Shippable - as of July 2018, Shippable works on arm64. See [the Shippable blog](http://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture) for details.
- Codefresh - Arm support is in beta, contact me via email for more info.

**Comment by vielmetti** [comment]
Hi @echlebek ! I'd love to help.

Please contact help@packet.net (attention Ed Vielmetti) and I'll get you all set up.

**Comment by vielmetti** [comment]
Ack! this got trapped by the stale bot. Checking to move it along.

**Comment by vielmetti** [comment]
Invite sent to a new project. It's possible that we can do this without dedicating a whole node to the task, since we do have some hosted arm64 CI support. I've sent an email separately.

**Comment by jacobsmith928** [comment]
@vielmetti seems like maybe we can support this now?
