### ISSUE TITLE
need access to an arm64 machine

### ISSUE THREAD

**Issue by roxell** [WorksOnArm/cluster#101]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Anders Roxell, anders.roxell@linaro.org, Linaro, +46708227105

Note that projects with two or more participants are preferred.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
openembedded
kernel.org

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
Memory, to be able to build OE I assume ?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Please state your contributions to the open source community and any other relevant initiatives

Brag a little bit about yourself, please!

**Comment by jacobsmith928** [comment]
Thank you @roxell I've created a project for you and marked it as not billable.  Please feel free to deploy a c1.large.arm for your testing.  A few notes:

- A great resource is our #worksonarm channel in community slack (https://slack.packet.net)
- These are bare metal dedicated machines, so when you are finished using at any time, please fully delete.  Powering off will not make it available to others. You can always redeploy a new machine when needed, or we can discuss a long-term reservation if the need arrives.
