### ISSUE TITLE
Bazel Build CI for Arm64 port

### ISSUE THREAD

**Issue by ArielleA** [WorksOnArm/cluster#102]
### Name, email, company, job title

Arielle Albon, independent platform porter on behalf of the Bazel Project

### Project Title and description

Bazel : a fast, scalable, multi-language and extensible build system.

Bazel is a build framework and tool that allows fast, correct repeatable builds,
in a number of languages. Rule sets can be created for any language or tools.

### Which members of the community would benefit from your work?

Users of Bazel that wish to target arm64 platforms, especially Tensorflow users
on modern SOCs with AI accelerators.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Apache License 2.0 https://github.com/bazelbuild/bazel

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

A c1.large.arm would be ideal for running a build slave continuously.

### Describe the continuous integration (CI) system in use or desired for this project.

Buildkite http://buildkite.com

### Please state your contributions to the open source community and any other relevant initiatives

Long time open-source developer, supporter. Professionally a Scrum Master.
Projects:
OpenWRT - initial port to Atheros ar521x based devices, first non-broadcom platform
Py-transports - author of PyIRCt, an XMPP to IRC transport using irclib & xmpppy
              - author of PyYIMt, an XMPP to Yahoo Instant Messenger
                using specific reverse engineering Yahoo library, and xmpppy
Porting of Bazel to Arm64, including some of the rule sets.

**Comment by vielmetti** [comment]
@ArielleA 

Approved! Please contact help@packet.net (attention Ed Vielmetti) and I'll get you all set up.

**Comment by vielmetti** [comment]
Referenced at https://github.com/bazelbuild/rules_docker/issues/1155 - while the Bazel binary work is complete, there are still a few gaps in the rules, in this case for multiarch docker (which in turn affects the `kind` project).
