### ISSUE TITLE
Request for kubernetes e2e/unit_test/integration_test CI and future CI on ARM

### ISSUE THREAD

**Issue by lubinszARM** [WorksOnArm/cluster#103]
Name, email, company, job title
Bin Lu bin.lu@arm.com, ARM, Staff software engineer

Project Title and description
Kubernetes is an open source system for managing containerized applications across multiple hosts; providing basic mechanisms for deployment, maintenance, and scaling of applications.

Which members of the community would benefit from your work?
Currently there are a bunch of contributions for this project, and together there is a need to have the fundamental UT/IT/E2E publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support.

Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, the project is 100% open source. Please refer to:
https://github.com/kubernetes/kubernetes

What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
Require access to one ARMv8 based server now in current stage.

Describe the continuous integration (CI) system in use or desired for this project.
For e2e test, please see following link as reference:
https://github.com/kubernetes/test-infra
https://k8s-testgrid.appspot.com/

Please state your contributions to the open source community and any other relevant initiatives
ARM is very actively in open source community and contributes a lot in various open source projects, like Kubernetes, Docker, Google/Gvisor, OpenJDK, DPDK, OpenStack, , etc.

**Comment by lubinszARM** [comment]
@vielmetti

**Comment by vielmetti** [comment]
As noted in https://github.com/kubernetes/kubernetes/issues/67720 the current Works on Arm inventory is very low. Please fill in details in your request how the k8s cluster will be provisioned and deprovisioned - we'll want you to use spot market and bring up and tear down the system as needed, rather than keep it running.

Alternatively, we are bringing online VM-based infrastructure, details and dates TBD. If you can provision and test your infra using arm64-on-arm64 virtual machines, let me and the project know.

**Comment by vielmetti** [comment]
Also worth asking is if there's another project within Works on Arm that you can double up on for project infra and machine access.

**Comment by vielmetti** [comment]
hey @jeefy @mrbobbytables can you take a look at this?

**Comment by vielmetti** [comment]
A suggestion is to request via CNCF, which would be very straightforward to administer inside the existing CNCF allocation at Packet.   The repo is https://github.com/cncf/cluster and the process is very similar to the Works on Arm setup.

**Comment by mrhillsman** [comment]
@lubinszARM @vielmetti we can offer resources for CI via OpenLab - https://openlabtesting.org - we are moving to GitHub issues for resource requests but not yet so if you fill out the form - Getting Started - on the site we can make it happen quite quickly in terms of the one ARMv8 node request

**Comment by lubinsz** [comment]
Hi @vielmetti 
My draft plan for e2e testing on Arm: 
I will create a trigger job daily, if the job was triggered, the script will create a k8s cluster for e2e testing.
The entire test process should takes 15+ hours.
The trigger condition is:  a new tag was found in k8s by checking 'git tag' or we trigger it by manually.
In general, the e2e testing runs at least once a week.

Also for k8s e2e test, the community strongly recommends not using virtual machines to test.

**Comment by lubinsz** [comment]
@mrhillsman 
I have filled out the “Let’s Get Started” form and send the request in OpenLab.
Thank you very much.

**Comment by mrhillsman** [comment]
@vielmetti safe to close this unless @lubinsz has any objections; we have been providing the requested infrastructure for some time now
