### ISSUE TITLE
Access to arm server for apt.llvm.org

### ISSUE THREAD

**Issue by sylvestre** [WorksOnArm/cluster#105]
### Name, email, company, job title
Sylvestre Ledru, sylvestre@debian.org, Debian, Debian Developer (I am also working for Mozilla but this isn't related)
Kristof Beyls <Kristof.Beyls@arm.com> volunteered to be the second contact!
Other ARM employees can probably vouch for me if needed!

### Project Title and description
The goal is to produce arm64 packages for https://apt.llvm.org/
Currently, only i386 and amd64 packages are provided.

### Which members of the community would benefit from your work?
LLVM, clang, libc++ and other LLVM-toolchain projects.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes
https://github.com/opencollab/llvm-jenkins.debian.net
https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/
https://llvm-jenkins.debian.net/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
I would need 4 or 5 ARM servers to handle the load. On going need.
For now, I have 9 intel servers for i386 and amd64 supports.

### Describe the continuous integration (CI) system in use or desired for this project.
I am using a Jenkins infra. I would need access to Debian system to run builds.
I created chroot for Debian & Ubuntu using deboostrap.

### Please state your contributions to the open source community and any other relevant initiatives
https://www.linkedin.com/in/sylvestreledru/

**Comment by sylvestre** [comment]
One server would be fine to start.

**Comment by vielmetti** [comment]
Approved - looking to set this up with a single machine right now.

**Comment by vielmetti** [comment]
Approved and invitations sent out - you should have instructions in your inbox @sylvestre and Kristof.

**Comment by sylvestre** [comment]
Many thanks. I am looking on how to connect it to the build system!

**Comment by vielmetti** [comment]
Thanks @sylvestre - when you get the build system connected and when there's a page on some CI dashboard showing status or progress I'll be happy to hear about it!
