### ISSUE TITLE
ONAP Multi CPU Architecture Container Images

### ISSUE THREAD

**Issue by OrangeMonk** [WorksOnArm/cluster#106]
### Name, email, company, job title
Adolfo Perez-Duran, adolfo@orangemonk.net, ARM, Software Architecture Consultant

### Project Title and description
ONAP CIA Project

(https://wiki.onap.org/) 

The CIA project is developing  best practices and tools for the creation of cpu-agnostic and efficient Docker/OCI container images. 

The Open Network Automation Platform (ONAP) is an open source project created to bring the capabilities for designing, creating, orchestrating of services based on Virtual Network Functions and Software Defined Networks.

### Which members of the community would benefit from your work?

Every single member of the ONAP community will benefit from the best practices and tools this project is developing.

Being part of an open source project the work of the CIA project can benefit any project working with OCI Containers

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, code will be located at https://git.onap.org/oparent/cia/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

The CIA project needs arm servers, such as c1.large.arm, to develop multi-cpu architecture images.

This is a request for continuous ongoing support. 

### Describe the continuous integration (CI) system in use or desired for this project.
Not required at the moment.

### Please state your contributions to the open source community and any other relevant initiatives
Container technology is a popular packaging method for developers and system administrators to build, ship and run distributed applications. Seventy percent of respondents to a 2017's survey indicated that the existence of tools to accelerate container development is one of the key factors that drives container adoption.

Software portability is the ability to use the same software artifacts (images/containers) in different environments. The CIA project aims at enabling ONAP deployments of both the orchestration platform and VNFs in different cloud infrastructure providers.

Network operators may choose among variety of hardware/server providers with different OS and cpu architectures.

This project takes a communal approach to capturing and developing best practices, guidance, recommendations and common tools for the design of container images.

**Comment by vielmetti** [comment]
Setting this up (but I hit a snag) - will follow up directly when this is done.

**Comment by vielmetti** [comment]
@OrangeMonk Can you comment on the status of this project, update us with the current situation? This effort came up in a review and I'd like to ensure that these systems are still in active use.

**Comment by vielmetti** [comment]
Per conversations with project stakeholders, this project has come to a close.
