### ISSUE TITLE
OpenHFT open source software testing on ARM

### ISSUE THREAD

**Issue by peter-lawrey** [WorksOnArm/cluster#109]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Peter Lawrey
peter.lawrey@chronicle.software
Chronicle Software
CEO

Note that projects with two or more participants are preferred.

The main project https://github.com/OpenHFT/Chronicle-Queue has had 42 contributors

### Project Title and description

Chronicle Queue
High performance persisted queue in Java using shared memory.  This works on x64, but not ARM atm.

Chronicle Map
High performance persisted key-value store in Java using shared memory.

### Which members of the community would benefit from your work?

A number of users of our software have tried on ARM and as it fails reported it as an issue.
We don't have the resources to setup servers to test this.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

https://github.com/OpenHFT/Chronicle-Queue and https://github.com/OpenHFT/Chronicle-Map

Both are Apache 2.0

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We need bare metal, 4+ cores and 16+ GB of memory on an ARM processor. We don't need x64 as we have enough of those.

Initially, we just need to fix the issues outstanding. We believe we know what the issue is but can't test it. Ideally, we would set up continuous integration.

### Describe the continuous integration (CI) system in use or desired for this project.

We use Teamcity and run a couple of Centos 7.5 and one WIndow server as agents.

### Please state your contributions to the open source community and any other relevant initiatives

I have the most answers in the world for Java, JVM, memory, concurrency on Stackoverflow https://stackoverflow.com/users/57695/peter-lawrey

I am a Java Champion, my blog Vanilla Java has had 4 million views and I architected OpenHFT open source software which has been downloaded more than 18 million times.

**Comment by vielmetti** [comment]
Reopening as we have resources that we didn't have back in October.

**Comment by vielmetti** [comment]
closed, as the resources were never used.
