### ISSUE TITLE
Cassandra on ARM 

### ISSUE THREAD

**Issue by mksinghtx** [WorksOnArm/cluster#11]
### Name, email, company, job title
Manish Singh mksingh@mitylytics.com, MityLytics, CTO
Misha Nanjappachar, misha@mitylytics.com
### Project Title and description
ARM on Cassandra for Cassandra releases for Dockerized and non-dockerized versions.
### Which members of the Works on Arm community and/or end-users would benefit from your work?
People building Data pipelines, looking to pick up latest Cassandra major and minor releases for bug fixes and improvements.
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes at http://cassandra.apache.org
### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
We would need Type2A ARM nodes or equivalent  - 3 at the minimum along with 2 Type-1 nodes to generate load for testing. In addition at certain times we would need to demonstrate integrations with Kafka and Storm/Spark for which we would need additional 3 ARM2A nodes.
 
### Please state your contributions to the open source community and any other relevant initiatives
We were the first company to demonstrate Cassandra at Apache Big Data North America in May 2017, thanks to the support of packet.net

**Comment by vielmetti** [comment]
@mksinghtx - thanks for the proposal!

One of the things that I've added in the newest proposal template - see #14 - is a request for people making proposals to identify a team with more than one person working on it - this is especially true for code that's from a foundation that may be available to provide additional support for the effort.

**Comment by mksinghtx** [comment]
Hi Ed,
  Have added Misha as a team member. We are looking for sponsors also to sponsor this effort.
Thanks,
--Manish

**Comment by vielmetti** [comment]
Hi @mksinghtx - haven't forgotten this request - but let me know if there's progress on this effort, and how your search for sponsorship is going.
