### ISSUE TITLE
aarch64 machine access for exprimenting Fedora CoreOS

### ISSUE THREAD

**Issue by sinnykumari** [WorksOnArm/cluster#110]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Sinny Kumari, sinnykumari@fedoraproject.org, Red Hat, Senior Software Engineer

Note: I should be able to give access to this machine to Fedora CoreOS community members whoever needs it to test or debug Fedora CoreOS related work.

Note that projects with two or more participants are preferred.

### Project Title and description
Fedora CoreOS initial support work on aarch64

### Which members of the community would benefit from your work?
Fedora CoreOS

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, Fedora CoreOS is in early design phase and related discussion occurs at https://github.com/coreos/fedora-coreos-tracker. Content of Fedora CoreOS will be built from Fedora packages which are available at http://koji.fedoraproject.org/koji/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
Decent memory and CPU with nested virt capability
According to https://www.packet.net/cloud/servers/ , armv8 comes only with c1.large.arm . This should be good enough for us.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Continuous ongoing effort
Building Fedora CoreOS is going to be a continuous effort at least till we do our first Fedora CoreOS release. Community members will need access to aarch64 machine for things like test, debug and fix aarch64 related issues.

### Describe the continuous integration (CI) system in use or desired for this project.
Not at the moment

### Please state your contributions to the open source community and any other relevant initiatives
I am involved with Fedora Atomic Host and worked in past on enabling Fedora Atomic Host on aarch64 and ppc64le. Also, I help in getting Fedora Atomic Two Week release out for all supported architectures(x86_64, ppc64le, aarch64)
I am also involved in Fedora CoreOS which will be successor of Fedora Atomic Host once released and work towards getting it's first release officially available.

Brag a little bit about yourself, please!

**Comment by vielmetti** [comment]
Invitation sent! thanks Ed

**Comment by sinnykumari** [comment]
Thanks Ed!

**Comment by jperrin** [comment]
This is the sort of collaboration I like seeing. :+1

**Comment by vielmetti** [comment]
This is running, so we can close it.

**Comment by vielmetti** [comment]
Noted at https://github.com/coreos/fedora-coreos-tracker/issues/69 - reopening this to track that issue.

Also: conversation with @sinnykumari about adding more members to project.

**Comment by sinnykumari** [comment]
Hi Ed,

Please add FCOS community members with email address dusty@dustymabe.com,  jlebon@redhat.com and ajeddeloh@redhat.com to Fedora CoreOS project

Thanks

**Comment by dustymabe** [comment]
and one more: bgilbert@redhat.com

**Comment by edolnx** [comment]
Those four folks have been invited!

**Comment by sinnykumari** [comment]
Thanks @edolnx
