### ISSUE TITLE
Datadog puppy agent on ARM

### ISSUE THREAD

**Issue by arbll** [WorksOnArm/cluster#111]
### Name, email, company, job title

Dhruv Sahni - dhruv.sahni@datadoghq.com - Datadog - Product Manager
Arthur Bellal - arthur.bellal@datadoghq.com - Datadog - Software Engineer
Derek Brown - derek.brown@datadoghq.com - Datadog - Software Engineer

### Project Title and description

The puppy agent is a server agent used to collect metrics, events and logs from hosts and forward them to Datadog. It is a minimal version of the datadog agent stripped of some of its features to allow for better compatibility across platforms.

### Which members of the community would benefit from your work?

Anyone looking to feed Datadog with metrics, events or logs coming from ARM hosts.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

https://github.com/DataDog/datadog-agent - (The puppy lives in the same repository as the regular Datadog agent)

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

A few (1-4) `c1.large.arm` would allow us to port and QA our agent. Ideally we would be able to let it run for extended period of time in order to test its stability.

### Describe the continuous integration (CI) system in use or desired for this project.

We use an on-premise gitlab internally. We are not currently planning to use those hosts with our CI but we might reconsider once the puppy is more mature.

**Comment by vielmetti** [comment]
Hi @arbll ! I'm working on getting this access for you, hope to have an update by end of week.
