### ISSUE TITLE
Request an ARM server to verify lock-free data structures

### ISSUE THREAD

**Issue by junchangwang** [WorksOnArm/cluster#113]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Junchang Wang
junchangwang@gmail.com
Nanjing University of Posts and Telecommunications
Researcher

### Project Title and description

Lock-free Data Structures on Multi-core Servers to verify the performance and scalability of various classic lock-free data structures on different architectures.

### Which members of the community would benefit from your work?

Given lock-free data structures (and parallelized data structures) is fundamental, members working on system software would get a benefit.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Definity. Most of the projects I am working on are open source. For example:
Perfbook (contributer): https://mirrors.edge.kernel.org/pub/linux/kernel/people/paulmck/perfbook/perfbook.html
EQueue (owner): https://github.com/junchangwang/EQueue
ECCount (owner): https://github.com/junchangwang/eccount

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

One multi-core ARM server. The more CPU cores on the server, the better. For example, a server with more than two dies, each of which has more than 8 cores, is expected.

### Please state your contributions to the open source community and any other relevant initiatives

I am interested in parallel computing and am working on helping improve Paul McKenney's classic textbook on this domain. This book is open-source, and I have submitted a dozen patches. However, all of the servers I can access are x86. So Paul kindly refers me to this project to apply access to ARM servers.

Besides, I have designed a few lock-free data structures (e.g., https://github.com/junchangwang/EQueue), and they are open-source under GPL license. Unfortunately, I never test them on ARM servers.

So it would be great if I can verify these projects on a real ARM server.

**Comment by vielmetti** [comment]
Junchang - the ideal system for this would be one of the Cavium ThunderX2 systems which have in our configuration 56 cores + 4 hardware threads per core, with a total of 224 separate CPUs reported via tools like `htop`. Your request has been noted and will be addressed as soon as possible based on our current inventory.
