### ISSUE TITLE
PyTorch

### ISSUE THREAD

**Issue by goldsborough** [WorksOnArm/cluster#115]
### Name, email, company, job title

PyTorch, psag@fb.com, Facebook, Software Engineer

### Project Title and description

PyTorch: https://github.com/pytorch/pytorch

PyTorch is a machine learning library for dynamic neural networks with strong GPU acceleration. Our community spans hundreds of industrial and academic research labs all around the world.

### Which members of the community would benefit from your work?

We want to provide ARM builds of PyTorch to enable machine learning applications on ARM systems like NVIDIA Jetson TX2 or AGX Xavier, or Raspberry Pis, which power self driving car and IOT applications.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, everything is open source: https://github.com/pytorch/pytorch

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

One c1.large.arm would be a great start. I need to determine whether PyTorch builds on ARM, and how long it takes. Right now one-time support is sufficient.

### Describe the continuous integration (CI) system in use or desired for this project.

We have CI running on Jenkins and CircleCI, and hope to move entirely to CircleCI in the future.

### Please state your contributions to the open source community and any other relevant initiatives

PyTorch is the second fastest growing project on GitHub: 

![screen shot 2018-10-23 at 14 58 48](https://user-images.githubusercontent.com/6429851/47393402-2d867f00-d6d4-11e8-9cc3-5a0706a4ffa2.png)

from https://octoverse.github.com/projects.html

**Comment by vielmetti** [comment]
Approved! You'll be the first project to get one of the few Ampere systems we have under test.

**Comment by vielmetti** [comment]
Noted also at https://github.com/pytorch/pytorch/issues/13130

**Comment by vielmetti** [comment]
This project is now complete, closing.
