### ISSUE TITLE
Using ARM CI for Piqueserver

### ISSUE THREAD

**Issue by NotAFile** [WorksOnArm/cluster#116]
### Name, email, company, job title

Adrian Tschira, nota@notafile.com, n/a, n/a

### Project Title and description

Piqueserver is an open-source server for the original "Ace of Spades" game. This is obviously not critically important software, but the game still gets hundreds of unique players each day and we would like to ensure things run smoothly. Piqueserver contains Python, Cython Python extensions and C and C++ code, which makes the interaction of those components on different systems harder to predict. All of the core team are currently students, so hardware expenditures are limited.

### Which members of the community would benefit from your work?

For many players, setting up an e.g. raspberry pi with piqueserver is often their first foray into linux and servers, so we want to ensure that everything goes smoothly for these users. Not being able to  test and build releases on these systems means these users have to face subtle bugs (e.g. https://github.com/piqueserver/piqueserver/issues/382) and long compile times on the usually cheap hardware. With ARM CI, we can ensure that that won't happen by testing commits and releasing official builds. We can also consider releasing pre-configured bootable ARM images which would be a nightmare to release otherwise. We also want to add ARM NEON support (https://github.com/piqueserver/piqueserver/issues/407) to improve performance on ARM. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Our main project (server) source code is located at github.com/piqueserver/piqueserver a number of auxilliary projects can be found at github.com/piqueserver.

### Describe the continuous integration (CI) system in use or desired for this project.

We currently run TravisCI for linux CI, Appveyor for Windows CI and one continuously running "nightly" server for integration testing, performance testing, for game client developers to verify their implementation of new features against and for reproducing bug reports.

We'd really like to extend that with ARM test/builds as well as possibly running another test instance for reproducing bugs.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

The website currently only lists the `c1.large.arm`, which seems entirely oversize for any of our requirements. We have no special requirements on hardware or network access.

### Please state your contributions to the open source community and any other relevant initiatives

The piqueserver core team also maintains releases for the `pyenet` library, which is also used by a number of other projects.

> Brag a little bit about yourself, please!

I'm one of the primary primary developers of piqueserver. (# 1 in the last few years according to github). I've done a few other mostly insignificant things, like spearhead the port of https://github.com/matrix-org/synapse to python3.

**Comment by vielmetti** [comment]
I've been in touch with @NotAFile and we're working on details of access to a new OpenStack based service. I'll keep this open until that process finishes.

**Comment by NotAFile** [comment]
This issue is still relevant.

**Comment by NotAFile** [comment]
This issue is still relevant

**Comment by vielmetti** [comment]
Thanks @NotAFile for your patience. 

We have some OpenStack infrastructure on the way, it is said, but I don't have a date certain for that yet.

Have you tried Drone Cloud? It runs on Packet infrastructure and is a hosted CI (along the lines of Travis or Circle or ...) that can execute in x86, arm64, or 32-bit Arm environments. Happy to help set something up with that.

**Comment by vielmetti** [comment]
Assuming this issue is still relevant, reopening.

**Comment by godwhoa** [comment]
Yep still relevant, we did give Drone Cloud a try last week but couldn't use caching plugins with it. Without caching our build times are way too slow (~24min, it had to build lots of dependencies from scratch due to the lack of ARMv8 python wheels).

**Comment by vielmetti** [comment]
Ooh, dependencies. We do have people working on the Python side of things, @godwhoa - if there's some list you have assembled of dependencies without wheels, I'm happy to tack those onto a list to tackle.

What caching plugin did you hope to use?

**Comment by NotAFile** [comment]
We were actually pretty surprised that caching isn't a default feature in drone... I don't think the plugin really matters, I  can't imagine they'd be that different?

The problem of wheels is that there is no PEP specification for linux ARM wheels. The manylinux1 and manylinux2010 platform tags only apply to x86(_64), due to being based on Centos7, which does not support anything else. So before any wheels could be uploaded, a manylinux standard for ARM wohld be required (or a third-party wheel repo that doesn't comply to pypi's strict standards, like piwheels.org). That said, our biggest annoyance was probably the lack of wheels for Cython.

**Comment by vielmetti** [comment]
Noted also at https://github.com/pypa/manylinux/issues/84#issuecomment-462038304 .

@NotAFile - Are you in any position to expand this project beyond `piqueserver` toward the greater task of improving Python on arm64? I ask only because it's a lot easier to approve resources towards fundamental language development tasks and a lot less easy to get backing for things that just look from the outside to be fun. Piqueserver then becomes the test case for the project (hey, good to have a test case).

**Comment by vielmetti** [comment]
Approved - details in email.

**Comment by NotAFile** [comment]
The relevant issues here

https://github.com/pypa/manylinux/issues/84
https://github.com/pypa/warehouse/issues/3668

I don't think arm64

**Comment by vielmetti** [comment]
Also relevant is https://github.com/cython/cython/issues/2561 which specifically addresses the issue of long Cython build times.

**Comment by vielmetti** [comment]
Also also relevant is https://github.com/numpy/numpy/issues/11702 which looks like they are using Shippable for builds and doing caching to improve results.
