### ISSUE TITLE
arm64/aarch64 access for continuous testing and occasional shell for mgmt config

### ISSUE THREAD

**Issue by purpleidea** [WorksOnArm/cluster#117]
### Who: James <last name in git logs> james@purpleidea.com
Currently self-funding work on open source software. Hacker.

### Project: Mgmt Config

[Mgmt](https://github.com/purpleidea/mgmt/) is a next generation automation tool. It is fast, and runs in real-time. Many blogs posts and conference recordings about it are available here: https://github.com/purpleidea/mgmt/blob/master/docs/on-the-web.md

### Which members of the community would benefit from your work?

We're still ramping up to a 0.1x release, but it would be excellent if we supported arm64 by the time we release. Some of the design ideas of this tool emerged when thinking about early arm clusters (and having seen some early unobtainium chips) and thinking about how configuration management could scale drastically across many smaller servers.

We've had about 50 code contributors to the project, and we hope that as we get more stable, the project gets lots of use in production environments.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yep, 100%. It's all here: https://github.com/purpleidea/mgmt/
(Note git master is a bit quiet at the moment, since a large changeset is brewing in a feature branch.)

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Something very small to be honest. Not looking to be greedy with resources, I'd like to run our CI, and occasionally get shell access to debug things interactively PRN. The smallest arm I saw was `c1.large.arm`. I only really need about max two cpu's and about 8GB of ram. In the future I'd love to do some large scale tests, but it's not necessary at the moment. Tests run once every 24, and on every new commit/PR.

> if this is a request for continuous ongoing support

Yes please :)

### Describe the continuous integration (CI) system in use or desired for this project.

Currently we use the free travis-ci. If that's supported, that would be great!

### Please state your contributions to the open source community and any other relevant initiatives

Former Red Hat engineer for four years. Left to try and self-fund this project off my savings. Going to keep it up until I run out of money or I can get funding to pay for the development. (The plan is to keep it open source!) Previously started https://github.com/purpleidea/oh-my-vagrant and https://github.com/purpleidea/puppet-gluster as well as other things on my github profile. I've been writing the Technical Blog of James http://purpleidea.com/blog/ for many years too!

Thanks for your consideration!

**Comment by purpleidea** [comment]
Never heard back...

**Comment by purpleidea** [comment]
Hi bot.

**Comment by vielmetti** [comment]
Hey @purpleidea ! Thanks for your understanding re the bot and thank you for poking it periodically.

Trying to figure out the best way to support you. We're waiting on status of a project that will generate arm64 VMs. There's a couple of good CI solutions like Drone Cloud that could do the trick well for the test/CI part, but not for the interactive part.

One possible approach is to build your system under NixOS - see #30 for that setup - there are a bunch of build resources there that could help a port.

**Comment by purpleidea** [comment]
I think the NixOS thing won't be a great fit... As long as I can run a bash/python/golang script on a machine somewhere, I think I can be in pretty good shape to run the tests. I can write a small script that pulls from git and runs the tests periodically every 24h or so, if that's okay with you. (Or a less frequent interval if that's easier.)

Let me know and thanks again :) I don't mind fighting the bot-- my life is duelling with computers!

**Comment by purpleidea** [comment]
Hi bot.

**Comment by purpleidea** [comment]
Hi bot!

**Comment by purpleidea** [comment]
Hi bot!!

**Comment by purpleidea** [comment]
Hi bot!!!

**Comment by purpleidea** [comment]
@vielmetti If this is never happening, please let me know.

lol bots: https://twitter.com/purpleidea/status/1246940946526285825

**Comment by vielmetti** [comment]
@purpleidea You should be able to use the arm64 support in Travis CI now - that was turned on last fall.

**Comment by purpleidea** [comment]
@vielmetti Did not know that, thanks, I'll have a look! :) As an aside, if you ever have a large number of small machines or VM's (eg: > 128-512 machines, @ 8GiB ram each) for some temporary (eg: a weekend) large scale tests, I'd always appreciate the loan.
