### ISSUE TITLE
IncludeOS on Aarch64

### ISSUE THREAD

**Issue by KristianJerpetjon** [WorksOnArm/cluster#118]
### Name, email, company, job title

Alfred Bratterud, alfred@includeos.org, CTO
Kristian Jerpetjøn, kristian@includeos.org, Senior Engineer

### Project Title and description

IncludeOS on ARM
The project aims to port the IncludeOS Unikernel from the amd64 architecture to aarch64 (potentially also arm32).

### Which members of the community would benefit from your work?

IoT developers:

IncludeOS on ARM will be initially directed at CPU-based, IoT workloads, as a replacement for Linux. There are fundamental challenges with Linux’ architecture that have caused security problems in IoT. Linux, and other Unix-based systems are run-time reconfigurable systems that can have their functionality fundamentally altered in an attack. IncludeOS on the other hand, creates baked little images that are to a much greater extent immutable and hard to modify. In addition the attack surface of such a system is greatly reduced.

IncludeOS has hard real time characteristics, which allows simplifications of IoT devices as there no longer has to be accompanying micro-controllers to facilitate real time behaviour.

Other developers:

IncludeOS can also be used for more generic, server-based, tasks. With it’s (limited) Linux compatibility (http://www.includeos.org/blog/2018/musl.html) and it’s flexible build system it can also serve as a replacement for containers in certain situations (typically defined systems that can be defined “ahead of time”). See for instance https://nabla-containers.github.io/ for a novel approach to an architecture that could be used to implement “Function-as-a-Service”. This could be relevant for the ARM architecture if the architecture gains traction.

It has also been used for “Network Function Virtualization” (firewall, load balancing, etc). 

It is worth pointing out that all though the system natively only supports application written in C++ and C, there are plans to port other language runtimes. Language runtimes that are implemented in C or C++ can be supported on IncludeOS.

Lastly it’s been a vehicle for CS research on operating systems. See Google Scholar for examples.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes. 100% Open Source under the APL2 license. Project related discussions occurs on #slack https://goo.gl/NXBVsc and the documentation can be found at https://includeos.readthedocs.io 
For a view of our source code please see https://github.com/hioa-cs/IncludeOS

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Decent memory and CPU to facilitate compilation and testing with virtualization capability.
According to https://www.packet.net/cloud/servers/ , armv8 comes only with c1.large.arm . This should be good enough for us.

Continuous ongoing effort. Project is expected to last for at least two years.

Building and further developing IncludeOS on the aarch64/arm architecture with the ability to fix aarch64 related issues and port new functionality as it arrives to aarch64.

### Describe the continuous integration (CI) system in use or desired for this project.

IncludeOS uses Jenkins, available at https://jenkins.includeos.org/

### Please state your contributions to the open source community and any other relevant initiatives

IncludeOS provides a novel way to do compute. By starting from scratch we’ve built a system that addresses the needs of today and tomorrow. According to researchers at IBM IncludeOS can provide the “next unit of computing for edge and cloud workloads”.

IncludeOS uses a lot of open source components, such as Musl, Solo5/hvt, Qemu, S2N, OpenSSL, Botan and others. We try to upstream as much of the changes that we need to do to these projects if they the project is willing.

We’ve worked with other Unikernels on some common projects such as the Solo5 project that is shared by Mirage and Rumprun.

**Comment by KristianJerpetjon** [comment]
bump

**Comment by perbu** [comment]
Got an update from Ed. They are waiting for new inventory before they can proceed.

**Comment by edolnx** [comment]
Greetings IncludeOS! We've created a project for you in the Works on Arm organization and invited each of you to it. If you already have an account, it should already appear otherwise following the link in the email will help you get started.

We've also added a Qualcomm based server for your use. Sadly it's only AArch64 only, and we are working getting you a different machine that supports both AArch64 and AArch32 so treat the current one as temporary. We'll let you know when they are available and work with you to reclaim the Qualcomm machine.

You are also free to grab any x86 based hosts out of the cloud fleet for your use as on-demand or spot instances as needed. For reference the Qualcomm machine is in our EWR facility so if you use machines in that facility will be lightning fast between the hosts.

Please feel free to reach out to Ed or I via this issue, email, or the Works on Arm channel in the community slack (slack.packet.com) if you have any questions.

**Comment by vielmetti** [comment]
Thanks all! I'd also happily take a PR for 

https://github.com/WorksOnArm/cluster/blob/master/projects/alphabetical.md

if you can find the slot in there for IncludeOS, I currently have some of the info added and will add more.

cc @perbu

**Comment by KristianJerpetjon** [comment]
Great news Thanks all!

**Comment by vielmetti** [comment]
Noting a talk by @perbu at https://cfgmgmtcamp.eu/

https://twitter.com/rjw1/status/1092408672561647616

**Comment by vielmetti** [comment]
@perbu @KristianJerpetjon I have this marked as still open - would love a brief project update if you have any reports of progress (or success, or even any interesting failures).
