### ISSUE TITLE
Proposal: arm64 builder for Raspberry Pi 3 images with LinuxKit

### ISSUE THREAD

**Issue by hairyhenderson** [WorksOnArm/cluster#12]
### Name, email, company, job title

Dave Henderson, dhenderson@gmail.com

### Project Title and description

LinuxKit booting on a RPi3

I'd like to be able to build small purpose-built Linux images that boot on a Raspberry Pi 3.
The RPi3 is an excellent platform for running small purpose-built images due to its popularity, low cost, and 64-bit ARMv8 CPU, but it's unfortunately not currently capable of building those images itself (due to resource constraints).

### Which members of the Works on Arm community and/or end-users would benefit from your work?

Potentially anyone with a Raspberry Pi 3.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, https://github.com/linuxkit/linuxkit

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Type 2A

### Please state your contributions to the open source community and any other relevant initiatives

Not sure it's totally relevant, but I've [contributed to Docker Machine](https://github.com/docker/machine/pulls?utf8=✓&q=author%3Ahairyhenderson%20) and [Docker](https://github.com/moby/moby/pulls?utf8=✓&q=author%3Ahairyhenderson%20), and I also created a somewhat popular commandline tool for template rendering, [gomplate](https://github.com/hairyhenderson/gomplate) (which builds for `arm64` too!).

**Comment by eyz** [comment]
The rPI 3 doesn't have enough RAM to currently produce a build, so the packet.net 2A would assist in builds during the development and integration of an root disk image.

**Comment by vielmetti** [comment]
Attn @arm64b who has been working on Linuxkit.

**Comment by vielmetti** [comment]
Related issue: https://github.com/linuxkit/linuxkit/issues/2574

**Comment by vielmetti** [comment]
Lots of progress today towards getting a Linuxkit build on a Pi 3. 

It's worth thinking through what kind of long-term support this might want, and how best to do it. In the short term I've applied some Works on Arm credits at Packet to @eyz and @hairyhenderson in support of this effort.

**Comment by vielmetti** [comment]
https://github.com/WorksOnArm/cluster/tree/master/projects/rpi3-linuxkit has a directory for anything from the project that can be shared as project status - the README.md file there is a skeleton for now and will be expanded as I report out more about this effort.

**Comment by hairyhenderson** [comment]
I guess we can close this now... Some awesome progress was made and the RPi3 is now more-or-less properly supported in LinuxKit 🎉
