### ISSUE TITLE
HPX (and related technologies) on ARM64

### ISSUE THREAD

**Issue by sithhell** [WorksOnArm/cluster#120]
### Name, email, company, job title

Thomas Heller, thom.heller@gmail.com, STE||AR-Group, Researcher

### Project Title and description

HPX (and related technologies) on ARM64

The project aims to push forward the support for ARM64 support in the HPX runtime system. In addition to provide continously tested software on ARM, we are also very interested to continously assess the performance on large scale ARM CPUs.

### Which members of the community would benefit from your work?

Every user of the HPX runtime system will immediately benefit from this work. As HPX is designed to run at any scale. This work will benefit everyone from smart phone applications to HPC workloads requiring massive parallelism

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

The code is located here: https://github.com/STEllAR-GROUP/hpx and is released under the Boost Software License

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We are interested in setting up a long term CI runner based on gitlab-runner using the c2.medium.arm resource. For this, we envision to access the spot market. In addition, we are interested in extending this to continuos performance evaluation, possibly extending towards distributed applications to leverage the excellent packet network infrastructre.

### Describe the continuous integration (CI) system in use or desired for this project.

We are currently in the process of migrating our different setups (buildbot, circleci and homegrown) towards gitlab-runner and attempt to build many configurations on a pull request/merge request basis.

### Please state your contributions to the open source community and any other relevant initiatives

HPX is the C++ Standard Library for Parallelism and Concurrency. We are actively engaged in the C++ standardization process and our experiments and research have direct influence on the future direction of C++.

**Comment by vielmetti** [comment]
Approved! We're set up with a new system.

**Comment by vielmetti** [comment]
Noting an issue at https://github.com/packethost/docker-machine-driver-packet/pull/34

**Comment by vielmetti** [comment]
@sithhell - the notes I have show the following issues still open:

* [ ] https://github.com/packethost/docker-machine-driver-packet/pull/34 - Docker Machine driver
* [ ] a Gitlab issue with the arm64 runner of long standing
* [ ] a Gitlab issue regarding getting multiple shell runners to coexist

If there are any others, please reference them here and I'll work my way through them.
