### ISSUE TITLE
Lollipop Cloud Submission for Inclusion

### ISSUE THREAD

**Issue by lollipop-cloud** [WorksOnArm/cluster#126]
### Name, email, company, job title

Mike Crosson
Founder
cloud@lollippopcloud.solutions

jmf
Founder
cloud@lollipopcloud.solutions

### Project Title and description

Lollipop Cloud

Short description: working on documentation, guides and integration that facilitate self-hosting personal clouds on arm SBCs

### Which members of the community would benefit from your work?

Any individual hoping to self-host a cloud on a Raspberry Pi 3b or 3b+ and similar SBCs. Also, upstream OSS projects that we build for arm. We regularly submit patches and code to upstream projects to enhance their support of the arm architecture.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

All of our code and documentation is OSS/Commons Licensed. http://git.lollipopcloud.solutions/ contains all of our work.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Ideally we'd move and grow our current build infrastructure to the packet.net bare metal cloud. Based on the offerings as of 2019/01/22 the following is a rough break down of our hopes/dreams/needs.

- t1.small.x86
  - jenkins instance / other basic x86-64 required infrastructure
  - currently hosted on an intel atom compute stick with usb storage
- c2.medium.x86 or x1.small.x86 
  - for building armbian, raspbian, bitwarden_rs projects (maybe more in the future)
  - we currently use a xeon W3550 workstation with 24Gb RAM for these tasks
- c1.large.arm or similar aarch64 server with at least 8Gb RAM and 4 cores of compute
  - preferably multi-arch so we can build arm7l software as well
  - we currently use a set of orange pi pc boards as well as A1 aws instances deployed on demand for our arm build needs
  - we build for arm7l and arm8 currently
  - we build a variety of docker images for arm including, but not limited to cryptpad, matrix, plume, pleroma, watchtower, fathom, gitea, minio, pixelfed, privatebin, searx, steamcache with more planned for the future

> Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Ideally we'd have long-term support from packet for our project.

### Describe the continuous integration (CI) system in use or desired for this project.

We currently use Jenkins to manage our builds. We'd like to keep Jenkins if possible but are open to other options. Ideally we'd be deploying on-demand for our builds but are unsure if this is an easily available option within jenkins for the packet.net bare metal infrastructure.

### Please state your contributions to the open source community and any other relevant initiatives

Brag a little bit about yourself, please!

jmf has contributed a lot of documentation and filed more than a few tickets related to accessibility in open source. they quietly work with developers that are open to improving accessibility and documentation

Mike Crosson (aka KemoNine) has contributed to cryptpad, plume, fathom, kodi.tv, has worked with the openwrt developers on x86-64 prior to official support, has been an xda recognized developer based on their cyangenmod porting work in the past and has been featured on the adafruit community corner

**Comment by vielmetti** [comment]
@lollipop-cloud 

Project approved. @edolnx and I will set this up and reserve a machine for you, @lollipop-cloud , and we'll report back here when that's ready. 

In private mail send me the email address(es) of the individuals who should be invited to the project; we prefer in general that these be individual personal addresses, though you can also add an administrative role as an additional address for things like key management &c.

**Comment by vielmetti** [comment]
System is reserved and online, so I'll close this out as "done" and we'll follow up as necessary.

**Comment by vielmetti** [comment]
Hisilicon system is up and running, to good effect. Stats are published to https://munin.cherry.lollipopcloud.solutions/localdomain/localhost.localdomain/

Noted for @lollipop-cloud an interest in Ampere hardware too, once we have a next quantity to look at.
