### ISSUE TITLE
Proposal: kubespray

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#127]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Ed Vielmetti, Packet
@miouge1

### Project Title and description

Kubespray testing

### Which members of the community would benefit from your work?

Anyone using Kubernetes on arm64 or on Packet

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

https://github.com/kubernetes-sigs/kubespray

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

A single Arm server, c1.large.arm or equivalent.

### Describe the continuous integration (CI) system in use or desired for this project.

[tbd]

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project?

[tbd]

### Please state your contributions to the open source community and any other relevant initiatives

[tbd]

Brag a little bit about yourself, please!

**Comment by Miouge1** [comment]
### Describe the continuous integration (CI) system in use or desired for this project.

GitLab CI

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project?

No monitoring system planned.

### Please state your contributions to the open source community and any other relevant initiatives

OpenStack, Helm, Kubernetes and Kubespray contributor.

**Comment by vielmetti** [comment]
A relevant issue is https://github.com/kubernetes-sigs/kubespray/issues/2551

**Comment by vielmetti** [comment]
Add to Kubernetes milestone

**Comment by vielmetti** [comment]
A Qualcomm system is now in the project, cc @johnstudarus . Your interest in an Ampere system is also noted.

**Comment by vielmetti** [comment]
@Miouge1 Am I to understand that a second system would help for testing?

**Comment by johnstudarus** [comment]
We've been running clusters with three hosts. I guess the master could be
x86 and two Arm minions?

**Comment by Miouge1** [comment]
A second ARM server would be good to verify that SDN/CNI actually work in practice.

Mixed x86 and arm64 Kubernetes clusters is also something interesting to test, good idea.

**Comment by Miouge1** [comment]
@vielmetti while testing a fresh deploy with Terraform, I accidentally returned the server back to the pool (I think). Is it possible to bring back an arm64 test server in the project?

**Comment by vielmetti** [comment]
@Miouge1 

When you destroyed (deprovisioned) the server it was scrubbed to be ready for the next use. That takes a few minutes, and it's unavailable during that time. I think that lines up with your comment.

The server is now ready for your use in the project.

**Comment by Miouge1** [comment]
OK, my bad thank you for the clarification.
