### ISSUE TITLE
Proposal: VPP

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#128]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Ed Vielmetti, Packet
@dbarach

### Project Title and description

VPP (Vector Packet Processing) is an extensible framework that provides out-of-the-box production quality switch/router functionality. It is the open source version of Cisco's Vector Packet Processing (VPP) technology: a high performance, packet-processing stack that can run on commodity CPUs.

### Which members of the community would benefit from your work?

[tbd]

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

* https://wiki.fd.io/view/VPP - documentation
* https://wiki.fd.io/view/VPP/AArch64 - VPP on AArch64 (arm64)

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

[tbd]

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe the continuous integration (CI) system in use or desired for this project.

[tbd]

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project?

[tbd]

### Please state your contributions to the open source community and any other relevant initiatives

Brag a little bit about yourself, please!

[tbd]

**Comment by vielmetti** [comment]
cc @edwarnicke

**Comment by vielmetti** [comment]
There is an extended discussion in #56 of getting VPP to work.

**Comment by edwarnicke** [comment]
@vielmetti Thank you for opening this :)

**Comment by dbarach** [comment]
Random bragging: I'm the PTL for the fd.io vpp project, a top user-space networking open-source project. Vpp is the result of > 15 years' worth of Cisco R&D, open-sourced about three years ago. The code base comprises 700 KLOC, and implements a highly performant network stack. On a top-drawer x86_64 server, vpp handles > 1 TB, full duplex. The VPP host stack handles O(1e7) TCP streams, easily outperforms the Linux kernel TCP stack, and passes over 1 million Codenomicon TCP tests.

**Comment by dbarach** [comment]
We currently use a Jenkins CI system for aarch64 builds, which is problematic on a good day.

**Comment by vielmetti** [comment]
Approved! Let's sort out what the best sort of infrastructure is for this effort.

I have access to Qualcomm Centriq, Huawei Taishan, Marvell ThunderX and ThunderX2, and Ampere eMag servers. At various points in time there is more or less availability of each machine type. In the interests of getting started, @dbarach - which should I try to set up first, second, third?

**Comment by vielmetti** [comment]
We also have what might be suitable infra for more CI - https://cloud.drone.io/ is Drone Cloud which builds for x86, arm32, and arm6.

**Comment by vielmetti** [comment]
Taking the `wontfix` label off of this, and looking at what it takes to move it forward.
