### ISSUE TITLE
Proposal: High-Performance SIMD Optimizations on Next Generation ARM platforms

### ISSUE THREAD

**Issue by lemire** [WorksOnArm/cluster#146]
### Name, email, company, job title

Daniel Lemire, University of Quebec (TELUQ), professor

home page: https://lemire.me/en/
blog: https://lemire.me/blog/

### Project Title and description

Title: High-Performance SIMD Optimizations on Next Generation ARM platforms

I have a number of ongoing projects that I'd like to test with next-generation ARM servers such as the upcoming Ampere services. Among those are ARM specific optimizations of Roaring (https://roaringbitmap.org) and some ongoing work (to be soon made public) on fast parsing.

### Which members of the community would benefit from your work?

High performance (SIMD) work is primarily focused on Intel/AMD platforms with some exceptions (like crypto). We are trying to bring impressive high-performance optimizations to ARM with a specific focus on SIMD (Neon). ARM servers have often been disappointing in this respect, but we want to keep pushing the envelope.

### Is the code that you’re going to run 100% open source? 

Yes. See https://github.com/lemire/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We are looking for short-time, focused, bare-metal access.

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

### Describe the monitoring system in use or desired for this project.

I am not planning on using monitoring. All results from investigations will be shared.

### Please state your contributions to the open source community and any other relevant initiatives

Daniel Lemire is a computer science professor at the Université du Québec (TELUQ). He has also been a research officer at the National Research Council of Canada and an entrepreneur. He has written over 70 peer-reviewed publications, including more than 40 journal articles. He has held competitive research grants for the last 15 years. He serves on the program committees of leading computer science conferences (e.g., ACM CIKM, WWW, ACM WSDM, ACM SIGIR, ACM RecSys). During the 2016-2017 NSERC Discovery Grant competition, he received a rating of outstanding for the excellence of the researcher.

He programs in C, C++, Java, JavaScript, Python, Swift and Go. He works primarily in an open-source setting. You can find his software in Git, Apache Hive, Druid, Apache Kylin, Netflix Atlas, LinkedIn Pivot, Microsoft Visual Studio Team Services and so forth. Some of his compression software is used by Apache Arrow and Apache Impala. In 2012, he was rewarded by the Google Open Source Peer Bonus Program.

**Comment by vielmetti** [comment]
Approved.

I've set up a sponsored project in your existing account "TELUQ SIMD Testing [SPONSORED]" with all billing turned off. In that project there's a reserved Qualcomm Centriq 2400 system. We have a handful of these available, and are getting more on some schedule, so it's as good a place as any to start.

I'll introduce you as well to Scott Burns who has been doing Arm SIMD studies as well.

The Qualcomm system is currently dedicated to your account, and is as good a place as any to get started. I've queued you up for access to Ampere, ThunderX2, and Hisilicon Hi1616 systems as well.

**Comment by lemire** [comment]
Wow.

I am even more eager to find new experts than to have access to hardware.

**Comment by vielmetti** [comment]
Keeping this open pending successful expert introductions.

**Comment by lemire** [comment]
+1

**Comment by lemire** [comment]
For the record, there is ongoing work on an ARM port of simdjson. We hope for further collaboration with ARM experts in the "near" future.

**Comment by vielmetti** [comment]
Just to be clear a relevant related issue is https://github.com/lemire/simdjson/issues/20 with some discussion at https://lemire.me/blog/2019/05/03/really-fast-bitset-decoding-for-average-densities/ regarding bitset operations.
