### ISSUE TITLE
Proposal: sled, a lock-free embedded database

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#149]
### Name, email, company, job title

Ed Vielmetti, Packet
Tyler Neely, @spacejam [TBA]

### Project Title and description

sled, a lock-free embedded database

Sled needs to occasionally test the core algorithms at very high levels of concurrency while triggering crashes and then performing validations. It's a relatively new database storage engine (3 years old) and right now the biggest priority is stabilizing it by testing it at high concurrency levels. This embedded database offers dramatically higher performance than the storage libraries that most cloud native systems are relying on (rocksdb, boltdb, badger etc...) and right now the only thing holding it back is that I need to test it in much more torturous ways than I have the hardware to perform at home.

### Which members of the community would benefit from your work?

[TBD]

### Is the code that you’re going to run 100% open source? 

Provide the URLs where it is located, or a Git repository.

https://github.com/spacejam/sled
https://crates.io/crates/sled

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

c1.large.arm (96 core ThunderX)
Potentially other high core-count systems.

### Describe the continuous integration (CI) system in use or desired for this project.

Travis CI for Linux (x64). No Arm testing at the moment.

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.

[TBD]

### Please state your contributions to the open source community and any other relevant initiatives

Brag a little bit about yourself, please!

[TBD]

**Comment by spacejam** [comment]
Thanks for helping fill this out, @vielmetti!

* company, job title: Ferrous Systems, Senior Distributed Systems Engineer
*communities that benefit: users of the Rust programming language, authors of distributed databases, authors of SQL / other rich embedded databases who want a high performance storage engine, mobile developers
* is it 100% open-source? yes! it also has a modular pagecache that others can use to write their own storage engines in relatively little code, using their own indexes etc... 
* monitoring: there is currently no service associated with this library, but if one becomes available I'm happy to make such metrics generally accessible!
* I've been a high-scale user, contributor or author for several open source systems in the Rust, Kubernetes, Mesos, etcd, Cockroach, RocksDB, TiDB/KV, Go, and Erlang ecosystems and want to make the databases we rely on much faster and more reliable.

**Comment by vielmetti** [comment]
Approved! I'll get a machine assigned.

**Comment by vielmetti** [comment]
Approved and a machine assigned, closing this out.
