### ISSUE TITLE
Proposal: gitea

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#151]
### Name, email, company, job title

* @go-gitea 
* Ed Vielmetti, Packet

### Project Title and description

Gitea - git with a cup of tea

Gitea is a lightweight code hosting solution written in Go.

The goal of this project is to make the easiest, fastest, and most painless way of setting up a self-hosted Git service. Using Go, this can be done with an independent binary distribution across all platforms which Go supports, including Linux, macOS, and Windows on x86, amd64, ARM and PowerPC architectures. This project has been forked from Gogs since 2016.11 but changed a lot.

### Which members of the community would benefit from your work?

[TBD]

### Is the code that you’re going to run 100% open source? 

https://gitea.io/en-us/
https://github.com/go-gitea/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

x86 and arm64 systems.

### Describe the continuous integration (CI) system in use or desired for this project.

[TBD]

### Describe the monitoring system in use or desired for this project.

[TBD]

### Please state your contributions to the open source community and any other relevant initiatives

[TBD]

### Additional information

Acknowledgment: [Thanks @packethost and @worksonarm for sponsoring our new build servers.](https://twitter.com/giteaio/status/1088672702167052289) - via Twitter from giteaio

**Comment by vielmetti** [comment]
This is set up and running, will update with details as they emerge.

**Comment by techknowlogick** [comment]
> ### Which members of the community would benefit from your work?
Developers who want an alternative to the centralized Git hosting platforms (ex. Github), and control over their source code.

> ### Describe the continuous integration (CI) system in use or desired for this project.
We use Drone.IO CI to build binaries, and docker images. These artifacts then are uploaded to various distribution sources (such as docker hub for the docker images)

> ### Describe the monitoring system in use or desired for this project.
We use uptime robot to ensure that our Drone instance is running.

> ### Please state your contributions to the open source community and any other relevant initiatives
@go-gitea releases Gitea as completely open source, has 12K+ stars on GitHub, 10M+ downloads on docker hub. We also contribute fixes back to upstream projects (such as Drone.IO for improved integration between Gitea and Drone).
