### ISSUE TITLE
Proposal: HarperDB ARMv7/ARMv8 Cluster Integrations and Testing

### ISSUE THREAD

**Issue by zaxharperdb** [WorksOnArm/cluster#156]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Zachary Fowler
zachary@harperdb.io
HarperDB
Chief Product Officer

Kyle Bernhardy
kyle@harperdb.io
HarperDB
Chief Technology Officer.

unknown (hiring new employee)
<new employee>@harperdb.io
HarperDB
Development Operations Engineer

Note that projects with two or more participants are preferred.

### Project Title and description
HarperDB ARMv7/ARMv8 IoT Implementations.
HarperDB is a small foot print SQL/NoSQL database that runs on NodeJS for ARM architectures.
The project is an effort to create and automate distributed HarperDB database implementations to test and confirm functionality and potential client use cases.

### Which members of the community would benefit from your work?
Operation Technology, Internet Technology and Internet Of Things designers, builders and engineers working with sensors and hardware publishing data to ARM architecture devices and beyond.
 
### Is the code that you’re going to run 100% open source? 
HarperDB core is not open source.
HarperDB Community Edition is Free, there are Enterprise features that require a licenses.
HarperDB plugins,drivers and community projects are and will remain open source.

Provide the URLs where it is located, or a Git repository.
https://github.com/HarperDB
NOTE: HarperDB Core (github.com/HarperDB/harperdb) is not open source and is private.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?  ARMv7 and ARMv8 IoT like devices; 1-8 cores, 1-2.6GHz, 60-120GB SSD/Flash, 1-8GB RAM.  
A network.
Is wireless and/or Cellular possible?
 

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Support should not be completely necessary.  Once the service is provisioned, we have the know how to manage the systems.  Support may only be needed if/when hardware is not acting as expected i.e network outages, ssd/flash corrupt etc..

### Describe the continuous integration (CI) system in use or desired for this project.
Team City. Postman/Newman

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.
Only the current release and release candidates for following releases will be run through this project.
We have our own on-premise server tests for every check-in.
We currently use Jet Brain's Team City tool for deployments and utilize Postman/Newman for building and running the integration tests.

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.
We currently do not have any application monitoring for this project, would be happy to share data, it will certainly be beneficial for us to implement a monitoring tool.  TODO.

### Please state your contributions to the open source community and any other relevant initiatives
HarperDB has community projects for itself (plugins/studio) that are open source, the engineering team has contributed to http://alasql.org/ to help fix bugs, as this is a library HarperDB is currently using.

Brag a little bit about yourself, please!

HarperDB is diligently working on providing an edge solution that does not rely on the cloud to allow companies to perform analytics at the edge in a distributed mesh computing database system.  HarperDB believes the value from data can be extracted without the Rube Goldberg systems currently being utilized by many companies; transacting with a NoSQL to ingest data, migrating that data through an Extract Transform Load (ETL) tool to a data lake and/or a SQL like database where analytics can be performed in a traditional relational manner.  HarperDB was created to shorten this data value chain.

**Comment by zaxharperdb** [comment]
DFW Hisilicon?
Is this an effort to get us in a working group?

**Comment by vielmetti** [comment]
Reopening, in the interest of sorting this out!

**Comment by zaxharperdb** [comment]
Let me know if I can provide more information and/or do anything to help.
Cheers,
Z
