### ISSUE TITLE
Proposal: GoGut

### ISSUE THREAD

**Issue by junaruga** [WorksOnArm/cluster#158]
> If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

> If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

> Note that projects with two or more participants are preferred.

* Alessia Visconti, alesvisc at gmail dot com, King's College London, Research Fellow
* Oliver Giles, olivergiles at protonmail dot ch, SciBite, Data Scientist
* Chen Zhang, zhangchen1983 at gmail dot com, Copenhagen University, PhD student
* Jun Aruga, jun.aruga at gmail dot com, Red Hat, Software Engineer

### Project Title and description

Project Title: GoGut
Description: A genome sequencing, monitoring and analysis on ARM

### Which members of the community would benefit from your work?

* Bio tools communities such as bowtie2.
* Debian/Ubuntu communities
* ARM HPC team.

### Is the code that you’re going to run 100% open source? 

> Provide the URLs where it is located, or a Git repository.

https://github.com/team-gogut
It’s not 100% open source.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

> Let us know if you need short-term (one time) support, or if this is a request for
> continuous ongoing support. If possible, please identify foundations or other
> support organizations that can help with long-running projects.

* We need "Cloud” in the Bare Metal.
* This is a request for continuous ongoing support.
* Foundations or other support organizations: Sanger Institute, Arm, AtoS

### Describe the continuous integration (CI) system in use or desired for this project.

> Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

Yes we would like to do it.
The public URL: https://github.com/team-gogut/yamp-arm

### Describe the monitoring system in use or desired for this project.

> Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.

We are not running the agent right now.
And we are not willing to share it.

### Please state your contributions to the open source community and any other relevant initiatives

> Brag a little bit about yourself, please!

Our project was born from below event at Sanger Institute with Arm and AtoS.
https://www.sanger.ac.uk/innovations/hackathon2018

**Comment by junaruga** [comment]
ping.

**Comment by vielmetti** [comment]
In Bangkok for the week for Linaro Connect! Will address this upon my return next week.

**Comment by junaruga** [comment]
@vielmetti okay, you are attending this event. That's great.
https://connect.linaro.org/

As you know, `qemu-user-static` is a key Arm eco system for users on x86_64 to use Arm base OS.
https://github.com/multiarch/qemu-user-static
Also conda packaging system is a key too.
https://github.com/conda/conda/issues/8297

I wish you enjoy the event, and those eco system would be discussed in the event.

**Comment by junaruga** [comment]
So, is it hard for us to use the server?
