### ISSUE TITLE
Arm64 builders for "Sponsored - Linaro - GNU toolchain" project

### ISSUE THREAD

**Issue by maxim-kuvyrkov** [WorksOnArm/cluster#159]
Linaro Toolchain Working group is successfully using Packet.net's machines for CI of GNU toolchain (Binutils, GCC, Glibc, GDB), and we want to increase the number of configurations we are testing.

### Name, email, company, job title

Maxim Kuvyrkov (representing Linaro Toolchain Working Group), maxim.kuvyrkov@linaro.org, Linaro, Toolchain Tech Lead

### Project Title and description

Sponsored - Linaro - GNU toolchain: https://app.packet.net/projects/a1750e43-50b9-47dd-a0cb-43d8ff7d7b75

### Which members of the community would benefit from your work?

Anyone using GNU toolchain, which includes most Linux distros.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes.  GNU toolchain is 100% open source.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We need long-term leases for arm64 hardware.  At the moment we are using 1x ThunderX1, and we would like to get additional 1x HiSilicon and 1x Amperes machines.

### Describe the continuous integration (CI) system in use or desired for this project.

Jenkins-based Linaro's CI system: https://ci.linaro.org/view/tcwg_gnu/

**Comment by vielmetti** [comment]
This is a good idea, pending availability of gear and some necessary account re-organization. Look forward to getting this sorted out in the next few days.

**Comment by vielmetti** [comment]
@maxim-kuvyrkov - I'm reopening this as some inventory has come free - will contact you via email as well.

**Comment by maxim-kuvyrkov** [comment]
Hi @vielmetti , sorry about the delay.
What do you have available?  We could readily use Arm machines capable of both 32-bit and 64-bit.

**Comment by maxim-kuvyrkov** [comment]
@vielmetti , Hi Ed.  Could you allocate 2 Ampere builders for Linaro toolchain tasks?

**Comment by edolnx** [comment]
Greetings Maxim - We've added two c2.large.arm (Ampere eMAG systems) reservations to this project. They should be available for your use now. If you have questions, feel free to contact us here or on the #worksonarm channel in slack.packet.com
