### ISSUE TITLE
Eclipse OpenJ9 on aarch64

### ISSUE THREAD

**Issue by DanHeidinga** [WorksOnArm/cluster#160]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Dan Heidinga
daniel_heidinga@ca.ibm.com
IBM
Senior Software Developer / Eclipse OpenJ9 Project Lead

### Project Title and description

Eclipse OpenJ9

A Java Virtual Machine for OpenJDK that's optimized for small footprint, fast start-up, and high throughput. 

Eclipse OpenJ9 is an independent implementation of a Java Virtual Machine. "Independent implementation" means it was built using the Java Virtual Machine specification without using any code from any other Java Virtual Machine.

The OpenJ9 JVM combines with the Java Class libraries from OpenJDK to create a complete JDK tuned for footprint, performance, and reliability that is well suited for cloud deployments.

### Which members of the community would benefit from your work?

OpenJ9 provides a JVM that has a small footprint, fast start-up, and high throughput.  A port to aarch64 will provide benefits to anyone running Java on ARM by providing a JVM that scales from embedded to server class configurations.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

The Eclipse OpenJ9 project is 100% open source.  It combines with the Eclipse OMR project and the OpenJDK project to provide a 100% open source JVM.

https://github.com/eclipse/openj9
https://github.com/eclipse/omr

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

This is a request for continuous ongoing support. 

For most platforms, OpenJ9 is currently using ~4 machines, with 8 cores, 8 gig ram, 100+ gig hard drives.

On the AdoptOpenJDK slack, we discussed starting with a ThunderX machine.

### Describe the continuous integration (CI) system in use or desired for this project.

OpenJ9 uses Jenkins CI.  We run a mix of nightly testing builds and per-pull request builds across a wide variety of OSes (windows, linux, mac, AIX), platforms (x86, ppc, ppcle, s390) and Java releases (8, 11, 12, head). 

### Please state your contributions to the open source community and any other relevant initiatives

I'm one of the Project Leads for the OpenJ9 project.  My contributions to the project include the initial code push, lots of reviews, debugging and support for user-raised github issues.  I'm also one of the top-6 contributors to the project.

**Comment by vielmetti** [comment]
This looks good - I am coming back from travel (and jet lag) and hope to clear the queue of outstanding requests this week or early next.

**Comment by DanHeidinga** [comment]
@vielmetti Is there anything I can do to help progress this request?

**Comment by vielmetti** [comment]
Hi @DanHeidinga -

There's a pretty good sized batch of Packet Arm infrastructure that I'm pushing forward to being ready to use, and some additional gear from some projects that are winding down that should also come on line shortly. I'm all in favor of this request and will get it sorted out as soon as it's feasible.

**Comment by vielmetti** [comment]
I want to keep this open. (We are finalizing an agreement with Arm for the next year of the project, and this has been gated on  getting a clear understanding of what the next year will focus on. Apologies for delays.)

**Comment by DanHeidinga** [comment]
Hi @vielmetti Anything I can do to help move this forward?

**Comment by edolnx** [comment]
Greetings Dan - We've created a new project for you and added a reservation for a c1.large.arm instance with is a ThunderX server. You should already have the invite in your email, but if you have issues please don't hesitate to reach out. Ed and I can both be found in the #worksonarm channel of slack.packet.com
