### ISSUE TITLE
Proposal: [Your project name here]

### ISSUE THREAD

**Issue by ferranti-os** [WorksOnArm/cluster#162]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Anthony Ferranti
ferranti@os.amperecomputing.com
Ampere Computing
Senior Staff Engineer, Software Solutions

Daniel Goehring
dgoehrin@os.amperecomputing.com
Ampere Computing
Senior Staff Engineer, Software Solutions

Note that projects with two or more participants are preferred.

### Project Title and description

OpenOCD
Port OpenOCD to work on Ampere eMAG platforms.

### Which members of the community would benefit from your work?

Members using OpenOCD to debug eMAG and other ARMv8 platforms.

### Is the code that you’re going to run 100% open source? 

Yes, it is an existing GPLv2 licenced project.
- http://openocd.org/
- https://sourceforge.net/p/openocd/code/ci/master/tree/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

eMAG 8180 Development Platform with network access.  Would also like to discuss the possibility of outfitting a system with a JTAG debugger (Ed - I am at the RedHat Summit so when we meet up I can discuss in more details)

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

Currently, the OpenOCD uses a Gerrit CI checker.  Dan and I are just getting involved in the project, but can envision a future where ARMv8  specific features are tested on a cloud deployed bare-metal infrastructure.  The bonus is other users can then use the debug tools in the cloud for their own test and debug.
 
### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.

We have not gotten that far yet.

### Please state your contributions to the open source community and any other relevant initiatives

We are new to the open source community.  Dan has begun interacting with the OpenOCD community to solve some bugs in the project we encountered.   Once those are resolved, we have some configuration files for eMAG8180 which we plan to upstream, as well as a list of feature limitations we would like to tackle.

**Comment by vielmetti** [comment]
@ferranti-os  - I will track down Daniel at Red Hat Summit and talk this through - we'll also want to loop in My on the specfics

**Comment by ferranti-os** [comment]
Daniel is not at the RedHat Summit.  I, however, am.  David Hiu, Mauri Whalen, and I were actually trying to meet up with you to set up a demo.  I’m in the main lobby.  mauri and David are in the expo hall.

--Tony Ferranti

[AMPERE_email]

www.amperecomputing.com<http://www.amperecomputing.com>
aferranti@amperecomputing.com<mailto:aferranti@amperecomputing.com>
1009 Think Place, Morrisville, NC 27650
+1-984-208-2056
