### ISSUE TITLE
Proposal: OpenEmbedded and Linux native builds for LKFT

### ISSUE THREAD

**Issue by danrue** [WorksOnArm/cluster#164]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Dan Rue, dan.rue@linaro.org, Linaro, LKFT lead
Daniel Díaz, daniel.diaz@linaro.org, Linaro, LKFT CI

### Project Title and description

The [Linux Kernel Functional Test (LKFT)](https://lkft.linaro.org/) project would like to assess arm-native builds and cross building from arm, using gitlab-ci.

### Which members of the community would benefit from your work?

We work with the upstream Linux development community to improve the quality of the Linux kernel by doing CI and functional testing on ARM hardware.

### Is the code that you’re going to run 100% open source? 

Yes. The repo has not been created but will be at https://gitlab.com/Linaro. All of LKFT is public and open source.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

c1.large.arm is sufficient

### Describe the continuous integration (CI) system in use or desired for this project.

TBD

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.

n/a

### Please state your contributions to the open source community and any other relevant initiatives

Thanks!

**Comment by vielmetti** [comment]
Approve, account set up

**Comment by vielmetti** [comment]
Removed "wontfix" label.

**Comment by vielmetti** [comment]
From the project lead:

```We're happy to report that we have concluded our research on the Works
On Arm project for LKFT/OE! Because we're rebuilding our entire
infrastructure (sort of LKFT 2.0), we're not currently running any
pipelines on the Arm server anymore. I have destroyed the instance we
had been using so it is now available for anyone else to use.```
