### ISSUE TITLE
Access request for the Wireshark project

### ISSUE THREAD

**Issue by crondaemon** [WorksOnArm/cluster#165]
### Name, email, company, job title

Dario Lombardo, dario@wireshark.org, Wireshark, core developer

### Project Title and description

Wireshark

### Which members of the community would benefit from your work?

Wireshark has a very large user base. ATM it's has not official support on arm, but it can be compiled on many platforms, and I would like to add a CI builder on arm as well, as part of my effort in building builders (see https://wiki.wireshark.org/DarioLombardo). 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

www.wireshark.org

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

I suppose I could go with cloud.

### Describe the continuous integration (CI) system in use or desired for this project.

Official builders are based on buildbot. I have worked on support for travis, gitlab-runner, appveyor, semaphore, which are not official builders, but are actively working for the community.

### Please state your contributions to the open source community and any other relevant initiatives

I am a member of the core development team of Wireshark and maintainer of PCAPRUB (pcap ruby bindings). I am a maintainer of ruby-smpp as well, although the project is a bit stale nowadays. I have contributed to more than 15  open source projects, mainly on github (https://github.com/pulls?q=is%3Apr+author%3Acrondaemon+archived%3Afalse+is%3Aclosed)

**Comment by vielmetti** [comment]
Hi @crondaemon  - happy to get this set up. I'll send details by email.

**Comment by vielmetti** [comment]
We've sorted out arrangements and I've set up an account, so we're good to go here.
