### ISSUE TITLE
request for access: daurnimator

### ISSUE THREAD

**Issue by daurnimator** [WorksOnArm/cluster#166]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Daurnimator, quae@daurnimator.com

### Project Title and description

I work on various Lua projects. In particular I was referred here as a way to test out solutions to https://github.com/wahern/cqueues/issues/223

### Which members of the community would benefit from your work?

Lua developers/users

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes.
  - https://github.com/wahern/cqueues 
  - https://github.com/wahern/luaossl/
  - https://github.com/LuaJIT/LuaJIT/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

> Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Probably just short term. I just need compute on an arm64 device with >47 bit pointers.

### Describe the continuous integration (CI) system in use or desired for this project.

This will be for manual testing during bug fixing.

### Please state your contributions to the open source community and any other relevant initiatives

I work on a wide swathe of open source projects; many core pieces of the lua ecosystem, I'm an [Arch Linux Trusted User](https://www.archlinux.org/people/trusted-users/#daurnimator), I help run the [hashbang](https://github.com/hashbang) project. These days I also work on Zig.
Check out my github profile for whatever I'm working on this month :P

**Comment by edolnx** [comment]
Greetings Daurnimator - We've created a project within the Works on Arm project in the Packet portal for you and added a reservation for a c1.large.arm (ThunderX system). You should have an email for that waiting for you. If you need help or have questions, please feel free to reach out to us here or in the #worksonarm channel in slack.packet.com

**Comment by vielmetti** [comment]
Hi @daurnimator  - thanks for taking a look at this.

We have some experience with Lua, especially in dealing with the `lightuserdata` data type.  You might find theses issue useful to orient you

- https://github.com/openresty/lua-nginx-module/issues/1152
- https://github.com/neovim/neovim/pull/7880
- https://github.com/LuaJIT/LuaJIT/pull/230
- https://github.com/PowerDNS/pdns/pull/6512

Closing this issue (as the reservation has been set up) but do feel free to contact us on questions.
