### ISSUE TITLE
Proposal: KintoHub ARM Cluster Request

### ISSUE THREAD

**Issue by Disturbing** [WorksOnArm/cluster#17]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just commenting, ignore/delete those fields and file your issue.

### Contact/Info
Joseph Cooper, joseph at kintohub D-O-T com, KintoHub Limited, CEO

Team size  4x engineers, 1 UI/UX, 1x product, 1x marketing

### Project Title and description
KintoHub

Kintohub is solving the problem of organizing the world's code to help companies avoid writing the same code over and over again.  They are building a platform that allows easy discovery of microservices and creates an ecosystem for developers to monetize their code.  Companies can find a wide range of scalable microservices and deploy them to a cloud of their choice in a few clicks, and be up and moving with their product quickly. There has been some movement in this space but no one has focused on the discovery, trust in third-party code, or developer incentives in addition to infra savings.

### Which members of the community would benefit from your work?
Everyone - cheaper cloud infra with shared microservices! Doing it on Arm, could only imagine the savings compared to traditional CPUs!

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
We will have 5+ frameworks that are open source. They are currently closed source and will be open in 4-6 weeks.  Please email me for early access.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
We're seeing up k8s clusters. 2x tiny but mighty and 1x armv8 would be great!

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Short term help would be any resources that can point us to setting up k8s successfully on your platform. As that progress goes on having a technician avail (Via email) for 1 week during our integration for any blockers would be immensely helpful.

### Please state your contributions to the open source community and any other relevant initiatives

Built 15+ Games in the last 6 years in 2x companies
Survived 10M+ Downloads and built infra to sustain 200M+ USD in transactions per year
I was born from open source communities 10 years ago, learned Java from some amazing mentors which aided me to find my passion yet - only contributed o one open source proj: https://github.com/Disturbing/suice
Today looking to do the exact opposite and empower people to share + deploy **compatible** open source projects more easily

**Comment by vielmetti** [comment]
@Disturbing -

In your initial query you mentioned that your work was closed source but that would be opened up in "4 to 6 weeks". Can you update this if you are still interested? Thanks!
