### ISSUE TITLE
Proposal: Yoe Distribution CI builder

### ISSUE THREAD

**Issue by cbrake** [WorksOnArm/cluster#173]
### Name, email, company, job title

Cliff Brake, cbrake@bec-systems.com, BEC Systems LLC, Engineer
Khem Raj, raj.khem@gmail.com, Himvis LLC, Embedded Linux Engineer

### Project Title and description

Yoe Distribution

http://yoedistro.org/

Yoe is an Embedded Linux Distribution optimized for product development. It is built on Yocto and OpenEmbedded with a focus on simplicity. This distribution does not end at demo images but rather begins there.

### Which members of the community would benefit from your work?

General members of the Yocto/Openembedded communities, and people building products/systems that use Embedded Linux.

### Is the code that you’re going to run 100% open source? 

Yes

https://github.com/YoeDistro/yoe-distro

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Something like a c1.large.arm would work well.

### Describe the continuous integration (CI) system in use or desired for this project.

https://drone.io/

Our current dashboard:

https://drone.yoedistro.org/YoeDistro/yoe-distro/

We are just starting CI setup, but would like to expand this to do a lot more.

### Describe the monitoring system in use or desired for this project.

Nothing yet, but I can imagine setting up a Prometheus/Grafana system for monitoring.

### Please state your contributions to the open source community and any other relevant initiatives

* Cliff:
  * Have contributed to various OSS projects (linux kernel, OpenEmbedded, various Go projects, etc) over the past 20 years.
  * http://bec-systems.com/site/
  * https://github.com/cbrake
* Khem
  * Embedded Linux, Compiler, build system expert
  * https://github.com/kraj

**Comment by kraj** [comment]
+1, I would use such a build system for clang development, yocto development and testing. Which would be a good test for cross building on ARM

**Comment by vielmetti** [comment]
Thanks @cbrake , @kraj .

Since you are using Drone CI for development, is it possible that Drone Cloud would help this effort? http://cloud.drone.io with an announcement at https://blog.drone.io/drone-cloud/ - it supports Arm native builds.

**Comment by cbrake** [comment]
@vielmetti we currently can't use the cloud builder because of disk usage, and need for mounting volumes:

https://discourse.drone.io/t/large-20-60gb-cache/4676/4

In the mean time, we have worked out a solution on some other build resources, so I'll close this for now.
