### ISSUE TITLE
netboot.xyz arm64 support

### ISSUE THREAD

**Issue by antonym** [WorksOnArm/cluster#179]
### Name, email, company, job title
Antony Messerli, antony@mes.ser.li, Rackspace, Principal Engineer

### Project Title and description
netboot.xyz, Leverages the iPXE project to network boot Operating System installers and utilities from an easy to use menu.

### Which members of the community would benefit from your work?
Anyone wanting to quickly boot their OS selection on ARM from the BIOS

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
100% open source
https://github.com/antonym/netboot.xyz

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
A single ARM server or two with remote console access to see if I can get OS support working on the distros that support ARM.  Long term it would be good to have occasional access to test new distros or features.  Usage is mainly for testing booting into the netboot.xyz ARM binary, and testing if Operating System options load and install correctly.  Servers would be spun down once testing is completed.

### Please state your contributions to the open source community and any other relevant initiatives

netboot.xyz, OpenStack, and various other OSS projects

Brag a little bit about yourself, please!
Previously worked with Packet to get netboot.xyz and iPXE functionality working on x86, so hello again!

**Comment by vielmetti** [comment]
@cayu53 please take a look; this would be especially valuable for proving out operating system combos that Packet is not directly supporting.

**Comment by cayu53** [comment]
@vielmetti Agree. Would be good to validate on Arm and as a result have Arm support built-in / available from netboot.xyz and blog about this once tested/available.

**Comment by vielmetti** [comment]
OK, we're all approved. I am on deadline for @cayu53 for today and tomorrow, and once those deadline obligations are in, I'll set this up.

**Comment by vielmetti** [comment]
I've asked @edolnx to help me with this - we are traveling to Techcon so I'll tack this onto the Techcon milestone.

**Comment by vielmetti** [comment]
@antonym  - there is a problem that @stratakis ran into at https://github.com/netbootxyz/netboot.xyz/issues/572 wherein the arch string for CentOS 8 needs to be `aarch64` rather than `arm64`.

**Comment by vielmetti** [comment]
Closing for now, to be resolved upstream.

**Comment by vielmetti** [comment]
Reopening to reflect updated information.

see https://github.com/netbootxyz/netboot.xyz/issues/162

**Comment by pgmwoa** [comment]
Closing the ticket as not considered for WoA program
