### ISSUE TITLE
Ongoing: Node.JS build and test infrastructure.

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#18]
This is a placeholder for an existing project for Node.JS that predates Works on Arm.

### Name, email, company, job title

(contacts from Node.JS project)

### Project Title and description

Build and test Node.JS on Arm.

### Which members of the community would benefit from your work?

(description of Node.JS community)

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

https://github.com/nodejs/node

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

(description of build farm)

### Please state your contributions to the open source community and any other relevant initiatives

(Brag a little bit about yourself, please!)

**Comment by mhdawson** [comment]
# Name, email, company, job title

Node.js build working group, build@iojs.org, Node.js Project, Build team (R,od Vagg, Michael Dawson + others)

# Project Title and description

Build and test Node.js on Arm.

Build and test of Node.js binaries on arm, as well as generation of binaries available on https://nodejs.org/en/download/.

# Which members of the community would benefit from your work?
Node.js is a large and growing community and arm support is important for use on smaller devices and a broader range of hardware. 

# Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

https://github.com/nodejs/node

# What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Arm is the primary need at the moment as we don't have existing cloud based donations, however general Intel resources are also widely used within the project.


Our build farm current spans 8 architectors and 6 operating systems and over 116 machines.  See this earlier presentation for more info: https://www.youtube.com/watch?v=5W3KRKdbmdM.

# Please state your contributions to the open source community and any other relevant initiatives

With 8.8 million instances of Node.js online, 3 billion downloads from npm, 1500 contributors and over 40,000 stars on github Node.js is undeniably one of the leading runtimes.  See https://medium.com/the-node-js-collection/node-js-state-of-the-union-blog-2017-ed86640ec451 for more details.  All of this is based on the build, test and releases which are supported by the infrastructure put in place by the build working group based on the contributions from hardware donators.

**Comment by mhdawson** [comment]
@vielmetti I took a first pass and have also asked the rest of the build WG to comment if they have suggestions.  Please let me know if this looks reasonable  or you need more detail in some sections.

**Comment by vielmetti** [comment]
Thanks @mhdawson - this is good.

**Comment by mhdawson** [comment]
@vielmetti  good to hear.  Let me know if you need anything else.

**Comment by vielmetti** [comment]
Closing this issue as substantially complete!
