### ISSUE TITLE
Proposal: OSEC

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#184]
### Name, email, company, job title

Note that projects with two or more participants are preferred.

* Ed Vielmetti, Packet @vielmetti 
* Richard Henwood, Arm

### Project Title and description

OSEC

### Which members of the community would benefit from your work?

All, especially those who are using libraries provided by
supported languages

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, there is a wide variety of libraries tested under this effort,
and rather than list them all here please note that this is happening
under the auspices of the OSEC group organized through Linaro.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

TBD. Probably at least two arm64 machines that would be long-running
to do porting work, and then perhaps spot market access to other systems.

### Describe the continuous integration (CI) system in use or desired for this project.

There are many projects that would be helped by this effort, each of which 
has its own CI system.

### Please state your contributions to the open source community and any other relevant initiatives

Ed organizes Works on Arm. Richard does ecosystem work for Arm.

**Comment by cayu53** [comment]
@vielmetti - the scope/description is very vague, it would be good to know a bit more who will effectively drive the porting/testing activity over time and ensure there is an effective use of resource. Should coordinate with Richard to better understand.

**Comment by vielmetti** [comment]
New c2.large.arm system has been allocated, with the understanding that the two projects involved will share a single server using containers for isolation.
