### ISSUE TITLE
zig programming language

### ISSUE THREAD

**Issue by markfirmware** [WorksOnArm/cluster#185]
### Name, email, company, job title

Mark E Kendrat
https://github.com/markfirmware
No Company
Computer Engineer

### Project Title and description
Zig is a general-purpose programming language designed for robustness, optimality, and maintainability.

https://github.com/ziglang/zig
cc @andrewrk

### Which members of the community would benefit from your work?
zig programmers
raspberry pi programmers

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes
https://github.com/ziglang/zig
https://github.com/markfirmware/zig-bare-metal-raspberry-pi

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

c1.large.arm
login to install zig and diagnose https://github.com/ziglang/zig/issues/2934 - the exception occurs on pi bare metal and I’d like to see if it occurs on a native system

expect to implement ci for building zig for aarch64 - https://github.com/ziglang/zig/issues/2443

### Describe the continuous integration (CI) system in use or desired for this project.
to be determined - if github actions can defer to a worksonarm runner, then that is the ticket

### Please state your contributions to the open source community and any other relevant initiatives
working on zig on pi bare metal

Brag a little bit about yourself, please!

**Comment by daurnimator** [comment]
FYI I already have worksonarm access for zig.

**Comment by vielmetti** [comment]
At https://github.com/ziglang/zig/issues/2443 I also note the availability of Drone Cloud and Travis CI, both with native (not QEMU) based arm64 support.

**Comment by andrewrk** [comment]
I'm tinkering with Drone Cloud. I have been unable to find a list of supported architectures in the docs, has anyone found this list?

**Comment by markfirmware** [comment]
I haven’t seen the list but I’m using arm64.
https://github.com/ziglang/zig/issues/2934#issuecomment-546037460

**Comment by vielmetti** [comment]
The related issue is #166 (existing access)

**Comment by andrewrk** [comment]
I found this: https://docker-runner.docs.drone.io/configuration/platform/

I'm doing pretty good with the aarch64 target. I rented a scaleway server for a few hours and built https://github.com/ziglang/docker-zig for aarch64. For 32 bit arm, I'm a bit stuck, how can I make a docker image for 32 bit arm? Is there an arm32 server I can rent for a couple hours?

**Comment by andrewrk** [comment]
@markfirmware email me your RSA public key and preferred username and I will give you ssh access to the box

**Comment by markfirmware** [comment]
@andrewrk will do when I’m back Saturday morning

**Comment by andrewrk** [comment]
We have ARM 64 downloads available on https://ziglang.org/download/ now :-)

**Comment by andrewrk** [comment]
I really hate the idea of stalebot, even though this is exactly the use case for it.

This isn't even my issue, and this is the perfect use case for stalebot, and I'm still upset about it.

**Comment by vielmetti** [comment]
Apologies @andrewrk for stalebot; that's mostly my fault, for not figuring out a quiet but effective way to stay on top of all of this.

I am happy for the Zig announcements! I think this particular issue can be closed out.
