### ISSUE TITLE
armv8 hardware for postmarketOS

### ISSUE THREAD

**Issue by ollieparanoid** [WorksOnArm/cluster#186]
### Name, email, company, job title

Most interested in the Works On Arm cluster are:

* [Oliver Smith](https://gitlab.com/ollieparanoid), ollieparanoid-at-postmarketos.org, project lead
* [Luca Weiss](https://gitlab.com/z3ntu), luca-at-z3ntu.xyz, developer, admin for sourcehut instance we plan to deploy
* [Martijn Braam](https://gitlab.com/MartijnBraam), martijn-at-brixit.nl, developer and infrastructure hosting/admin
* [Bart Ribbers](https://gitlab.com/PureTryOut), bribbers-at-disroot.org, developer, maintainer of a great amount of postmarketOS and Alpine packages

### Project Title and description

It is possible to install a Linux distribution on a ten year old PC and make it usable again, at least for basic tasks like listening to music, watching videos and playing retro games in emulators. All with up to date software, and with the additional benefits that the Linux and open source ecosystem brings to the table. There is no advertising in the applications, no tracking, users are not forced to sign up for services, and of course they have the full rights to use, study, share and improve the software. We want to have this for phones. [postmarketOS](https://postmarketos.org) aims for a ten year life-cycle for smartphones.

### Which members of the community would benefit from your work?

From postmarketOS:
* Anyone who wants a more sustainable architecture for smartphone operating systems. Be it directly through using postmarketOS after we leave alpha, or through the related projects that we collaborate with ([Plasma Mobile](https://www.plasma-mobile.org/), [ubports](https://ubports.com/), [Maemo Leste](https://maemo-leste.github.io/), ...)
* Any project that benefits from [patches that we upstream](https://wiki.postmarketos.org/wiki/Upstreaming) (e.g. Alpine Linux)

From collaborating with WorksOnArm specifically:
* Building ARM packages for the official binary package repository without using an emulation layer makes the builds faster, and avoids bugs introduced by emulation ([like this one](https://gitlab.com/postmarketOS/pmbootstrap/issues/546), fix was upstreamed).
* Binary repository: building ARM packages in parallel with x86_64 packages is a huge performance gain.
* Binary repository: stable and edge branch, and even possibly nightly packaging for Plasma Mobile and other software that is updated frequently by upstream.
* CI for ARM builds makes sure, that packages don't just build on x86_64 and then possibly break when compiling for ARM as we build them for the binary repository.

(Therefore all developers and users of postmarketOS will benefit.)

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes.

* postmarketOS package build recipes: [pmaports](https://gitlab.com/postmarketOS/pmaports/)
* building packages for the binary repository: [sourcehut](https://sourcehut.org) ([src](https://git.sr.ht/~sircmpwn/?search=sr.ht))
* CI for gitlab: [gitlab-runner](https://gitlab.com/gitlab-org/gitlab-runner/)

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

The smallest ARM instance seems to be [c1.large.arm](https://www.packet.com/cloud/servers/c1-large-arm/). This should be more than enough, especially the RAM exceeds what we need - 32 GB would be enough.

(It is important, that we can build for 32 and 64 bits ARM architectures with the machine. I was told, that this is not possible with all ARM servers. But our friends from [Alpine](https://github.com/WorksOnArm/cluster/issues/50) and [Adélie](https://github.com/WorksOnArm/cluster/issues/59) are also building their ARM packages for 32 and 64 bit on packet machines, so I assume that this should not be a problem.)

_Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects._

This is a request for continuous ongoing support, so we can keep building new binary packages as we update the build recipes, and so we can keep using CI for ARM.

### Describe the continuous integration (CI) system in use or desired for this project.

Desired:
* gitlab CI: proposed changes to our [package built recipes](https://gitlab.com/postmarketOS/pmaports/) get built for armhf (armv6), arm7, aarch64 on a packet.net server, using "gitlab-runner"
* Binary repository: [build.postmarketos.org](https://build.postmarketos.org/) manages builds on [sourcehut's CI service](https://builds.sr.ht/). x86 builds would run on sr.ht (the officially hosted sourcehut instance), all ARM builds would run with a self-hosted sourcehut instance on packet.net. Once a package is built, it gets uploaded to builds.postmarketos.org.

### Please state your contributions to the open source community and any other relevant initiatives

postmarketOS was started by yours truly in 2017, and kicked off a community of like-minded developers interested in alternative, Linux based smartphone operating systems. Thanks to everybody who helped and made it grow, today we have hundreds of people in the various postmarketOS chat rooms and over 3000 reddit subscribers, discussing what can be done to improve the situation. More writing goes on in the project's wiki, which has become a good resource for finding information about booting and running Linux on >140 devices that are known to run postmarketOS (most of them are phones).

This project makes it easy to get involved with Alpine Linux and running something that is not Android on your phone. Even getting involved with open source in general, quite a few people have reported that they made their first pull or merge request in order to contribute to postmarketOS. In total, we have almost 2000 merge requests as of writing.

More advanced developers of the postmarketOS community even work on [mainlining their phones](https://postmarketos.org/blog/2019/06/23/two-years/#google-samsung-galaxy-nexus). But enough of the bragging, there are a lot of shiny pictures on the website's blog for the curious :wink:

**Comment by cayu53** [comment]
Thanks @ollieparanoid  for your request. With resource we currently have we are prioritizing projects focusing on infrastructure / cloud native and will not be able to support your request at this time. We may revisit in the future as things develop.

Best regards,

**Comment by ollieparanoid** [comment]
I see, thanks @cayu53.
