### ISSUE TITLE
Request for ARM CI for an open source machine learning project

### ISSUE THREAD

**Issue by Wetrain** [WorksOnArm/cluster#188]
### Name, email, company, job title

Adam.Jones (adam@libreml.org), Codethink, Software engineer
Christopher Phang(chris@libreml.org), Codethink, Software engineer

### Project Title and description
LibreML:

We provide ready-made docker containers that give a reproducible, open source SDK for machine learning, with all components built from source using Buildstream

### Which members of the community would benefit from your work?

We have discovered some issues where some common ML libraries are NOT tested on ARM, which is something we would like to solve, as this could lead to unstable/unpredictable results on ARM platforms: https://gitlab.com/libreml/libreml/issues/110

Anyone working in the Machine Learning/AI industry, especially people working in free software or education will benefit from these improvements.

Along side this, having fast CI will enable us to keep development times down to encourage more contributions as people are not waiting for slow build to complete.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes libreML is 100% open source, located on Gitlab.

https://gitlab.com/libreml/libreml

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

A c1.large.arm would be great, as this would enable us to keep up with the current x86 demand in the CI.

Once we have access to the machine, we can setup Gitlab runners and the maintenance required will be minimal after that.

### Describe the continuous integration (CI) system in use or desired for this project.

We will be using GitlabCI to build and test libreML for both ARM and x86, the Arm machine will act as an elastic gitlab runner which can run jobs when needed for CI.

### Please state your contributions to the open source community and any other relevant initiatives

Adam Jones, is a contributor to freedesktop-sdk, which is a an open source linux runtime: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

Chris Phang, is the founder of LibreML

**Comment by Wetrain** [comment]
Hey!

Any update on our request? :smiley:

**Comment by vielmetti** [comment]
Reopening this to re-evaluate.

**Comment by vielmetti** [comment]
Email sent to the team, @Wetrain - please review!

**Comment by Wetrain** [comment]
Thanks @vielmetti, sorry for the delay, the email slipped through the net. We will review ASAP

**Comment by vielmetti** [comment]
This has been approved and is underway.
