### ISSUE TITLE
google/gVisor  CI

### ISSUE THREAD

**Issue by lubinsz** [WorksOnArm/cluster#189]
Kind attention: @kalyxin02 @xiaobo55x
Name, email, company, job title
Bin Lu,  bin.lu@arm.com, Arm, Staff software engineer

Project Title and description
gVisor(https://github.com/google/gvisor) is a user-space kernel, written in Go, that implements a substantial portion of the Linux system surface. 

Which members of the community would benefit from your work?
Currently there are a bunch of contributions for this project, and together there is a need to have the fundamental integration test and unit test publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support, and thus appeal more gViosr developers to utilize this project.
Also the google guys wants me to build an ARM CI for it.

Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes.

https://github.com/google/gvisor

What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
Require access to ARM based Type 2A servers. Still in planning phase of how many, but starting off one should be sufficient.

As such - no long term support need is currently envisioned.

Please state your contributions to the open source community and any other relevant initiatives

I have enabled gvisor KVM platform to support Arm64.  And also I delivered several patches to enable other modules, such as loader/arch/pagetable...
Currently, the google guys want to run the kvm CI cases on Arm64 server.

Please let me know if you need more information.
Thanks!!

**Comment by cayu53** [comment]
I assume that this is in response (and support of) https://github.com/google/gvisor/issues/1231

Happy to see one platform used to support this work. It would help if you could update this issue once things are in place and CI is running for Arm64 (and let the community know). If/when over time the upstream project has access to other Arm-based platforms for doing CI it would be good to update this ticket to provide visibility so we can review the needs etc.

Thanks,

**Comment by kalyxin02** [comment]
Hi Philippe,

Our team member Bin is currently working on that. Will update the ticket once we have progress.

Thanks
Kaly

**Comment by lubinszARM** [comment]
cc @avagin @prattmic

**Comment by vielmetti** [comment]
Hi @lubinsz - do you know which CI system you will be planning to use for this?

**Comment by lubinsz** [comment]
Hi @vielmetti 
It should be google kokoro ci system: https://github.com/googleapis/google-cloud-cpp/tree/master/ci/kokoro
 @avagin can you update more information?
Thanks.

**Comment by vielmetti** [comment]
This has been approved - I'll follow up as soon as possible with access details.

**Comment by vielmetti** [comment]
@lubinsz - I have allocated one c2.large.arm (Ampere eMag) to a new project, and invited you to it. You can deploy the reserved hardware per these directions:

https://www.packet.com/developers/docs/getting-started/deployment-options/reserved-hardware/

It is quite possible that you'd also want to deploy on the c1.large.arm (Cavium ThunderX) and if you do decide to test or validate there just let me know.

Looking forward to getting any preliminary reports of success, I'll follow the upstream issue.

**Comment by lubinszARM** [comment]
@vielmetti 
Thank you very much.

**Comment by vielmetti** [comment]
Looks like positive progress, based on

https://github.com/google/gvisor/issues/1231

**Comment by lubinsz** [comment]
Hi @vielmetti 
It seems that I can't find my reserved Arm server.
Can you help me to check it?
Thanks.
![image](https://user-images.githubusercontent.com/1996245/76492014-17649480-646a-11ea-9247-ef78837fc608.png)

**Comment by vielmetti** [comment]
Reopening to reflect an access question (server wasn't showing up on available list).

**Comment by vielmetti** [comment]
@lubinsz The access question has been addressed, you should be able to provision the server now.

**Comment by lubinsz** [comment]
Hi @vielmetti 
The issue is gone.
I can access the server now.
Thanks.

**Comment by vielmetti** [comment]
The machine that's supporting this problem is having hardware issues, and it's been difficult to be in touch with the team running this by email. @lubinsz do you have an update?

**Comment by lubinszARM** [comment]
cc @zhlhahaha

**Comment by lubinszARM** [comment]
Hi @zhlhahaha
Can you help to check this issue?
Thanks.

**Comment by zhlhahaha** [comment]
> Hi @zhlhahaha
> Can you help to check this issue?
> Thanks.

Hi @lubinszARM, thanks for informing me. I have replied @vielmetti via email.

**Comment by pgmwoa** [comment]
Closing the ticket as communicated the issue & resolved access of new project owners - Howard.Zhang@arm.com & Justin.He@arm.com
