### ISSUE TITLE
Request for the Parsec project

### ISSUE THREAD

**Issue by hug-dev** [WorksOnArm/cluster#190]
Hi 😃!
Please allow me to make the following request, on behalf of the Parsec team.
FYI: @kushalkoolwal @paulhowardarm @ionut-arm

### Name, email, company, job title

Some of the members of the Parsec project:
* Hugues de Valon
   hugues.devalon@arm.com
   Arm
   Software Engineer

* Ionut Mihalcea
   ionut.mihalcea@arm.com
   Arm
   Software Engineer

* Paul Howard
   paul.howard@arm.com
   Arm
   Principal System Solutions Architect

### Project Title and description

Parsec is the Platform AbstRaction for SECurity, a new open-source initiative to provide a common API to secure services in a platform-agnostic way.

### Which members of the community would benefit from your work?

People wanting strong and easy to use security features on the IoT Edge gateways would benefit from Parsec. People wanting to deploy one application on several platforms using the same security library would benefit from Parsec. People wanting to use those same security features in a variety of programming languages would benefit from that work.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

The Parsec code is fully open-source, under an Apache-2.0 license and [accessible here](https://github.com/parallaxsecond/parsec).

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

No strong requirements as long as Linux can run on it to execute average GitHub Actions workflows (compiling code and doing integration tests).
Taking example from similar requests, a "c2.large.arm" system should be fine!

### Describe the continuous integration (CI) system in use or desired for this project.

We would like to use this instance to set up a **GitHub Actions self-hosted runner** ([cf](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/hosting-your-own-runners)) so we can execute on Aarch64 the workflows we are currently only executing on x86.

### Please state your contributions to the open source community and any other relevant initiatives

The Parsec project is entirely commited to be a good open-source citizen and tries to be the most open possible on his roadmap. We have an open-source community chat and weekly meetings.
As part of the Open-Source Software team in Arm I have been contributing to Mbed OS, Trusted Firmware for Cortex-M, the Rust Programming Language and Rust for embedded repositories.

**Comment by cayu53** [comment]
Happy for this go ahead, I will let Ed/Packet-team assess what platform is best suited for this...

Regards,

**Comment by vielmetti** [comment]
All set -

- invites sent out to project members including @hug-dev - please check your email
- one c2.large.arm server has been reserved to the project

Please see https://www.packet.com/developers/docs/getting-started/deployment-options/reserved-hardware/ - once each of the invites has been accepted, you'll be able to deploy this server with each of your SSH keys installed on it for use.

thanks!

Ed

**Comment by hug-dev** [comment]
That's awesome, thanks a lot 😄!
