### ISSUE TITLE
Emacs docker images

### ISSUE THREAD

**Issue by Silex** [WorksOnArm/cluster#192]
## Name, email, company, job title

Philippe Vaucher, philippe.vaucher@gmail.com (as this is a personal project I don't list my company).

### Project Title and description

Emacs images for docker (https://github.com/Silex/docker-emacs).

This project provides different docker images:

- The main images (~500MB) only contain the runtime dependencies for Emacs to run.
- The `-dev` variants (~1400MB) also contain the build dependencies, the Emacs source (in `/opt/emacs`), and additional
  tools such as [Cask](https://cask.readthedocs.io), [git](https://git-scm.com) and [Python](https://www.python.org).
- The `-alpine` variants (~200MB) follow the same logic as the main images but are based on
  [Alpine Linux](https://alpinelinux.org).

I am currently using the free travis plan to build amd64 images, and it works fine. But I want to add multiarch images (https://github.com/Silex/docker-emacs/pull/38) and I hit a lot of roadblocks... I managed to work around them all (by switching to a private server on gitlab) except for the last one: https://bugs.launchpad.net/qemu/+bug/1861161

Basically cross-building with QEMU fails because of a glibc bug in alpine images. So it looks like the only way out is to build on an actual ARM machine. I cannot use the travis ARM workers because they have an hardcoded 50 minutes job maximum AND you cannot disable ASLR which is required to build previous Emacs versions.

### Which members of the community would benefit from your work?

Anyone using Emacs in its CI. People like @NicolasPetton, @DamienCassou, @purcell, @bbatsov with projects like https://melpa.org, https://github.com/cask/cask or https://github.com/bbatsov/projectile.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, completely open source (both https://github.com/Silex/docker-emacs and https://github.com/emacs-mirror/emacs).

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

I just need a basic ARM worker. The idea would be to add it as the arm32/v7 and arm64/v8 builder of a buildx swarm. For amd64 and i386 I'll use a private box (5$ hetzner cloud machine) that will run a gitlab worker, but of course if you can provide that I'm interested as well :wink:

The only hard requirement is that I need to be able to do `sysctl kernel.randomize_va_space=0` for Emacs to build properly.

### Describe the continuous integration (CI) system in use or desired for this project.

Until now I use travis, but I intend to switch to gitlab in order to accomodate the complex workflow.

### Please state your contributions to the open source community and any other relevant initiatives

I'm basically the maintainer of everything docker related in the Emacs world. See https://github.com/Silex/docker.el and https://github.com/Silex/docker-emacs.

For other projects, see https://github.com/Silex?utf8=%E2%9C%93&tab=repositories&q=&type=source&language= :wink:

**Comment by DamienCassou** [comment]
This would really be awesome. Our Emacs-related FLOSS projects are currently built on ARM but each build takes close to 10 minutes. With the work @Silex is doing, this should go down to around 2 minutes. Thank you @Silex!

**Comment by vielmetti** [comment]
Hey @Silex - just starting to look at this now.

Can you help me figure out whether it's possible to use Drone Cloud (https://cloud.drone.io) to do these builds? It has native Arm support (32-bit and 64-bit) and so builds should be speedy and won't require going through QEMU. I don't know, though, if your ASLR requirement can be met. The Drone machines are at Packet and we're happy to help sort through any config questions that come up.

I've read through https://bugs.launchpad.net/qemu/+bug/1861161 and agree with the suspicion that it has something to do with getdents64() not crossing the 32-bit to 64-bit boundary correctly. It looks like there was an extensive discussion of this about a year ago, at

https://lists.gnu.org/archive/html/qemu-devel/2018-12/msg06063.html

and if I stare at the architecture correctly and compare it to my knowledge of the Ampere systems we have that support both 32-bit and 64-bit code, you might run into the same issues there (i.e. "native" support might still trigger this issue; the only way to know is to try).

**Comment by vielmetti** [comment]
For what it's worth there's an open kernel issue here too:

https://bugzilla.kernel.org/show_bug.cgi?id=205957

from the reading of it there are several plausible approaches to addressing the underlying issue, and not a clear consensus yet on the right way to handle crossing the 32/64 bit barrier for those filesystem calls.

**Comment by Silex** [comment]
@vielmetti: Thanks. I think drone.io suffers from the same limitation as travis (which also has arm64 workers). Also it does not look very flexible (e.g https://discourse.drone.io/t/run-docker-container-in-docker/5704) which can quickly be a problem.

In the meantime to work around the QEMU bug I found an idea at https://bugs.launchpad.net/qemu/+bug/1805913, which is to use an ext4 partition that has `dir_index` disabled.

Anyway, I'll play with both ideas and report.

**Comment by vielmetti** [comment]
Aha, the workaround is interesting. It appears that there's a flag you can hit using `tune2fs` described here

https://gist.github.com/jorandradefig/147d03f1fc96047e3745541732fd5019

e.g. `sudo tune2fs -O ^dir_index /dev/xvda1` to disable that feature for that filesystem.

(what's the old saying? You can tune a file system, but you cannot tune a fish.)

**Comment by Silex** [comment]
Ok, so here are the results:

- Cannot use cloud.drone.io because you cannot disable ASLR: https://discourse.drone.io/t/ability-to-modify-sysctl-kernel-randomize-va-space/6769
- The trick for ext4 without `dir_index` does not seem to work when I test it.

There's still one thing I can try: the QEMU patches that someone wrote that apparently fix the issue, but IIRC the setup was a bit complex.

**Comment by vielmetti** [comment]
@Silex do you have a link or a pointer to those QEMU patches? I think I know enough people in that world to review or hopefully test them.

**Comment by Silex** [comment]
@vielmetti: I'm a bit swamped at work atm so yeah it's a good idea if you can test them :wink: 

https://sourceware.org/bugzilla/show_bug.cgi?id=23960
https://bugzilla.kernel.org/show_bug.cgi?id=205957

**Comment by Silex** [comment]
https://github.com/moby/qemu/issues/9

**Comment by vielmetti** [comment]
Good luck with the proposed workaround (the 32-bit static qemu referenced above)

**Comment by Silex** [comment]
:cry: 

I did `apt install qemu-user-static:i386`. Looks like I need to dig deeper and actually debug QEMU, but this looks so time-consuming...

```
root@earth:~# file /usr/bin/qemu-aarch64-static
/usr/bin/qemu-aarch64-static: ELF 32-bit LSB executable, Intel 80386, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=978c7aee3fbc61500d09d9577e2344083fc447ce, stripped

root@earth:~# ps afx | grep qemu
21031 pts/0    S+     0:00          \_ grep --color=auto qemu
 1036 ?        Ss     0:00 /usr/sbin/qemu-ga --daemonize -m virtio-serial -p /dev/virtio-ports/org.qemu.guest_agent.0
10584 ?        Ssl    0:00      |   |   \_ /usr/bin/qemu-arm-static /usr/bin/make install
28768 ?        Sl     0:01      |   |       \_ /usr/bin/qemu-arm-static /usr/bin/make -C src VCSWITNESS=$(srcdir)/../.git/logs/HEAD all
16718 ?        Sl     0:00      |   |           \_ /usr/bin/qemu-arm-static /usr/bin/make -C ../lisp compile-first EMACS=../src/bootstrap-emacs
16726 ?        Rl    48:24      |   |               \_ /usr/bin/qemu-arm-static ../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -f batch-byte-compile emacs-lisp/macroexp.el
10696 ?        Ssl    0:00      |       \_ /usr/bin/qemu-aarch64-static /usr/bin/make install
10972 ?        Sl     0:02      |           \_ /usr/bin/qemu-aarch64-static /usr/bin/make -C src VCSWITNESS=$(srcdir)/../.git/logs/HEAD all
20397 ?        Sl     0:00      |               \_ /usr/bin/qemu-aarch64-static /usr/bin/make -C ../lisp compile-first EMACS=../src/bootstrap-emacs
20405 ?        Rl    24:09      |                   \_ /usr/bin/qemu-aarch64-static ../src/bootstrap-emacs -batch --no-site-file --no-site-lisp --eval (setq load-prefer-newer t) -f batch-byte-compile emacs-lisp/macroexp.el

root@earth:~# strace -p 16726
clock_gettime(CLOCK_REALTIME, {tv_sec=1584794027, tv_nsec=921230669}) = 0
getdents64(5, /* 0 entries */, 2048)    = 0
_llseek(5, 0, [0], SEEK_SET)            = 0
getdents64(5, /* 5 entries */, 2048)    = 144
tgkill(29984, 29987, SIGRT_2)           = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_REALTIME, {tv_sec=1584794027, tv_nsec=921642405}) = 0
getdents64(5, /* 0 entries */, 2048)    = 0
_llseek(5, 0, [0], SEEK_SET)            = 0
getdents64(5, /* 5 entries */, 2048)    = 144
tgkill(29984, 29987, SIGRT_2)           = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_REALTIME, {tv_sec=1584794027, tv_nsec=922333065}) = 0
getdents64(5, /* 0 entries */, 2048)    = 0
_llseek(5, 0, [0], SEEK_SET)            = 0
getdents64(5, /* 5 entries */, 2048)    = 144
tgkill(29984, 29987, SIGRT_2)           = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_REALTIME, ^C{tv_sec=1584794027, tv_nsec=923201432}) = 0
strace: Process 16726 detached
```

**Comment by Silex** [comment]
What is interesting tho is that the `qemu-aarch64-static` also get stuck. Maybe we are dealing with a different bug than the `getdents` one.

**Comment by vielmetti** [comment]
Closing. This *should* be the sort of task that is easy to do with a hosted CI service; happy to continue to help with identifying blocking issues that make the build difficult.

**Comment by Silex** [comment]
@vielmetti: sorry but I don't understand your comment, you saw the roadblocks I have to deal with.

There are QEMU bugs preventing me from doing this with a hosted CI service. Debugging this is no trivial task and takes tons of time.

What *would* be easy to do is having a ARM box where these issues don't exist.

**Comment by NicolasPetton** [comment]
Philippe Vaucher <notifications@github.com> writes:

> What *would* be easy to do is having a ARM box where these issues
> don't exist.

I can provide an ARM board if that helps.

Nico

**Comment by Silex** [comment]
@NicolasPetton: thanks. Let's keep you as plan B, I'm discussing with @vielmetti for an alternative solution. I'll ping you if needed.

**Comment by cphang99** [comment]
@Silex the [libreML](https://gitlab.com/libreml/libreml) project has arm64 workers (provided by WorksOnARM) that builds [emacs](https://gitlab.com/libreml/libreml/-/blob/master/elements/dev-tools/emacs.bst) as part of its creation of the sdk. We also produce docker images at the end of our CI runs. 

You might be able to use our [images](https://gitlab.com/libreml/libreml/container_registry/eyJuYW1lIjoibGlicmVtbC9saWJyZW1sL2FhcmNoNjQiLCJ0YWdzX3BhdGgiOiIvbGlicmVtbC9saWJyZW1sL3JlZ2lzdHJ5L3JlcG9zaXRvcnkvMTExNjMxOC90YWdzP2Zvcm1hdD1qc29uIiwiaWQiOjExMTYzMTh9) directly already to do your testing, but if you have any other questions, please let us know!

**Comment by Silex** [comment]
@cphang99: we found a solution with @vielmetti and now all my images are multiarch (https://hub.docker.com/r/silex/emacs)

I build from emacs 23.4 and up, including emacs 27.0.91 and master.
