### ISSUE TITLE
CI infrastructure for Debian

### ISSUE THREAD

**Issue by zumbi** [WorksOnArm/cluster#194]
### Name, email, company, job title

Héctor Orón Martínez
zumbi _at_ debian.org
Debian OS contributor

### Project Title and description

CI infrastructure for Debian

Debian is GNU/Linux software operative system. Debian has it's own CI/CD processes to ensure good quality for their products. It would be really beneficial for both parties Debian and ARM to extend Debian QA and CI/CD pipeline with ARM worker nodes.

### Which members of the community would benefit from your work?

- Debian users on ARM
- ARM community

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, the source code is 100% open source, this code is located in Debian source repositories and/or source version control systems.
- http://ftp.debian.org/debian/
- https://salsa.debian.org/public

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Debian runs different services for QA purposes and managed by different people, among those that might be interested on using packet resources are:
- Salsa CI team (already using packet nodes to attach ARM gitlab workers to Gitlab (salsa.d.o))
- Release team (would like to have more ARM nodes for piuparts, debci/autopkgtests, etc.)
- Bit-by-bit reproducible builds (might be good to do timely reproducible builds of the Debian archive and compare results with builds done elsewhere)
- More potential users could be interested on the resources provided.

Depending on the use, continuous support might be needed, as a gitlab worker, those are mostly in use all the time.
Other tasks might be suitable for one-time use, as in spawn a machine, run some processes, shutdown the machine.

### Describe the continuous integration (CI) system in use or desired for this project.

Since Debian has different procedures and this is a generic report, I shall not describe or enter in details, we can ask product owners to file in this section as soon as they like to use packet.net resources.

### Please state your contributions to the open source community and any other relevant initiatives

I am point of contact for Debian and packet.net relationship, however not the individual nor the team driving the effort forward. However since you asked for it, I am part of the Debian System Administrator team, one of the original porters for Debian armel and armhf ports, maintain the official build daemons infrastructure, part of the Debian treasurer team, also board member of SPI (one of the Debian's legal entities that hold Debian assets).

My role in this request is to facilitate the connection between packet.net resources and Debian community. 

Regards

**Comment by vielmetti** [comment]
Thanks @zumbi - I should be able to have this reviewed this week.

**Comment by vielmetti** [comment]
@zumbi - if there are specific requests for resources, they can go here or via email - I will follow up privately regarding a few details, and will close this in the meantime.
