### ISSUE TITLE
request for arm64 server for linuxkit

### ISSUE THREAD

**Issue by deitch** [WorksOnArm/cluster#197]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

* Avi Deitcher, Aptimia
* Justin Cormack, Docker
* Rolf Neugebauer, AWS
* Dave Tucker, RedHat
* Ian Campbell, Docker

Note that projects with two or more participants are preferred.

### Project Title and description

[LinuxKit](https://github.com/linuxkit/linuxkit) is a toolkit for building secure, portable and lean operating systems for containers. It has supported all containers and the core operating system on arm64 as a first-class citizen from day 1, and will continue to do so as long as we have a proper build server.

### Which members of the community would benefit from your work?

docker, containerd, runc, cncf, kubernetes, many many others. It is used as the basis for composing operating systems that run on Packet, AWS, GCP, Azure, AliCloud, on-premise, on raspberry pis, and just about everywhere.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes 100% open source [here](https://github.com/linuxkit/linuxkit)

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Single arm64 node is fine, likely c2.large.arm for ongoing.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe the continuous integration (CI) system in use or desired for this project.

We run our CI via github actions, which can include custom runners. We also do our own direct builds.

### Please state your contributions to the open source community and any other relevant initiatives

Brag a little bit about yourself, please!

LinuxKit is _the_ way to build composed, targeted operating system images. It is installed on just about every engineer desktop in the world, as it underlies docker for desktop on both windows and macOS. It also is used in production in a growing number of companies.

**Comment by vielmetti** [comment]
The server is set up and active, closing this.

**Comment by deitch** [comment]
Thanks Ed
