### ISSUE TITLE
Request for arm64 build server for Wiki.js

### ISSUE THREAD

**Issue by NGPixel** [WorksOnArm/cluster#199]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

### Name, email, company, job title

Nicolas Giard, @ngpixel

### Project Title and description

[Wiki.js](https://wiki.js.org) is an open-source, powerful and modern wiki server application, written in Node.js. It offers multiple editors (Markdown, WYSIWYG, etc.) and over 50+ integrations with external authentication providers, search engines and storage targets. The app has been localized in over 40+ locales thanks to the community.

### Which members of the community would benefit from your work?

Wiki.js is used by millions of users from organizations, NGOs, communities and individuals to organize and publish their documentation.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Wiki.js is 100% open source (AGPLv3 license) and the source code is hosted on GitHub:
https://github.com/Requarks/wiki

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We're looking for a single small ARM64 build server, which would run an Azure DevOps agent to automatically run docker builds for the arm64, armv7 and armv6 platforms (using dockerkit for the last 2 architectures).

Because of the many dependencies of Wiki.js, some modules must be compiled specifically on the arm platform.

### Describe the continuous integration (CI) system in use or desired for this project.

We are using Azure DevOps to automatically build docker images and windows packages.

### Please state your contributions to the open source community and any other relevant initiatives

Lead developer (@ngpixel) for [Wiki.js](https://github.com/Requarks/wiki), contributing 99% of the code for the last 4 years, writing the EN + FR localization and offering free support.

Thanks!

**Comment by vielmetti** [comment]
Hi @NGPixel - we're sorry that we're going to have to pass on direct support for this one. My suggestion is to take a look at Drone Cloud or Travis CI which both have automated CI loops available for doing native arm64 build and test - one or the other of those should let you accomplish the goal you are setting out to do.

**Comment by vielmetti** [comment]
Hi @NGPixel - we're sorry that we're going to have to pass on direct support for this one. My suggestion is to take a look at Drone Cloud or Travis CI which both have automated CI loops available for doing native arm64 build and test - one or the other of those should let you accomplish the goal you are setting out to do.
