### ISSUE TITLE
Cockroach on ARM

### ISSUE THREAD

**Issue by benesch** [WorksOnArm/cluster#20]
### Name, email, company, job title

Nikhil Benesch <benesch@cockroachlabs.com>
[Cockroach Labs](https://cockroachlabs.com), software engineer

### Project title and description

[CockroachDB](https://github.com/cockroachdb/cockroach) is a cloud-native SQL database for building global, scalable cloud services that survive disasters.

### Which members of the community would benefit from your work?

Anyone looking to run CockroachDB on an ARM platform. There are no inherent hurdles to producing an ARM build of CockroachDB, but without an automatic ARM build we've had several commits sneak in (SSE4.2 instructions, hardcoding FPU rounding) that assume x86.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Nearly all of CockroachDB is freely-available under the terms of the Apache License. A few features are enterprise-only and instead licensed under the Cockroach Community License. 

The source code is publicly available on GitHub, including the source for enterprise features: https://github.com/cockroachdb/cockroach

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

A single Type 2A server would be sufficient for our CI. We wouldn't need support beyond the initial provisioning of the machine.

**Comment by vielmetti** [comment]
Approved and ready to start. We talked in email about setting up a shared Slack channel for the project, and there's an email in your inbox to that effect. 

I'm looking forward to getting TeamCity (the CI tool) integrated as well.

**Comment by vielmetti** [comment]
We're setting up a shared Slack channel to handle project communications.

**Comment by vielmetti** [comment]
It looks like the last open issue is a packaging issue, https://github.com/cockroachdb/cockroach/issues/24441

**Comment by vielmetti** [comment]
Reopening to reflect that https://github.com/cockroachdb/cockroach/issues/24441 is still open.

**Comment by vielmetti** [comment]
Reopening to reflect that an upstream issue is still open.

**Comment by vielmetti** [comment]
This project has ended.

**Comment by vielmetti** [comment]
Noted that there is still work being done on this:

https://github.com/cockroachdb/cockroach/pull/48187
