### ISSUE TITLE
Request for kubernetes e2e/unit_test/integration_test CI and future CI on ARM

### ISSUE THREAD

**Issue by lubinsz** [WorksOnArm/cluster#201]
Name, email, company, job title
Bin Lu bin.lu@arm.com, ARM, Staff software engineer

Project Title and description
Kubernetes is an open source system for managing containerized applications across multiple hosts; providing basic mechanisms for deployment, maintenance, and scaling of applications.

Which members of the community would benefit from your work?
Currently there are a bunch of contributions for this project, and together there is a need to have the fundamental UT/IT/E2E publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support.

Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, the project is 100% open source. Please refer to:
https://github.com/kubernetes/kubernetes

What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
Require access to two ARMv8 based nodes now in current stage.
Conformance test requires at least 2 nodes.

Describe the continuous integration (CI) system in use or desired for this project.
For conformance test, please see following link as reference:
https://github.com/kubernetes/test-infra
https://k8s-testgrid.appspot.com/

Please state your contributions to the open source community and any other relevant initiatives
ARM is very actively in open source community and contributes a lot in various open source projects, like Kubernetes, Docker, Google/Gvisor, OpenJDK, DPDK, OpenStack, , etc.
We have enabled kubernetes to support Arm64. And also I delivered several patches to enable it.

My plan for k8s ci on Arm64 is below:
Our plan is to complete the issue of “official multi-platform support”( https://github.com/kubernetes/kubernetes/issues/86295 )  as the first step.

Then, we will continue to discuss the k8s CI on Arm64 issue with upstream.
Please see our issue page in k8s/test-infra as reference, we will resolve this issue as our 2nd step: https://github.com/kubernetes/test-infra/issues/16588

**Comment by lubinsz** [comment]
We have already setup the conformance test on 2 AWS arm64 instances.
Please see the following link as reference:
https://k8s-testgrid.appspot.com/conformance-arm#Periodic%20Arm64%20conformance%20test%20on%20AWS

**Comment by lubinsz** [comment]
cc @cayu53 @kalyxin02

**Comment by vielmetti** [comment]
@lubinsz -

Some questions as we set this up:

Any preference for machine types? This should run equally well on c2.large.arm or c1.large.arm.
Do you have a second person who should be on the project list?

Let me know and I'll reserve a pair of machines.

**Comment by lubinszARM** [comment]
cc @zhlhahaha

@vielmetti 
We have no preference. Maybe the cheaper the better :)
So far, we need to test several CI jobs with 2 environments：
1,  Cloud provider conformance test with 2 hosts
2, For other scenarios, such as e2e/integration, we need to create a few(>4) virtual machines to test

And the second person is @zhlhahaha

**Comment by vielmetti** [comment]
@lubinsz - two systems have been reserved (a pair of c2.large.arm in NRT1) and the two of you have been invited to the project. Contact me direct at ed@packet.com or our support line at help@packet.com if there are any issues!
