### ISSUE TITLE
Add 2-4 more ARM64 machines to LLVM buildbot CI

### ISSUE THREAD

**Issue by maxim-kuvyrkov** [WorksOnArm/cluster#202]
### Name, email, company, job title

Name: Maxim Kuvyrkov
Email: maxim.kuvyrkov@linaro.org
Company: Linaro
Job title: Toolchain Tech Lead

### Project Title and description

LLVM Toolchain CI Buildbots for ARM64

### Which members of the community would benefit from your work?

LLVM community relies on buildbot infrastructure (http://lab.llvm.org:8011/) for continuous integration and testing of llvm projects.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, 100% open source: http://llvm.org/ .

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

In https://github.com/WorksOnArm/cluster/issues/42 LLVM buildbots were allocated 1x Taishan 64-core ARM64 machine, which works great, but it is under a continuous load of 4-5 times that it can handle (i.e., 400 processes competing for 64 cores).

Would you please allocate another two HiSilicon Taishan or four Ampere eMAG machines to LLVM Buildbot CI?

We have tried to use ThunderX1 machines, but, unfortunately, they crash within hours on LLVM CI loads.

This is going to be a long-time allocation.

### Describe the continuous integration (CI) system in use or desired for this project.

LLVM Buildbots: http://lab.llvm.org:8011/

### Please state your contributions to the open source community and any other relevant initiatives

I'm a long-time open-source developer with contributions to GCC, LLVM, Binutils, Glibc, and GDB. My team at Linaro is the owner of AArch64 and AArch32 LLVM buildbots, which we want to migrate to Packet.net hardware.

Thank you!

**Comment by vielmetti** [comment]
@maxim-kuvyrkov 

Do you have any geographic location requirements or preferences? I'm looking at inventory now.

**Comment by maxim-kuvyrkov** [comment]
Hi @vielmetti ,
Any location will do just fine.  Thanks.

**Comment by vielmetti** [comment]
@maxim-kuvyrkov 

As a start I have allocated two c2.large.arm systems additionally to the account, in our Tokyo (NRT1) data center. Please add this capacity to your system and then let me know where you stand so that I can any more servers as required.
