### ISSUE TITLE
Request for an AArch64 bare-metal instance for the wasmtime project

### ISSUE THREAD

**Issue by raw-bin** [WorksOnArm/cluster#204]
Kind attention: @vielmetti @alexcrichton

### Name, email, company, job title

* Robin Randhawa, robin.randhawa@arm.com, Arm, Technical Director for System Software Architecture

* Alex Crichton, acrichton@mozilla.com, Mozilla, Staff Research Engineer

### Project Title and description

The [wasmtime](https://wasmtime.dev/) run-time for [WebAssembly (WASM)](https://webassembly.org/) and [WASI (modular system interface for WebAssembly)](https://github.com/WebAssembly/WASI).

### Which members of the community would benefit from your work?

Any consumer of the WebAssembly cluster of technologies targeting Arm AArch64 and associated architecture. 

The intent here is for Arm and the WASM communities to collaborate and make Arm v8.x a best in class target architecture for WASM.

This has important ramifications for multiple application domains from the edge to the cloud. A good overview of how these technology clusters are beneficial for safety and security is available [here](https://hacks.mozilla.org/2019/11/announcing-the-bytecode-alliance/).

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes.

https://github.com/bytecodealliance/wasmtime/
and also: https://github.com/WebAssembly

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

* One Ampere eMag "c2.large.arm" system
* Short-term support

The request is to provide a bare-metal AArch64 instance which will be maintained by Arm and the WASM team (represented presently by Alex Crichton) collaborating on the CI aspects and beyond.

As such - no long term support need is currently envisioned. 

The instance itself should be required for a long term though (1 year +) and between Arm and the WASM team we will periodically share how the instance is impacting the progression/improvement of WASM and WASI on AArch64. We have high confidence that access to this instance will be positively and significantly impactful for WASM and WASI on AArch64.

### Describe the continuous integration (CI) system in use or desired for this project.

The expectation is to take ongoing work done by @pietroalbini for using GitHub Actions extended for use with native AArch64 hosts and use that for wasmtime. This may change in the future.

### Please state your contributions to the open source community and any other relevant initiatives

Robin: 

Misc contributions over the years to the Android Linux kernel, FreeBSD kernel, u-boot and misc boot-chains. Robin was the OS power and performance lead at Arm Cambridge and oversaw the implementation of Linux kernel support for Arm's big.LITTLE designs and Linux's Energy Aware Scheduling framework among others. In his spare time Robin hacks on Redox OS (a microkernel based stack written in Rust) to port it to AArch64.

Alex: 

Alex is a member of the Rust Language core team and has his fingerprints on pretty much all of Rust! No seriously!

Please let me know if you need more information. 
Thanks!!

**Comment by alexcrichton** [comment]
Thanks for filing this @raw-bin and I'm also happy to help out if any other info is needed!

**Comment by bjorn3** [comment]
> ### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
> 
> Yes.
> 
> https://github.com/WebAssembly

Shouldn't the url be https://github.com/bytecodealliance/wasmtime/?

**Comment by raw-bin** [comment]
Hi @bjorn3. Although the ask here is for the wasmtime project, it is likely that other related strands from under the WASM umbrella will also benefit so from that stand-point it doesn't really matter. However, to offset any confusion, I'll add this URL to the description just in case.

**Comment by vielmetti** [comment]
Collaborators listed above have been invited to a new project, and a server has been reserved to it. Let me know when you have things set up!

**Comment by alexcrichton** [comment]
Thanks @vielmetti! I've allocated a server and we're all setup now and it all looks good :)
