### ISSUE TITLE
Request for an AArch64 bare-metal instance for the Cloud Hypervisor project

### ISSUE THREAD

**Issue by MrXinWang** [WorksOnArm/cluster#205]
Kind attention: @kalyxin02 @michael2012z @rbradford

### Name, email, company, job title
Michael Zhao, Michael.Zhao@arm.com, Arm, Staff software engineer
Henry Wang, Henry.Wang@arm.com, Arm, Graduate software engineer

### Project Title and description
Cloud-Hypervisor

Cloud-Hypervisor is an open source Virtual Machine Monitor (VMM) that runs on top of KVM. The project focuses on exclusively running modern, cloud workloads, on top of a limited set of hardware architectures and platforms. Cloud Hypervisor is implemented in Rust and is based on the rust-vmm crates.

The cloud-hypervisor community is accepting PRs to enable AArch64. Currently we are using a github action to cross-build AArch64 code on x86_64 machine in order to make sure these AArch64 PRs can be built. As these PRs are gradually being merged, it is necessary to set up AArch64 CI in order to test everything on real AArch64 platform.

### Which members of the community would benefit from your work?
Currently there are a number of contributions for this project, and together there is a need to have the fundamental integration test and unit test publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support, and thus appeal more cloud-hypervisor developers to utilize this project.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, https://github.com/cloud-hypervisor/cloud-hypervisor

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
Require access to AArch64 based servers. Still in planning phase of how many, but starting off one should be sufficient.

### Please state your contributions to the open source community and any other relevant initiatives
We are delivering patches to enable cloud-hypervisor on AArch64. See cloud-hypervisor [#1168](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1168), [#1223](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1223) [#1232](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1232), [#1238](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1238), [#1293](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1293). Support to this project will be long-term.

### Please let me know if you need more information.
Thanks!!

**Comment by vielmetti** [comment]
This has been approved, I'll update when the system has been allocated.

**Comment by MrXinWang** [comment]
@vielmetti Thanks so much!

**Comment by vielmetti** [comment]
Invitations have been sent and a machine has been reserved to the account, you should be all set.

**Comment by vielmetti** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Cloud-Hypervisor-0.8-Released - news about Cloud Hypervisor 0.8 release with aarch64 support.

**Comment by MrXinWang** [comment]
Hi @vielmetti ! Thanks so much for providing the machine! We can access it perfectly now. I am wondering if you can add the cloud-hypervisor community maintainer @rbradford to the cloud-hypervisor organization in packet.net. His email can be found in https://github.com/rbradford. Thanks!

**Comment by vielmetti** [comment]
Thanks @MrXinWang - I've added @rbradford to the project.
