### ISSUE TITLE
Access for Folding@home

### ISSUE THREAD

**Issue by jcoffland** [WorksOnArm/cluster#208]
### Name, email, company, job title

Joseph Coffland, joseph@cauldrondevelopment.com, Cauldron Development LLC, Lead developer at Folding@home.

### Project Title and description

Folding@home uses the compute resources of volunteers around the world to study human diseases like COVID-19 and cancer.

### Which members of the community would benefit from your work?

A Folding@home client for ARM would allow ARM users to participate.

### Is the code that you’re going to run 100% open source?

No.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We would need long-term access to ARM hardware to build and test Folding@home software on ARM.  Ideally we would have access to ARM machines with GPUs to fully test the F@H client on ARM.

### Describe the continuous integration (CI) system in use or desired for this project.

We currently use Buildbot and Docker.

### Please state your contributions to the open source community and any other relevant initiatives

Some of the Folding@home software is Open-Source.  We have plans to make the client software fully Open-Source.

**Comment by vielmetti** [comment]
Thanks @jcoffland ! There was a team that assembled to help with the port of Rosetta to arm64 - my strong suspicion is that there will be overlap of interest and resources from that team, and I've alerted them to this as well. Stay tuned!

**Comment by edolnx** [comment]
Could you provide some more information about what kinds of GPU devices you are looking for? Packet might be able to put some nvidia T4 GPUs in a couple of hosts, but in the community we have a lot of machines with AMD GPUs because of the current driver situation.

**Comment by jcoffland** [comment]
Any modern GPUs should be fine.  Both NVidia and AMD would be useful since they use different drivers.  We just need to test that they work with our software on ARM.

**Comment by vielmetti** [comment]
I've referred this request to Rex at Arm to get more eyes on it. The current Works on Arm inventory does not include any GPU configurations.

**Comment by jcoffland** [comment]
We also need access to ARM CPUs to compile Folding@home software for ARM.  We would like to setup CI/CD for our client software and two simulation cores, GROMACS and OpenMM.  In addition, we would like access to additional ARM instances to run our ARM client's and cores for testing purposes.  How can get access to these resources?

**Comment by vielmetti** [comment]
Thanks all, this is approved. I'll follow up with @jcoffland on details of access.

**Comment by jcoffland** [comment]
Thanks Ed.

**Comment by vielmetti** [comment]
Machine reserved, invite and introductory email sent. I've set up a single c2.large.arm (Ampere eMag) machine for now.
