### ISSUE TITLE
MariaDB on ARM

### ISSUE THREAD

**Issue by davidwbt** [WorksOnArm/cluster#21]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
David Thompson, dthompson@mariadb.com, MariaDB, VP Engineering

Note that projects with two or more participants are preferred.

### Project Title and description
MariaDB

### Which members of the community would benefit from your work?
Our goal is to enable MariaDB to run on as many platforms and distributions as possible, we are the default relational db on many linux distros.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
All of our code is either GPL, LGPL, or BSL licensed.
https://github.com/mariadb-corporation/
https://github.com/mariadb/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
- Qualcomm Centriq Servers which are not officially listed. Ideally 2 full bare servers (one for builds, one for developer / support testing). We are a qualcomm centriq launch partner.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.
Qualcomm centriq would be long term. We'd be also be interested in other architecture servers for benchmarking purposes.

### Please state your contributions to the open source community and any other relevant initiatives
We are the leading open source relational database :)

**Comment by vielmetti** [comment]
This work has been completed.

**Comment by lag-linaro** [comment]
Do you know why MariaDB isn't searchable on the WorksOnArm website?

**Comment by lag-linaro** [comment]
It's there now, thanks for your help.

https://www.worksonarm.com/explore/mariadb/

**Comment by vielmetti** [comment]
A server in the project is currently buidling MariaDB ARM packages for CentOS, Ubuntu, and Fedora.
