### ISSUE TITLE
GitHub Actions workers?

### ISSUE THREAD

**Issue by webknjaz** [WorksOnArm/cluster#210]
Hi, I saw that some aarch64 resources can be requested @ https://www.worksonarm.com/projects/
followed by references to various services. May I ask if it supports running GitHub Actions
self-hosted runners? If I were to request WorksOnArm resources, would it be possible to
integrate such runners?

**Comment by vielmetti** [comment]
There are some notes about using self-hosted runners from GitHub Actions with public repos.

See

https://github.community/t/self-hosted-runner-security-with-public-repositories/17860/10

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories

While there are ways to set up self-hosted runners to make them less risky, the fundamental problem is this:

> Forks of your public repository can potentially run dangerous code on your self-hosted runner machine by creating a pull request that executes the code in a workflow.

**Comment by webknjaz** [comment]
Yeah, that's totally understandable.
