### ISSUE TITLE
CI/CD for Android Cloud Blueprint

### ISSUE THREAD

**Issue by hanyu-D** [WorksOnArm/cluster#212]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### hanyu Ding, dinghanyu@chinamobile.com, Chinamobile，
Note that projects with two or more participants are preferred.
ARM、Ampere

### Project Title and description
IEC Type 3 Android Cloud native application on ARM server in edge
IEC Type3 mainly focus on Android Application running on edge ARM Cloud architecture with GPU/ vGPU Management. Also, ARM cloud games need to have the basic features of "cloud”, such as flexibility , availability everywhere. Based on cloud infrastructure optimized for android application, providing ARM application services such as Android cloud game and VR/AR live video.

### Which members of the community would benefit from your work?
Bytedance, Chinamobile

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
100% open source, has already upload to gerrit. The code link: https://gerrit.akraino.org/r/gitweb?p=iec.git;a=tree;f=src/type3_AndroidCloud;h=da39f2d43bacd9771cea346f65a3d96e2a061ade;hb=HEAD

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
3*ARM server, specifications are:

RAM | 16*DDR4-2933
Storage | 10*2.5 inch SAS/SATA/SSD or 8*2.5 inch  NVMe SSD
Network | 1 onboard network card, each card supports 4*GE port or 4*10GE port or 4*25GE port
Power Supply | Power 100~240V AC，240V DC
Scale | 447 mm x 490 mm x 86.1 mm

### Describe the continuous integration (CI) system in use or desired for this project.
we need ARM pod to run our CI system for IEC TYPE3.

### Please state your contributions to the open source community and any other relevant initiatives
Test introductions in IEC type3: https://wiki.akraino.org/display/AK/R3+Test+Document+of+IEC+Type+3%3A+Android+cloud+native+applications+on+Arm+servers+in+edge

Brag a little bit about yourself, please!

**Comment by vielmetti** [comment]
Closed after review.
