### ISSUE TITLE
ARM64 version of cmake

### ISSUE THREAD

**Issue by galak** [WorksOnArm/cluster#213]
Would like to see the project work with Kitware to have them be able to build arm64 binaries and publish them on a regular basis.  While cmake is available from distro(s) sometimes a newer version is needed and on x86 one can easily grab a release binary package from Kitware.

https://discourse.cmake.org/t/regarding-cmake-aarch64-binary-in-releases-and-cmake-cross-build-host-x86-64-target-aarch64/1109

**Comment by galak** [comment]
https://gitlab.kitware.com/cmake/cmake/-/issues/20122

**Comment by vielmetti** [comment]
Hi @galak thanks for the heads up - if you have a good contact from the Kitware team I'd be happy to have a conversation on this topic.

**Comment by galak** [comment]
> Hi @galak thanks for the heads up - if you have a good contact from the Kitware team I'd be happy to have a conversation on this topic.

I don't, I think looking at https://gitlab.kitware.com/cmake/cmake/-/tree/master/Utilities/Release and adding arm64 linux support would be a huge start.

**Comment by vielmetti** [comment]
Thanks @galak . I'm closing this issue now and have related the relevant info to some contacts who may be able to make progress on getting current arm64 binaries built for cmake. If there's a reason to reopen it I will do so!

**Comment by vielmetti** [comment]
https://gitlab.kitware.com/cmake/cmake/-/issues//17923 looks like the issue to bring up directly with cmake, @galak .

**Comment by vielmetti** [comment]
Also relevant @galak is https://gitlab.kitware.com/cmake/cmake/-/issues/20122 where there is a "snap" based access to images on multiple architectures including aarch64.
