### ISSUE TITLE
Request for an AArch64 bare-metal instance for the Oak project

### ISSUE THREAD

**Issue by ebeasant-arm** [WorksOnArm/cluster#214]
Kind attention: @vielmetti

Name, email, company, job title

Edwin Beasant, edwin.beasant@arm.com, Arm, Staff Software Engineer

Tiziano Santoro, tzn@google.com, Google, Software Engineer

Project Title and description

The goal of Project Oak is to create a specification and a reference implementation for the secure transfer, storage and processing of data.

Which members of the community would benefit from your work?

Any consumer of the Oak cluster of technologies targeting Arm AArch64 and associated architecture, or heterogeneous Oak systems with an aarch64 component.

The intent here is for Arm and the Oak communities to collaborate and make Arm v8.x a best in class target architecture for Confidential Computing.

This has important ramifications for multiple application domains from the edge to the cloud. A good overview of how these technology clusters are beneficial for safety and security is available: https://github.com/project-oak/oak/blob/main/docs/concepts.md.

Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes.

https://github.com/project-oak/oak

What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

One "c2.large.arm" system
Short-term support
The request is to provide a bare-metal AArch64 instance which will be maintained by Arm and the Oak team (represented presently by Tiziano Santoro) collaborating on the CI aspects and beyond.

As such - no long term support need is currently envisioned.

The instance itself should be required for a long term though (1 year +) and between Arm and the Oak team we will periodically share how the instance is impacting the progression/improvement of Oak and CC on AArch64. We have high confidence that access to this instance will be positively and significantly impactful for CC on AArch64.

Describe the continuous integration (CI) system in use or desired for this project.

The expectation is to take ongoing work done by @edwinbeasant for using GitHub Actions extended for use with native AArch64 hosts and use that for Oak. This may change in the future.

Please state your contributions to the open source community and any other relevant initiatives

Edwin:

Misc (smaller, company) contributions over the years to Rust, Wasmtime, Coreboot, Open Solaris, Go, ksh93. Edwin was a Solaris libc tech lead at Sun/Oracle, and has more recently been working as part of Arm's efforts to develop effective support and infrastructure for WASM, WASI, Rust and related projects on aarch64. In his spare time Edwin hacks on aarch64 Linux and  occasionally the Redox kernel.

Tiziano:

Tiziano is a member of the Oak core team and has day to day responsibility of the Oak codebase.

Please let me know if you need more information.
Thanks!!

**Comment by vielmetti** [comment]
This has been approved and will be set up shortly.

**Comment by vielmetti** [comment]
This has been set up, and an introductory message has gone out.
