### ISSUE TITLE
arm64 builds of docker-compose

### ISSUE THREAD

**Issue by galak** [WorksOnArm/cluster#215]
Any assistance in getting arm64 binaries as part of docker-compose project would be great:

https://github.com/docker/compose

https://github.com/docker/compose/issues/7472

**Comment by vielmetti** [comment]
per https://github.com/docker/compose/issues/7472#issuecomment-664848792 the current recommended approach for docker-compose is to use `pip` to install - please follow additional discussion there about getting arm64 binaries.
