### ISSUE TITLE
Extra RAM Needed 

### ISSUE THREAD

**Issue by CarolineConcatto** [WorksOnArm/cluster#216]
We would like to increase one of our node capacity both by RAM and CPU if possible.
 
We have an historical monitoring data that server is being overloaded and RAM is not sufficient.
 
Initially, we would like to increase our “Jenkins Master, dff43c77.packethost.net” server RAM
                ; RAM from 32 to 128
 
However, we would continue to monitor system load on server again after increased RAM and then decide on what to increase the CPU.

**Comment by vielmetti** [comment]
The full ID of this server is dff43c77-8020-4d6b-861f-07adf158ff76 for reference, on the "Sponsored - Arm - LLVM" project. The best replacement for this looks like a standard c2.large.arm system in EWR1.

This system is a Jenkins master - is it set up to have a public page to display results or for monitoring?

**Comment by CarolineConcatto** [comment]
I know that Jenkins display public results of the compiler builds.
I also use the monitoring internally.
This machine is also used as a slave in lab.llvm.

**Comment by kushalkoolwal** [comment]
Looks like the migration effort has been completed. Closing this ticket. We have an internal ticket open at Packet to shutdown the system.
