### ISSUE TITLE
FastNetMon on ARM

### ISSUE THREAD

**Issue by pavel-odintsov** [WorksOnArm/cluster#22]
### Name, email, company, job title

Pavel Odintsov, pavel.odintsov@gmail.com, Project Lead

### Project Title and description

FastNetMon, cross-platform DDoS sensor

### Which members of the community would benefit from your work?

Users and other developers interested in ARM development and whole Debian community as our project recently was added into Debian: https://packages.debian.org/sid/fastnetmon 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, it's 100% open source and license under GPLv2 terms: https://github.com/pavel-odintsov/fastnetmon 

But we also have a commercial edition which uses a completely different branch of code. We do not overlap them and do not share code.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Two interconnected using direct cable connection using private NICs TYPE 2A is enough for us. 

We need one machine for packet generation and another one for sensor (FastNetMon itself). It's important to have physical connection as we generate significant pps rate for load testing.

### Please state your contributions to the open source community and any other relevant initiatives

I'm an author of FastNetMon, I have strong background in C++, Go. I implemented from scratch sFlow, Netflow, BGP and BGP flow spec/RFC5575 protocols.

I'm passionate about open source and Internet plumbing! :)

**Comment by vielmetti** [comment]
Approved, project created. We're going to review the network requirements for this and do whatever additional cabling would be necessary to take on the right tests.

**Comment by vielmetti** [comment]
Machines have been provisioned, so I'm going to close this as not needing more work on the cluster side for now.

**Comment by vielmetti** [comment]
We are aware of an issue that's affecting reprovisioning of the servers to use Ubuntu 18.04.

**Comment by vielmetti** [comment]
Ubuntu issue resolved. We are now working on support for a 4.17 kernel.

**Comment by vielmetti** [comment]
4.17 kernel for Ubuntu identified here

http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.17/

**Comment by vielmetti** [comment]
Success! Kernel built per above instructions.
