### ISSUE TITLE
Cloud hypervisor CI more bare-mental Arm instances are required

### ISSUE THREAD

**Issue by justin-he** [WorksOnArm/cluster#221]
Kind attention:  @michael2012z @rbradford @MrXinWang
Even after https://github.com/WorksOnArm/cluster/issues/205, more baremental Arm instances are required since community
complained about only 1 instance is too slow for processing the Arm CI testing.
Could I apply for another 1 instance at least? Thanks for the help :)

Name, email, company, job title
Michael Zhao, Michael.Zhao@arm.com, Arm, Staff software engineer
Henry Wang, Henry.Wang@arm.com, Arm, Graduate software engineer
Justin he, Justin.He@arm.com, Arm software engineer

Project Title and description
Cloud-Hypervisor

Cloud-Hypervisor is an open source Virtual Machine Monitor (VMM) that runs on top of KVM. The project focuses on exclusively running modern, cloud workloads, on top of a limited set of hardware architectures and platforms. Cloud Hypervisor is implemented in Rust and is based on the rust-vmm crates.

The cloud-hypervisor community is accepting PRs to enable AArch64. Currently we are using a github action to cross-build AArch64 code on x86_64 machine in order to make sure these AArch64 PRs can be built. As these PRs are gradually being merged, it is necessary to set up AArch64 CI in order to test everything on real AArch64 platform.

Which members of the community would benefit from your work?
Currently there are a number of contributions for this project, and together there is a need to have the fundamental integration test and unit test publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support, and thus appeal more cloud-hypervisor developers to utilize this project.

Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, https://github.com/cloud-hypervisor/cloud-hypervisor

What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
Require access to AArch64 based servers. Still in planning phase of how many, but starting off one should be sufficient.

Please state your contributions to the open source community and any other relevant initiatives
We are delivering patches to enable cloud-hypervisor on AArch64. See cloud-hypervisor #1168, #1223 #1232, #1238, #1293. Support to this project will be long-term.

Please let me know if you need more information.
Thanks!!

**Comment by justin-he** [comment]
cc @jongwu

**Comment by MrXinWang** [comment]
Thanks @justin-he.

/cc @sboeuf

**Comment by vielmetti** [comment]
@justin-he 

After discussion with @kushalkoolwal we will be providing a new server (Ampere Altra "Mt Snow") which should be more capable for your needs. I will update this issue when I have a definite timeline on installation.

**Comment by vielmetti** [comment]
The suggested new machine has more cores (80 vs 32) and faster cores (how much faster TBD, but for some tasks possibly 2x). 

If your CI infrastructure has a serial bottleneck, this will help measurably, but you'll probably get even more benefit from identifying parallelism in that system and taking advantage of it.

**Comment by sboeuf** [comment]
That sounds like a nice upgrade indeed :)
Let's cross our fingers this will reduce the time spent on each PR!

**Comment by vielmetti** [comment]
@sboeuf  - is there a dashboard or other report somewhere that shows progress of PR testing and/or times to complete? I'd be happy to see what kind of comparisons we can make over time.

**Comment by sboeuf** [comment]
@vielmetti here is the Jenkins instance keeping the runs: https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/
You can look into `master-periodic` to find out the average time spent.

**Comment by vielmetti** [comment]
An update!

We are looking at timing for the shipment and turnup of the new Ampere Altra servers. When I get a specific date for those I'll add that to this issue.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.

**Comment by vielmetti** [comment]
Noting a v0.14 release at https://www.phoronix.com/scan.php?page=news_item&px=Cloud-Hypervisor-0.14

**Comment by shipra-ps** [comment]
Hi Team,

An imp communication has been sent to you over email on 26th Jul'24. Request you to acknowledge the same.

**Comment by rbradford** [comment]
> Hi Team,
> 
> An imp communication has been sent to you over email on 26th Jul'24. Request you to acknowledge the same.

Please could you use my updated email (from my GitHub profile.)

**Comment by shipra-ps** [comment]
Done
