### ISSUE TITLE
Proposal - Build Armbian Linux Kernels and Images natively on Arm

### ISSUE THREAD

**Issue by lanefu** [WorksOnArm/cluster#223]
ARMDEVSUMMIT2020
### Contact Info

Igor Pecovnik -- igor dot pecovnik at gmail dot com -- Armbian Project Founder and Lead
Lane Jennison -- lane at lane-fu dot com -- Armbian Project Admin, Maintainer, and Evangelist

### Project Title and description

[Armbian](https://www.armbian.com) is a base operating system platform for single board computers (SBCs) that other projects can trust to build upon.

- Lightweight Debian or Ubuntu based Linux distribution specialized for ARM development boards
- Each system is compiled, assembled and optimized by [_Armbian Build Tools_](https://github.com/armbian/build)
- It has powerful build and software development tools to make [_custom builds_](Developer-Guide_Build-Preparation.md)
- A vibrant community

We focus on providing the best mainline-linux experience possible for Single Board Computers excluding Raspberry Pi.   This is achieved by:

-  working closely with SoC maintainers and developers to apply hardware enablement patches not yet fully upstreamed to mainline Linux and U-boot
- providing our own patches and device tree overlays
- providing off-the-shelf configurations optimized for specific SoCs and SBCs

### Which members of the community would benefit from your work?

- We already serve thousands of existing users by providing stable, current OS images for the owners of of low-cost SBCs where the vendor only provides unstable demo images based on unmaintained BSP kernels.
- We empower users in 3rd world markets to self-educate and deploy solutions using low-cost SBCs that would otherwise be unusable
- We empower small-scale engineer shops to bring boutique products to market because we have an OS to support their hardware.  ex: See the helios4 and helios64 NAS products by [Koblo.io](https://kobol.io)

### Is the code that you’re going to run 100% open source? 

yes

Provide the URLs where it is located, or a Git repository.

- https://github.com/armbian/build
- https://github.com/armbian/config

### What infrastructure (computing resources and network access) do you need?

We build dozens of different linux kernels and hundreds of linux image permutations.  We're looking for ways to build kernels faster and run image building within debboostrap faster

### Describe the continuous integration (CI) system in use or desired for this project.

As a linux distribution targeting over 100 bespoke SBCs, testing is hard.  See [this article](https://blog.ippon.tech/ci-test-unusual-projects-with-github-actions-and-self-hosted-runners/) describing some of our challenges.

Current Testing is the following
* basic CI building of targeted kernel via github actions and self-hosted runners https://github.com/armbian/ci-testing-tools
* a hardware test farm leveraging [these testing scripts](https://github.com/armbian/autotests)

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!

Armbian is the project I've been waiting for. I've been involved for a few years now..  I'm also a maintainer for some of the ansible roles for hashicorp tools.   (I love running nomad and consul on Armbian) [or nomad running arm VMs on armbian](https://twitter.com/lanefu/status/1254433300682244096)

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.
When you are done with the project, please let `info@worksonarm.com` know
so that we can reuse the hardware for someone else!

Sometimes projects change ownership or key people. Please let
`info@worksonarm.com` know promptly if we need to communicate with new folks.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter/ArmSoftwareDev)
* Discord, Arm Developer Ecosystem
* Arm Developer Commmunity, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

_i agree to above_

**Comment by kushalkoolwal** [comment]
Congrats on winning the ARMDEVSUMMIT2020 draw!

**Comment by lanefu** [comment]
wow! that's super exciting! 

@igorpecovnik exciting opportunities ahead!

**Comment by EvilOlaf** [comment]
This is awesome. Thank you so much for this opportunity!

**Comment by lanefu** [comment]
So what's timing on next steps?

**Comment by pgmwoa** [comment]
Please allow us few days to provision your hardware. You will be notified via email once the hardware is available.

**Comment by vielmetti** [comment]
Account setup has been done, you should see a set of welcome messages shortly @lanefu @EvilOlaf

**Comment by lanefu** [comment]
@vielmetti yep! my account is setup now.

**Comment by lanefu** [comment]
@pgmwoa Okay we have access to the account, and will wait for you to provision and confirm.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.

**Comment by vielmetti** [comment]
Looks like we're good to go @lanefu
