### ISSUE TITLE
Provide CI/CD resources for Linux Foundation's Project EVE

### ISSUE THREAD

**Issue by rvs** [WorksOnArm/cluster#225]
*Name, email, company, job title*

Roman Shaposhnik, rvs at apache dot org, Linux Foundation, N/A

*Project Title and description*

Linux Foundation Project EVE https://www.lfedge.org/projects/eve/

Project EVE aims to do for the IoT edge what Android did for mobile by creating an open edge computing engine that enables the development, orchestration and security of cloud-native and legacy applications on distributed edge compute nodes. Supporting containers and clusters (Dockers and Kubernetes), virtual machines and unikernels, Project EVE aims to provide a flexible foundation for IoT edge deployments with choice of any hardware, application and cloud. 

*Which members of the community would benefit from your work?*

Everyone running EVE on ARM. E.g. https://www.zdnet.com/article/xen-our-hypervisor-now-runs-on-raspberry-pi-4-but-pis-quirks-made-life-tricky/ and https://www.theregister.com/2020/09/29/xen_on_rpi_4/ to give two recent examples.

*Is the code that you’re going to run 100% open source?*

Yes (as any code under the governance of Linux Foundation)

*Provide the URLs where it is located, or a Git repository*

https://github.com/lf-edge/eve
https://github.com/lf-edge/adam
https://github.com/lf-edge/eden

*What infrastructure (computing resources and network access) do you need?*

24/7 build slaves for GitHub actions: 4-8Gb of RAM 2-4 cores, 3Gb of disk

*Describe the continuous integration (CI) system in use or desired for this project*

GitHub actions

*Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard*

Yes we would like to test every check in on arm64. Here's what we're currently doing on x86:
     https://github.com/lf-edge/eve/actions?query=workflow%3AEden

*Are you using a hosted CI system for some or all of your existing testing?*

Yes. We're using GitHub actions: https://github.com/lf-edge/eve/actions

*Please state your contributions to the open source community and any other relevant initiatives*

See the links to how we enabled Xen on RPi4 above. Other than that there's a lot of tech press coverage around Project EVE.

**Comment by vielmetti** [comment]
Thanks @rvs - we'll get this set up for you!

**Comment by rvs** [comment]
This is awesome news @vielmetti -- not to be a pest ;-) but any ETA?

**Comment by vielmetti** [comment]
Account is set up, hardware is reserved. You should get a note from @pgmwoa with the full welcome. Follow the docs at https://metal.equinix.com/developers/docs/deploy/reserved/ to deploy your reserved hardware.

**Comment by pgmwoa** [comment]
Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.

**Comment by vielmetti** [comment]
@rvs - at your convenience, please schedule a call with me at https://calendly.com/evielmetti to go over what your plans and goals are and how we can help achieve them!
