### ISSUE TITLE
Access to Arm servers for AOMedia Codec WG

### ISSUE THREAD

**Issue by andrey-norkin** [WorksOnArm/cluster#230]
### Name, email, company, job title

Andrey Norkin, anorkin@netflix.com, Netflix, AOMedia Codec WG co-chair
Adrian Grange, agrange@google.com, Google, AOMedia Codec WG co-chair

### Project Title and description

Donating Arm servers access to the AOMedia Codec Working Group. 

### Which members of the community would benefit from your work?

The Codec Working Group in the Alliance for Open Media would benefit from being able to evaluate the new video coding technologies on an Arm platform. 
The AOMedia membership list is available here: http://aomedia.org/membership/members/

### Is the code that you’re going to run 100% open source? 

The code is available to everyone, and has had a number of contribution from the member of open-source community. 
It can be accessed here: 
https://aomedia.googlesource.com/aom 

It is planned to move the new work to https://gitlab.com/AOMediaCodec in the future

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Not sure

### What infrastructure (computing resources and network access) do you need?

- Guaranteed 300 vCPU for 12 months of the project, with a check-in at 6-month mark 
- Depending on the project progress and Arm’s available capacity can ramp up to 600 vCPU for remaining 6 months
- A possible donation of older ThunderX servers 

### Describe the continuous integration (CI) system in use or desired for this project.

Gerrit with Jenkins are currently used. All patches are tested with unit tests, including tests on Arm platform.
https://build.aomedia.org/jenkins/

### Please state your contributions to the open source community and any other relevant initiatives.

Codec WG develops video coding specifications that are made available to the community on the royalty-free basis.  The Codec WG has previously developed the AV1 video codec specification: https://aomediacodec.github.io/av1-spec/av1-spec.pdf

In addition to that, the group has developed the reference software for the AV1 specification that includes a video encoder and video decoder in the libaom package: https://aomedia.googlesource.com/aom 

The AV1 video codec is supported by a number of internet browsers, mobile devices, TVs and is used to stream video. Please see the list of announcements here: 
http://aomedia.org/categories/#in-the-news

//----------------------

In addition, we would like to thank Arm for this generous offer!

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by vielmetti** [comment]
Two Mt Jade servers have now been assigned to the project.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.

**Comment by shipra-ps** [comment]
Hi Team,

I had been trying to reach over to you over email from my id: shipra.snehi@arm.com to review and understand the usage of our ARM servers. But looks like either my email is going to SPAM folder or the contact email id's have changed. I would request you to help us with your inputs asap.

**Comment by shipra-ps** [comment]
Hi Team,
Just trying to follow-up on my previous comment. Let us know if you are still using our ARM servers.

**Comment by shipra-ps** [comment]
Hi Team,

This is to inform you that since we haven't received any revert from you on the server usage ( even after multiple follow-ups) , we are proceeding with freeing the server from the project. 
In case you would still need the server, you may raise a new ticket on GitHub and share your requirements.
