### ISSUE TITLE
QEMU - Works On Arm Sponsored

### ISSUE THREAD

**Issue by stsquad** [WorksOnArm/cluster#231]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

### Name, email, company, job title

Alex Bennée
alex.bennee@linaro.org
Linaro
Senior Software Engineer

### Project Title and description

QEMU - Hardware Virtualisation VMM and emualtor

### Which members of the community would benefit from your work?

Broadly all of them as we will plumb into the CI system as well as use for ARM specific testing and development.

### Is the code that you’re going to run 100% open source? 

Yes
www.qemu.org
https://gitlab.com/qemu-project

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Yes

### What infrastructure (computing resources and network access) do you need?

This is migration from our existing WorksOnArm hardware to newer shinier machines

### Describe the continuous integration (CI) system in use or desired for this project.

GitLab
Aiming to test every merge request.
https://gitlab.com/qemu-project/qemu/-/pipelines

Are you using a hosted CI system for some or all of your existing testing? 

### Please state your contributions to the open source community and any other relevant initiatives.

I'm one of many maintainers - particularly with responsibility for the automation and testing.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by stsquad** [comment]
Gentle ping. Just checking nothing got lost.

**Comment by pgmwoa** [comment]
> Gentle ping. Just checking nothing got lost.

There is a slight delay in servers availability. We have your project in list for hw reservation and you should receive a notification as soon as it is done.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.

**Comment by pgmwoa** [comment]
@stsquad , Need your attention on email sent related to Mt Snow upgrade.

We would like to update you that there is a new production silicon available from Ampere that needs to be upgraded in the Mt Snow system reserved for your project.
 
_The new silicon will allow upgrade to the latest microcode, fixes for any security flaws and also occasional odd behaviors that you may have observed. This silicon upgrade will also help ensure that the latest microcode and firmware versions that Ampere supports can be installed on these systems to keep them up to date. We expect this upgrade to be agnostic to any software / applications you have been running._

**The upgrade is being planned by Equinix in the week of 21st March.** 
 
Important points to be noted:
•	The upgrade of the machine will take **one week** and during that time **you will not be able to access** or use those machines.
•	We will do our best to retain the storage state of each machine but we can’t guarantee that some or all systems won’t have data lost. We advise you to plan backup of project data before the planned upgrade date, as risk mitigation. 
 
We do understand that this may cause some inconvenience to you, we truly appreciate your cooperation. Please let us know in case you have any questions.
