### ISSUE TITLE
Eigen - Migrate to Ampere Altra Mt Snow - Works On Arm Sponsored

### ISSUE THREAD

**Issue by tellenbach** [WorksOnArm/cluster#232]
### Name, email, company, job title

Name: David Tellenbach
Email: david.tellenbach@me.com

### Project Title and description

Eigen is a C++ library for linear algebra and related algorithms that is widely used in a number of well-known projects, including Tensorflow.

### Which members of the community would benefit from your work?

Arm would benefit since Eigen is used as a core dependency in a number of projects.

### Is the code that you’re going to run 100% open source? 

Yes, 100% open source. URL of GitLab repository: https://gitlab.com/libeigen/eigen URL of project homepage: http://eigen.tuxfamily.org/index.php?title=Main_Page

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Yes, Eigen uses functionality available in ARMv8.2-a only.

### What infrastructure (computing resources and network access) do you need?

We would like to migrate our existing Ampere eMAG system that is also WorkOnArm sponsored to an Ampere Altra system with the following specs:

Mt Snow: 128GB (8x 16GB), 1TB SSD U.2, 1x 25GbE NIC

### Describe the continuous integration (CI) system in use or desired for this project.

We are using GitLab CI with docker executors.

### Please state your contributions to the open source community and any other relevant initiatives.

Maintainer of the Eigen project.

**Comment by tellenbach** [comment]
cc @kushalkoolwal

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by vielmetti** [comment]
Thanks @tellenbach -

The Armv8.2 instruction set looks like it would have very useful new bits for the core of what Eigen is doing. Do you have any anticipation what the new low precision instructions will do for performance?

**Comment by tellenbach** [comment]
> We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

Thanks @pgmwoa!



> Thanks @tellenbach -
> 
> The Armv8.2 instruction set looks like it would have very useful new bits for the core of what Eigen is doing. Do you have any anticipation what the new low precision instructions will do for performance?

@vielmetti unfortunately not yet. We now support ARMv8.2-a native half floats but haven't benchmarked them so far. I'll keep you updated!

**Comment by vielmetti** [comment]
The server has been assigned to the project.

@tellenbach please note that we have had some early issues, specifically around rebooting Ubuntu systems after a recent set of patches to the GRUB boot loader. Kindly review https://gist.github.com/vielmetti/dafb5128ef7535c218f6d963c5bc624e if you are planning to use Ubuntu on these machines, there are instructions there which I have tested. A full fix is underway.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.
