### ISSUE TITLE
Linaro - LLVM builder

### ISSUE THREAD

**Issue by maxim-kuvyrkov** [WorksOnArm/cluster#233]
### Name, email, company, job title

Name: Maxim Kuvyrkov
Email: maxim.kuvyrkov@linaro.org
Company: Linaro
Job title: Toolchain Tech Lead

### Project Title and description

LLVM Buildbots for AArch64 and AArch32

### Which members of the community would benefit from your work?

LLVM community relies on buildbot infrastructure (http://lab.llvm.org:8011/) for continuous integration and testing of llvm projects.

### Is the code that you’re going to run 100% open source? 

Yes, 100% open source: https://llvm.org/ , https://github.com/llvm/llvm-project

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

We don't require ARMv8.2, but will benefit if machines support ARMv8.2, since we will be able to test compiler support for ARMv8.2.

### What infrastructure (computing resources and network access) do you need?

1x Mt Jade for LLVM project.

### Describe the continuous integration (CI) system in use or desired for this project.

http://lab.llvm.org:8011/ .  LLVM uses buildbot CI and Linaro maintains ARM configurations for CI.

### Please state your contributions to the open source community and any other relevant initiatives.

My team is among top-10 contributors to both major open-source toolchains: GNU Toolchain and LLVM Toolchain.  I, personally, am a long-time open-source developer with contributions to GCC, LLVM, Binutils, Glibc, and GDB. My team at Linaro is the owner of AArch64 and AArch32 LLVM buildbots, which we are running on Packet.net hardware.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
