### ISSUE TITLE
GNU Toolchain - Works On Arm Sponsored

### ISSUE THREAD

**Issue by nsz-arm** [WorksOnArm/cluster#235]
### Name, email, company, job title

Szabolcs Nagy <szabolcs.nagy@arm.com>, Arm Ltd., Software engineer
Luis Machado <luis.machado@linaro.org>, Linaro Ltd., Software engineer
Vidya Praveen <vidyapraveen@arm.com>, Arm Ltd., Software engineer

### Project Title and description

GNU Toolchain - Continuous native testing on aarch64 and aarch32
of upstream GNU tools, mainly for the GDB and Glibc projects which
otherwise don't have public arm based CI.

### Which members of the community would benefit from your work?

GDB and Glibc developers who otherwise don't or can't regression
test their work on an aarch64 or aarch32 system. We likely have to
set up GCC builds too to test latest Glibc features and then we can
send GCC test results as well.

### Is the code that you’re going to run 100% open source?

Yes, sources of the tested projects can be found at

https://www.gnu.org/software/gdb/current/
https://www.gnu.org/software/libc/sources.html
https://gcc.gnu.org/git.html

and we will run open source build infrastructure
(buildbot, qemu, linux, docker, etc).

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

No.

### What infrastructure (computing resources and network access) do you need?

I think our baseline requirement is 32 cores and 64GB memory and 200GB storage
but we can make good use of more resources up to about 200 cores, 400GB memory and 1TB storage.
(we will run more configurations and get results faster if we have more resources)

Our CI clients sync source repositories and transmit logs to a CI server.
With a small setup I'd expect less than 1GB traffic per day, with a large
setup I'd expect less than 10GB traffic per day.

I don't think we need regular support if we get ssh and root access
(needed for installing packages and managing services like docker or qemu-kvm).

### Describe the continuous integration (CI) system in use or desired for this project.

We would set up glibc buildbot clients: https://sourceware.org/glibc/wiki/Buildbot
and gdb buildbot clients: https://sourceware.org/gdb/wiki/BuildBot

The buildbot servers are managed by the community, normally it triggers a test run
on every commit or when the previous test finished in case commits are more frequent.

### Please state your contributions to the open source community and any other relevant initiatives.

Szabolcs Nagy is a Glibc aarch64 port maintainer.
Luis Machado is a GDB aarch64 port maintainer.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by vielmetti** [comment]
@pgmwoa Manisha there is a previous project #98 from @u99127 which has the same description ("Arm GNU Toolchain").

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
