### ISSUE TITLE
KVM/arm64 - Works On Arm Sponsored

### ISSUE THREAD

**Issue by mzyngier** [WorksOnArm/cluster#236]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title

Marc Zyngier <maz@kernel.org>, Google, Software Engineer
Christoffer Dall <christoffer.dall@arm.com>, ARM, Principal Engineer

### Project Title and description

KVM/arm64

### Which members of the community would benefit from your work?

KVM/arm64 is the most deployed production arm64 hypervisor. Most users of the ARMv8 architecture directly benefit from it, among which Google, AWS, and many others.

### Is the code that you’re going to run 100% open source? 

Yes.

Provide the URLs where it is located, or a Git repository.

https://git.kernel.org/pub/scm/linux/kernel/git/kvmarm/kvmarm.git/

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Yes. We can also benefit from later (and earlier) version of the architecture.

### What infrastructure (computing resources and network access) do you need?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

This is a *very* long running project. Both Christoffer and Marc have been maintaining this project for the past 9 years, and will continue doing so for the foreseeable future,  We are not interested in short-term support. We are already supported by ARM/Equinix under the "Columbia KVM/arm" banner.

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

Everything is CI-ed via the various Kernel-CI projects.

Are you using a hosted CI system for some or all of your existing testing? 

No.

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!

Marc is the Linux kernel maintainer for both KVM/arm64 and part of the Linux interrupt subsystem, including the ARM GIC architecture.

Christoffer used to co-maintain KVM/arm64 and works future evolution of the ARM architecture

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
