### ISSUE TITLE
Linaro - Works On Arm Sponsored

### ISSUE THREAD

**Issue by fozog** [WorksOnArm/cluster#237]
### Name, email, company, job title
Ozog, francois.ozog@linaro.org, Linaro, Director edge and fog computing group
Holmes, mike.holmes@linaro.org, Linaro, Director foundational technologies
Bech, Joakim.bech@linaro.org, Linaro, Distinguished Engineer

### Project Title and description
Title: Mixed critical virtual environments
Description: integrate and build all necessary technologies to implement Confidential Computing / Mixed ownership.
It will impact diverse firmware, hypervisor, Linux and toolchain projects.

### Which members of the community would benefit from your work?
All Linaro members and beyond (Microsoft...)

### Is the code that you’re going to run 100% open source? 
Yes; that said, it is expected ecosystem will have proprietary solutions. For instance we expect to define the required interfaces to allow  building safety compatible virtualization solutions while we will not seek safety certification in the open source. Examples for that are VMM in the trust zone. We expect to work on solutions with dedicated cores per task or task groups in the non-secure world or in the secure world.
 
Provide the URLs where it is located, or a Git repository.
Many upstream projects are impacted:
https://github.com/ARM-software/arm-trusted-firmware
https://github.com/OP-TEE/optee_os
https://github.com/tianocore/edk2
https://github.com/u-boot/u-boot
https://github.com/ARM-software/SCP-firmware
https://github.com/xen-project/xen
https://git.kernel.org
https://github.com/zephyrproject-rtos/zephyr
https://github.com/openenclave/openenclave
https://gitlab.freedesktop.org/gstreamer
https://github.com/ros2
https://github.com/gcc-mirror/gcc
https://github.com/llvm

### Does this project require ARMv8.2 (Yes/No/Not Sure)?
Yes. Work on OP-TEE RAS mitigation features: https://trustedfirmware-a.readthedocs.io/en/latest/components/exception-handling.html?highlight=Exception%20Handling%20Framework 

### What infrastructure (computing resources and network access) do you need?
Mount snow

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.
Yes: https://ci.linaro.org

Are you using a hosted CI system for some or all of your existing testing? 
A mixture. Linaro is the original author and maintainer of LAVA

### Please state your contributions to the open source community and any other relevant initiatives.

Regular top 5 contributor in the Linux kernel.
Linaro is going to resume releasing GCC and LLVM interim integrations in tandem with Arm who will provide “master” releases of the toolchain
http://patches.linaro.org 
https://www.codelinaro.org/about
https://www.96boards.org

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
