### ISSUE TITLE
SONIC ARM switch enablement - Works On Arm Sponsored

### ISSUE THREAD

**Issue by kielfriedt** [WorksOnArm/cluster#239]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title

Kiel Friedt kiel.friedt@arm.com ARM Support engineer

### Project Title and description

SONIC ARM switch enablement

Creating CI/CD pipeline for SONIC NOS under AZURE. Porting N1SDP to ONIE and then onto SONIC. AZURE has requested CI/CD for building components and services under SONIC. Currently a small group of items are built under QEMU. This takes days to complete and I would like to accelerate this.

### Which members of the community would benefit from your work?

SONIC is a popular NOS, providing CI/CD on ARM would allow quick deployment on new and existing ARM switching equipment. Thus leading to a increase in adoption.

### Is the code that you’re going to run 100% open source? 
Yes

Provide the URLs where it is located, or a Git repository.

https://github.com/Azure/SONiC
https://github.com/Azure/sonic-buildimage

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

No

### What infrastructure (computing resources and network access) do you need?

I do not know the computing resources and network access requirements as of yet. The current items built under QEMU is small but enable this compute resource could cause many more builds to be performed. x86 builds and pr build are done multiple times daily. I would expect a slow but steady ramp up once building is enabled.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

I would expect this to be a long term effort since ARM switch equipment is a small but growing market.

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

Are you using a hosted CI system for some or all of your existing testing? 

Azure pipeline is used for SONIC building. Agents would be ran on the ARM equipment. This will be used to build new and existing components of SONIC. All PRs would need to be built on ARM64. As of now these checks do not exist. I would expect them to be enabled once hardware is available.

No, CI agents would respond to the Azure pipeline. 

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!

Kiel is a principle support engineer focused on Cloud/5G/network enablement. In the past working as a windows kernel developer and has experience on many security projects within the telecom space. 

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
