### ISSUE TITLE
Swift on Arm - Migration to Altra - Works On Arm Sponsored

### ISSUE THREAD

**Issue by futurejones** [WorksOnArm/cluster#240]
Hi WoA Program Team,

I am confirming that the new server details as listed below are excellent and suitable for the Swift on Arm project.
The current server is located in Tokyo (NRT1). This location is not important and can be changed if necessary.
Please go forward with the migration.

Thanks,
Neil.

> Hello Neil,
> 
> I am happy to inform that the new Ampere systems would be ready soon for project migration.
> 
> Would like to propose one new Altra Mt Snow - 1P, 80 cores system for your project in replacement to the older machine.
> 
> Specs are - Mt Snow: 128GB (8x 16GB), 1TB SSD U.2, 1x 25GbE NIC
> 
> Kindly confirm. I will accordingly schedule your project migration and communicate to you the next steps.
> 
> P.S: We also have an Ampere’s Altra website https://amperecomputing.com/altra/  in case you would like to read more about the new systems.
> 
>  
> 
> Regards
> Manisha
>  
> WoA Program Team
>

**Comment by futurejones** [comment]
Notice to Manisha Nigam.
This is an ongoing existing approved project.
Details on the project are here https://github.com/WorksOnArm/cluster/issues/62

**Comment by pgmwoa** [comment]
Please fill the details in the template for the ticket to be approved.

**Comment by futurejones** [comment]
_If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below._

_If you are just making a comment, ignore/delete those fields and file your issue._

_Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal._

### Neil Jones, neil@swift-arm.com

_Note that projects with two or more participants are preferred._

### Project - Porting Open Source Swift coding language to aarch64 machines.
The Swift coding language was developed by Apple and released as open source in 2015.  
https://swift.org/about/

In 2016  http://swift-arm.slack.com was set up to port Swift to the RaspberryPi and other armv6/v7 devices.
This was achieved for Swift version 3 and many people having been coding with swift on RasberryPi's since then.

We are now seeing a lot RasberryPi style SBC's with arm64/aarch64 cpu's, at the same time Swift is evolving and is now being used in many Server Side open source projects such as - 
- https://github.com/vapor/vapor
- https://github.com/Kitura/Kitura
- https://github.com/PerfectlySoft/Perfect
- https://github.com/apple/swift-nio

The goal of this project is to not only port Swift to aarch64, but also port any build tools required for building Swift and other related software.

All of this will be made available in apt-get install packages at - 
- https://packagecloud.io/swift-arm

### Which members of the community would benefit from your work?
Anybody who wants to use the Swift coding language on an aarch64 machine.

### Is the code that you’re going to run 100% open source? 
_Provide the URLs where it is located, or a Git repository._
Yes - https://github.com/apple/swift

### Does this project require ARMv8.2 (Yes/No/Not Sure)?
Yes
### What infrastructure (computing resources and network access) do you need?
Altra Mt Snow - 1P, 80 cores 128GB (8x 16GB), 1TB SSD U.2, 1x 25GbE NIC
A request for continuous ongoing support. 

### Describe the continuous integration (CI) system in use or desired for this project.
Swift Community Hosted CI. Jenkins based. https://ci-external.swift.org/
AArch64 Nodes:
https://ci-external.swift.org/job/oss-swift-RA-ubuntu-20.04-aarch64
https://ci-external.swift.org/job/oss-swift-RA-ubuntu-18.04-aarch64
https://ci-external.swift.org/job/oss-swift-RA-centos8-aarch64
https://ci-external.swift.org/job/oss-swift-RA-amazon-linux-2-aarch64

_Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard._
At this point we are doing nightly builds but would like to add another node for PR testing.

_Are you using a hosted CI system for some or all of your existing testing?_ 
I am also running a personal Jenkins server for building and testing various Swift packages and versions as well as other Swift related projects.
http://futurejones.xyz:8080/

### Please state your contributions to the open source community and any other relevant initiatives.

I am an active contributor to the Swift open source project, a member of swift-arm slack team, and a number of other open source projects.
I also setup and maintain 
https://packagecloud.io/swift-arm
https://swift-arm.com/
https://github.com/futurejones/swift-arm64

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)


@pgmwoa I have added the Template details.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers

**Comment by futurejones** [comment]
Thank you

**Comment by pgmwoa** [comment]
@futurejones, Need your attention on the email sent related to Mt snow upgrade.

We would like to update you that there is a new production silicon available from Ampere that needs to be upgraded in the Mt Snow system reserved for your project.
 
_The new silicon will allow upgrade to the latest microcode, fixes for any security flaws and also occasional odd behaviors that you may have observed. This silicon upgrade will also help ensure that the latest microcode and firmware versions that Ampere supports can be installed on these systems to keep them up to date. We expect this upgrade to be agnostic to any software / applications you have been running._

**The upgrade is being planned by Equinix in the week of 21st March**. 
 
Important points to be noted:
•	The upgrade of the machine will take **one week** and during that time **you will not be able to access or use those machines.**
•	We will do our best to retain the storage state of each machine but we can’t guarantee that some or all systems won’t have data lost. We advise you to plan backup of project data before the planned upgrade date, as risk mitigation. 

We do understand that this may cause some inconvenience to you, we truly appreciate your cooperation. Please let us know in case you have any questions.

**Comment by shipra-ps** [comment]
Hi Neil,

Somehow I am unable to reach out to you over email on neil@swift-arm.com . We have some important communication for you which needs to be done over email.
Can you pls drop a mail from your end to Shipra.Snehi@arm.com , so that we can provide you the update over there?

Regards,
Shipra Snehi
WoA Program Team
