### ISSUE TITLE
Node.js - Works On Arm Sponsored (migration to Altra servers)

### ISSUE THREAD

**Issue by rvagg** [WorksOnArm/cluster#241]
We've been instructed to open an issue here to begin migration of our CI infrastructure to the new Altra servers that have been reserved for us. Please let me know if there's anything else you need from us, otherwise we'll wait to hear back on progress and next steps.

/cc @mhdawson

**Comment by pgmwoa** [comment]
Please fill the details in the template for the ticket to be approved.

**Comment by pgmwoa** [comment]
Closing this ticket as a new one #251 has been opened
