### ISSUE TITLE
Linaro - Jenkins CI - Migration to Altra Mt Snow - Works On Arm Sponsored

### ISSUE THREAD

**Issue by fboudra** [WorksOnArm/cluster#242]
### Project Title and description

Linaro CI build slaves - general purpose

Linaro is a collaborative engineering organization consolidating and optimizing open source software and tools for the Arm architecture. Linaro engineering works with upstream (and downstream) projects on a set of requirements that are determined by the Technical Steering Committee (TSC).

At Linaro, the System Technologies group provides infrastructure and software solutions to Linaro engineering in order to support their efforts into improving the open source eco system on Arm.
We provide a Jenkins instance (https://ci.linaro.org/)

Note: while this request may seem redundant with some of my Linaro's colleagues, it isn't. Our team provide general purpose continuous integration services for various project. Other teams at Linaro may work on specific topics like the toolchain and have separate requirements.

### Which members of the community would benefit from your work?

Linaro is contributing to various open source projects. To name a few: the Linux Kernel, the GNU Compiler Collection (GCC), Zephyr, AOSP, UEFI, OP-TEE, OpenEmbedded, Debian and many others.

### Is the code that you’re going to run 100% open source? 

Yes, the code is 100% open source.

In addition to the upstream projects repositories that we're using, our repositories can be found on:
* https://git.linaro.org/
* https://github.com/linaro
* https://github.com/96boards

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Not sure, due to the various projects running on the continous integration provided, pipelines will vary over time and may require ARMv8.2.

### What infrastructure (computing resources and network access) do you need?

It's the migration for an existing and approved WorksOnArm project (https://github.com/WorksOnArm/cluster/issues/77). The project will need 1 x Altra Mt Snow.

### Describe the continuous integration (CI) system in use or desired for this project.

We're running a Jenkins master at https://ci.linaro.org/ . The hardware will be used as a node on this instance.
We do CI on commit, on merge/pull requests, and scheduled (nightly/daily) basis.

We do host CI systems, including Jenkins/Gitlab/LAVA.

### Please state your contributions to the open source community and any other relevant initiatives.

My personal contributions to the open source community goes from Debian, Qt, KDE, OpenEmbedded to the Linux Kernel (and many other open source projects). I've been a long time open source contributor and an open source advocate. As for the company I work for, Linaro is regularly in the top 10 contributors to the Linux kernel, next to companies 10+ times its size :)
In addition to my personal contributions, Linaro is a well known contributors to Open Source and Arm ecosystem. The various working groups are recognize as expert in their domains.

We can see also see our upstreaming contributions on http://patches.linaro.org/

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
