### ISSUE TITLE
Alpine Linux - Works On Arm Sponsored

### ISSUE THREAD

**Issue by clandmeter** [WorksOnArm/cluster#243]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title

Carlo Landmeter, Alpine Linux, Infra manager
Natanael Copa, Alpine Linux, Founder

Note that projects with two or more participants are preferred.

### Project Title and description
Alpine Linux, Linux Distro

### Which members of the community would benefit from your work?

Anyone who like a small secure linux distribution, and of course docker users.

### Is the code that you’re going to run 100% open source? 

Yes

Provide the URLs where it is located, or a Git repository.

gitlab.alpinelinux.org

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Not sure

### What infrastructure (computing resources and network access) do you need?

Builders to build our packages for all our ARM architectures (we build native)
CI for all our ARM architectures

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Long term

### Describe the continuous integration (CI) system in use or desired for this project.

We use self hosted Gitlab

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

gitlab.alpinelinux.org

Are you using a hosted CI system for some or all of your existing testing? 

We use our own CI

### Please state your contributions to the open source community and any other relevant initiatives.

I think it's kind of obvious, check docker examples.

Brag a little bit about yourself, please!

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers
