### ISSUE TITLE
Eclipse Adoptium - Works On Arm Sponsored

### ISSUE THREAD

**Issue by sxa** [WorksOnArm/cluster#245]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title

Stewart Addison sxa@adoptopenjdk.net

### Project Title and description

Eclipse Adoptium (formerly adoptopenjdk)

### Which members of the community would benefit from your work?

All java users ;-)

### Is the code that you’re going to run 100% open source? 

Yes

Provide the URLs where it is located, or a Git repository.

github.com/adoptopenjdk

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

If possibly, yes

### What infrastructure (computing resources and network access) do you need?

As discussed with Manisha we are looking to move our existing systems to the new Mt.Jade servers and I believe three have already been reserved for us for this purpose - I was asked to create this issue to track the access to the new systems.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Continuous, but we haven't had to bother you too much with requests since we first worked with you

### Describe the continuous integration (CI) system in use or desired for this project.

Jenkins.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

ci.adoptopenjdk.net - we build nightly rather than on each PR

Are you using a hosted CI system for some or all of your existing testing? 

Yes - same server

### Please state your contributions to the open source community and any other relevant initiatives.

Personally I'm on the AdoptOpenJDK steering committee and manage the infrastructure and most of the build process for the project which builds openjdk code from the main openjdk codebase, OpenJ9, Bisheng (Huawei) and Dragonwell (Alibaba) - all of which support aarch64.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
