### ISSUE TITLE
Julia - Works On Arm Sponsored

### ISSUE THREAD

**Issue by ViralBShah** [WorksOnArm/cluster#247]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title
Viral Shah, viral@mayin.org, Julia Project, co-creator

Note that projects with two or more participants are preferred.

### Project Title and description
Julia language

### Which members of the community would benefit from your work?
We support the Aarch64 and armv7 targets, used by tens of thousands of users

### Is the code that you’re going to run 100% open source? 
yes

Provide the URLs where it is located, or a Git repository.
https://github.com/julialang/julia

### Does this project require ARMv8.2 (Yes/No/Not Sure)?
Not Sure

### What infrastructure (computing resources and network access) do you need?
We like having access to a 64-bit Aarch64 box and 32-bit ARMv7 box for running CI and build bots, and one Aarch64 box for interactive development and debugging.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.
Yes, we like to: https://build.julialang.org/#/workers

Are you using a hosted CI system for some or all of your existing testing? 
We are running our own

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!
Julia project: https://julialang.org/ 

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by ViralBShah** [comment]
cc @staticfloat

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by ViralBShah** [comment]
Hi - Just checking in if a server is available for us to get started?

**Comment by pgmwoa** [comment]
> Hi - Just checking in if a server is available for us to get started?

We are in the process of getting them ready, probably sometime next week. Your project is in queue for reservation.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers.

**Comment by Keno** [comment]
We had this machine briefly, but never managed to actually set it up and in the meantime had gotten CI elsewhere, so this machine was reclaimed. Said other CI is now running out, so we'd like to make use of this machine if possible. As suggested via email, requesting this reinstatement here.

**Comment by pgmwoa** [comment]
@Keno @ViralBShah 

There is a change in the GitHub ticket template for capturing Project details since the last time you had requested servers.

Request you to submit a new ticket to re-confirm / share latest project details, so that we have all the relevant information for allocating the correct infrastructure.
Please specify the names and email-ids of all the users who would need access to the machines.

Thank you for understanding.
