### ISSUE TITLE
 LLVM and Flang - Works On Arm Sponsored 

### ISSUE THREAD

**Issue by leandron** [WorksOnArm/cluster#248]
This proposal covers two projects that share same infra, under an existing project called "Sponsore LLVM". This ticket is a request for migration of existing AArch64 systems to new Altra machines.

### Name, email, company, job title
Fatih Onur, fatih.onur at arm.com, Arm, DevOps Engineer
Gary Caroll, gary.carol at arm.com, Am, DevOps Engineer
Leandro Nunes: leandro.nunes at arm.com, Arm, Compiler Eng

### Project Title and description

Flang is the LLVM project’s Fortran frontend - see https://github.com/llvm/llvm-project/tree/master/flang. It began life as an out of tree project called F18, with the intention being that it would be contributed to LLVM as Flang.

LLVM CI aims to build AArch64 LLVM debian packages for distribution.

### Which members of the community would benefit from your work?
Users interested in AArch64 builds of LLVM, and developers interested in CI jobs to test their work.

### Is the code that you’re going to run 100% open source? 
Yes, at https://github.com/llvm/llvm-project/tree/master

### Does this project require ARMv8.2 (Yes/No/Not Sure)?
Not sure.

### What infrastructure (computing resources and network access) do you need?
It is a migration of our existing infrastructure to Altra systems.

### Describe the continuous integration (CI) system in use or desired for this project.

http://lab.llvm.org:8011/
https://llvm-jenkins.debian.net/

### Please state your contributions to the open source community and any other relevant initiatives.

We maintain and work on many CI jobs for various LLVM-related components.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.

We had reserved 2 Mt Snows  in March'21 and now with the recent allocation of 2 Mt Snows, your project allocation has been completed. Hence closing the ticket.
