### ISSUE TITLE
Xen Project - Works On Arm Sponsored

### ISSUE THREAD

**Issue by sstabellini** [WorksOnArm/cluster#249]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Participants
Stefano Stabellini, sstabellini@kernel.org, Xilinx, Xen Maintainer
Julien Grall, julien@xen.org, Amazon, Xen Maintainer
Andrew Cooper, andrew.cooper3@citrix.com, Citrix, Xen Maintainer

### Project: Xen Project
Linux Foundation Open Source Collaborative project to development the Xen hypervisor.

### Which members of the community would benefit from your work?
All members: we intend to use the server to run the gitlab-ci loops. It is used to build and test all code contributions to the project.

### Is the code that you’re going to run 100% open source? 
Yes

> Provide the URLs where it is located, or a Git repository.

The official URL is: http://xenbits.xenproject.org/git-http/xen.git

### Does this project require ARMv8.2 (Yes/No/Not Sure)?
No

### What infrastructure (computing resources and network access) do you need?

We need network access to the internet to be able to run a gitlab-ci runner. We need enough computing resources to run the Xen Project CI-loop tests. See the following for reference:

https://gitlab.com/xen-project/xen/-/pipelines/274469996

We haven't needed support so far. We could manage the gitlab-ci runner configuration on our own.

### Describe the continuous integration (CI) system in use or desired for this project.

> Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

Yes we test every commit as well as not-yet-committed patch series from contributors.

> Are you using a hosted CI system for some or all of your existing testing? 

We are using gitlab-ci.

### Please state your contributions to the open source community and any other relevant initiatives.
> Brag a little bit about yourself, please!

I (Stefano Stabellini) have been involved in Xen development since 2007. I created libxenlight in November 2009 and started the Xen port to ARM with virtualization extensions in 2011. I am a Xen Project committer and maintainer. In the last couple of years at Xilinx I developed dom0less, which lowers the boot time of Xen-based systems by 90%+.

## Important reminders and logistics

> Approved projects will be expected to provide credit back to Works on Arm
> in the form of a logo display, blog post, Twitter post, news release, or
> some other suitable acknowledgement.

We are certainaly happy to do that and thank you for your support!

> Approved projects are subject to a 90 day review process for termination.
>
> When resources are not required anymore or when the project ends, please add comments on this issue so that we can  reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers.
