### ISSUE TITLE
Nextcloud: WoA request

### ISSUE THREAD

**Issue by mathiasconradt** [WorksOnArm/cluster#25]
Hi Jacob,

thanks for reaching out.

Since we want to compare ARM and Intel and with a similar pricing, I guess the two specs by Ed would be the ones to go with, as they have the same pricing.

https://www.packet.net/bare-metal/servers/type-2a/ - "Type 2A" w/96 Arm cores, 128G of memory, list price $0.50/hr

https://www.packet.net/bare-metal/servers/type-1e/ - "Type 1E" w/8 threads on 4 Intel E3-1578L cores, 32G memory, list $0.50/hr

I’d need two machines with preferably Ubuntu (or Redhat, but Ubuntu preferred) installed, where I can setup the LAMP stack (and then Nextcloud) and run load tests.

In case you need my public key for ssh, please find it attached.

(Not sure what a github request should contain, I guess we don’t want to put this info publicly on github. Hope this info is sufficient. Otherwise please let me know).

Thanks & Best regards,

Mathias

**Comment by mathiasconradt** [comment]
[id_rsa.pub.txt](https://github.com/WorksOnArm/cluster/files/1502882/id_rsa.pub.txt)

**Comment by vielmetti** [comment]
Blog post published:

https://nextcloud.com/blog/running-nextcloud-arm-server-can-provide-40-performance-per-dollar-uplift/

**Comment by vielmetti** [comment]
Posted to Works on Arm newsletter as lead story in https://www.worksonarm.com/blog/woa-issue-59/

**Comment by vielmetti** [comment]
I think this issue is complete @mathiasconradt - there will of course be opportunities for more collaboration, but I think we have this all sorted out. Let me know if we're OK to close.
