### ISSUE TITLE
Sled - Works On Arm Sponsored

### ISSUE THREAD

**Issue by spacejam** [WorksOnArm/cluster#250]
The Sled project, an embedded database leaning heavily into lock-free concurrency and targeting a variety of Arm architectures, is an existing tenant in the Works on Arm system, and has been asked to migrate to the next generation of Arm servers, off of the previous ThunderX setup.

Manisha Nigam has proposed the use of one Altra Mt Snow - 1P, 80 core system.

This migration may occur at any time, and there is no sensitive material on the previous ThunderX system that needs to be preserved. Feel free to blow away the old system as it is convenient for you to do so.

Thank you for your assistance in setting up the new system :)

**Comment by pgmwoa** [comment]
As communicated via email (8 June), server has been powered down. Closing the ticket.
