### ISSUE TITLE
Node.js - Works On Arm Sponsored

### ISSUE THREAD

**Issue by mhdawson** [WorksOnArm/cluster#251]
### Name, email, company, job title

Michael Dawson, midawson@redhat.com, Chair of the Node.js Technical steering comittee

### Project Title and description

Node.js - builds Node.js - https://github.com/nodejs/node

### Which members of the community would benefit from your work?

Anybody who wants to run Node.js on the ARM architecture

### Is the code that you’re going to run 100% open source? 

Yes

Provide the URLs where it is located, or a Git repository.

- https://github.com/nodejs/node

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Noe sure

### What infrastructure (computing resources and network access) do you need?

Long term, ongoing. 

### Describe the continuous integration (CI) system in use or desired for this project.

We use Jenkins and run testing on every check-in on arm64 already based on existing
support from works on Arm - https://ci.nodejs.org/job/node-test-commit-arm/

### Please state your contributions to the open source community and any other relevant initiatives.

Bio, but not really relevant because this request is on behalf of the Node.js project as a continuation of resources that are already being provided: https://github.com/mhdawson/resume/blob/main/mdawson-bio.md

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Already in place -> see https://github.com/nodejs/build
Monthly tweets also go out thanking our infrastructure donators.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use

**Comment by pgmwoa** [comment]
We are still waiting for more Mt. Jade inventory to become available at Equinix. Will update you as soon as we have a time frame.

**Comment by mhdawson** [comment]
Thanks for the update.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers
