### ISSUE TITLE
GCC compile farm - Works On Arm Sponsored

### ISSUE THREAD

**Issue by jonglezb** [WorksOnArm/cluster#252]
### Name, email, company, job title

Baptiste Jonglez, gccfarm@bitsofnetworks.org, GCC compile farm, volunteer / admin

### Project Title and description

The GCC compile farm started as a way to test GCC on many different architectures and systems (x86, ARM, Power, Sparc, Mips, Linux, BSD, AIX...). Over the years, interest has grown from many free software projects in addition to GCC, and there are now more than 800 users (= open source developers on various projects) that rely on the farm to test/debug their project on exotic hardware.

It's a community project run 100% by volunteers, and several organizations already donate hardware and hosting.

Website: https://gcc.gnu.org/wiki/CompileFarm and https://cfarm.tetaneutral.net/

### Which members of the community would benefit from your work?

To name a few (we have 800+ users from many projects): GCC, LLVM, sudo, glibc, musl, openjdk, ffmpeg, mercurial, mbedtls, wine, cryptopp, Rust, Python, OpenBlas, Prolog, Qemu...

### Is the code that you’re going to run 100% open source? 

Yes, this is the main requirement to apply for an account on the farm, see https://cfarm.tetaneutral.net/users/new/ (and we actively enforce this rule). All users are required to use the farm only for open source development / testing / debugging.

Our management system is also open-source if that matters: https://framagit.org/compile-farm/gccfarm

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Yes, that would be nice but not a hard requirement (we are looking to have different ARM variants in the farm, including newer ones).

### What infrastructure (computing resources and network access) do you need?

- bare metal is required, we then manage the software ourselves (OS, users, packages)
- we are looking for interesting/recent hardware variants to widen the scope of the farm, with ideally one machine of each CPU type (e.g. 1x ThunderX2, 1x ThunderX3, 1x Altra, etc, depending on what you have)
- relatively "small" machines are fine: e.g. 16 cores and 64 GB of RAM (but more is welcome). Access to the actual "exotic" hardware is more important than performance.
- at least 2 TB of HDD storage per machine, more is welcome.
- we need inbound SSH access only, preferably with a public IPv4/IPv6 address (to use the standard SSH port whenever possible)
- outbound traffic should not be filtered (we need git, http, ftp, rsync, buildbot, etc)
- network traffic is low on average (a few Mbit/s downstream at most) but can be bursty

### Describe the continuous integration (CI) system in use or desired for this project.

Users are using whatever system works for them: cron jobs, buildbot workers, other CI systems, building / debugging things manually...

### Please state your contributions to the open source community and any other relevant initiatives.

The project has been helping open source developers since 2005: https://gcc.gnu.org/wiki/CompileFarm#History_and_Sponsors

Projects find it useful to check that they don't introduce regressions on uncommon / exotic systems, or to add specific features that depend on the hardware.

Also, whenever somebody reports a bug like "your project fails to build/run on this exotic architecture / OS", people are often quick to point to the compile farm for help :-)

Here are some examples where the farm has helped or has been mentioned:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53943#c4
https://github.com/openssl/openssl/commit/bee9c8a4ffd3ec65bb56aaa04423c4f6f9c4012c
https://github.com/zlib-ng/zlib-ng/pull/224#issuecomment-439526170
https://github.com/rust-lang/rust/issues/53181
https://github.com/rust-lang/rust/issues/49773#issuecomment-423780872
https://github.com/rust-lang/rust-bindgen/issues/1746#issuecomment-598159082
https://github.com/borgbackup/borg/issues/4875
https://github.com/numpy/numpy/pull/15074#discussion_r357405492
https://github.com/weidai11/cryptopp/commit/b4a041a71b68286912f484644d55f887c3774a38
https://github.com/OpenSmalltalk/opensmalltalk-vm/issues/493#issuecomment-620804934

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Thanks for your interest in Works On Arm program. We are reviewing your request and will get back soon.

**Comment by pgmwoa** [comment]
Closing the ticket after email discussion with project.
