### ISSUE TITLE
OpenEmbedded - Works On Arm Sponsored

### ISSUE THREAD

**Issue by jonmason** [WorksOnArm/cluster#253]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title

Jon Mason, jon.mason@arm.com, Arm, Principal Yocto Developer

### Project Title and description

OpenEmbedded
OpenEmbedded offers a best-in-class cross-compile environment. It allows developers to create a complete Linux Distribution for embedded systems.
https://www.openembedded.org/wiki/Main_Page

### Which members of the community would benefit from your work?

All members of OpenEmbedded/Yocto would benefit from builds and CI run on Arm hardware

### Is the code that you’re going to run 100% open source? 

Yes.  See http://layers.openembedded.org/layerindex/branch/master/layers/

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

Since we are building things and running virtualized CI via qemu, nothing 8.2 needed

### What infrastructure (computing resources and network access) do you need?

What we currently have at Packet/Equinix is doing a good job, more disk space to reduce the number of rebuilds (called sstate in yocto/openembedded parlance) would be nice.

### Describe the continuous integration (CI) system in use or desired for this project.

This is an area where I would like to improve.  Current users are dispatching jobs daily via automated scripts.  I would like to use something like gitlab CI to visualize and automate it in a more standard way.  

### Please state your contributions to the open source community and any other relevant initiatives.

Yocto/OpenEmbedded Developer
OpenEmbedded Board Member
Linux kernel driver maintainer
https://www.linkedin.com/in/jondmason/

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers
