### ISSUE TITLE
GNU Guix build farm - Works On Arm Sponsored

### ISSUE THREAD

**Issue by lfam** [WorksOnArm/cluster#254]
### Name, email, company, job title

Leo Famulari
leo@famulari.name
[GNU Guix](https://guix.gnu.org/)
Volunteer contributor

### Project Title and description

We ask for your help in expanding our build farm and CI pipeline for the aarch64 platform.

GNU Guix is a GNU / Linux operating system distribution based on the functional packagement management idea pioneered by [Nix](https://en.wikipedia.org/wiki/Nix_package_manager).

Currently, the distribution includes ~16000 packages, and has been ported to the aarch64, armhf, x86_64, i686, and ppc64le platforms. Our [build farm](https://ci.guix.gnu.org/) has enough machines for the x86 family, but we are requesting assistance in expanding our build capacities for aarch64; if we can efficiently build armhf binaries on the same machines, we'll do that, too.

By modeling package compilation and dependencies in a functional way, Guix offers a hybrid of "build from source distros" (like Gentoo) and "binary distros" (like Debian). Guix is basically a build-from-source distro, but with the possibility to transparently "substitute" the results of building, if such binaries are available for substitution.

Our goal is to offer binaries for all of our packages, on all of our platforms, and to make them available within 24 hours of package updates in our "rolling release" model. We reach this goal for x86, but not currently for ARM.

### Which members of the community would benefit from your work?

Every Guix user with ARM computers would benefit if we increased our capability to build packages for ARM platforms.

Since Guix is a build-from-source distro that can transparently "substitute" binaries, these users always have the option to build everything from source if binaries are not available.

However, most consumer ARM devices currently deployed lack the power to comfortably build an entire operating system from source, so the user experience would be massively improved if we increased our build farm's capacity. And, I think that our ARM userbase would grow as a result.

### Is the code that you’re going to run 100% open source? 

Yes. Guix itself is GPL3 (or later) and, as a [GNU project](https://www.gnu.org/distros/free-system-distribution-guidelines.en.html), our distro only includes and recommends free / open source software.

The entire operating system is contained in this Git repo:

https://git.savannah.gnu.org/cgit/guix.git

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

We would target Armv8.0-A without any extensions when compiling; we aim to support that as the lowest common denominator for 64-bit ARM. Please let me know if you think this plan is based on a misunderstanding of ARM's architectural extension system.

### What infrastructure (computing resources and network access) do you need?

We are looking for performance-oriented hardware with high core counts (64 or greater, ideally), more than 64 GB RAM (we'll be doing multi-threaded compilation), and ideally a minimum 100 Mbit/s symmetric internet connections (for passing binaries and sources back and forth to our build farm's coordinator node). Solid state storage is ideal, but we don't need a huge amount; 512 GB or 1 TB would be more than sufficient.

### Describe the continuous integration (CI) system in use or desired for this project.

We use [GNU Cuirass](https://guix.gnu.org/en/cuirass/), which is developed within the Guix project. Currently it is more of a build coordinator than a full CI, although it's [improving rapidly](https://guix.gnu.org/en/blog/2021/cuirass-10-released/) based on [funding from NLnet](https://othacehe.org/gnu-guix-continuous-integration---nlnet-grant.html).

Another project member is working on a complementary pure CI project (as opposed to build farm + CI), the Guix Data Service ([example page](https://data.guix-patches.cbaines.net/revision/d0cdfd2596b60d23675ca869be8121f32d307e51)).

We build our packages, and Guix itself, on arm64 continuously, although we can't "keep up" building all the packages on the Overdrive 1000s that we currently own. As an example, here is the CI dashboard for the Cuirass package itself, on aarch64 for our master branch:

https://ci.guix.gnu.org/search?query=spec%3Aguix-master+system%3Aaarch64-linux+cuirass

And here is the job that builds Guix itself; click one of the rows to see that it is building for aarch64, x86_64, and i686.

https://ci.guix.gnu.org/jobset/guix-modular-master

### Please state your contributions to the open source community and any other relevant initiatives.

I've been volunteering with Guix since 2015. I've made significant contributions to security of the overall system, mentoring new contributors, and in creating and maintaining packages.

There's a lot more to "contributing" than Git commits, but [here](https://git.savannah.gnu.org/cgit/guix.git/log/?qt=committer&q=Leo+Famulari) are the commits I've either written or reviewed on behalf of others for Guix.

**Comment by kat-co** [comment]
FWIW, I can confirm that @lfam contributes to Guix above and beyond commits. They were just assisting me in diagnosing an aarch64 build failure yesterday in Guix's chat channel.

I would also be very happy to see Guix's capacity to build arm binaries increased. I have a few low-power aarch64 devices I'd like to use Guix on, and I would plan to purchase many more if I could run Guix on them.

Thank you for your consideration!

**Comment by pgmwoa** [comment]
Thanks for your interest in Works On Arm program. Currently migration is in progress and we have limited inventory. In meantime we are trying to check possibility of alternate resources. We will get back when we have some more details.

**Comment by lfam** [comment]
Thanks for your reply!

We look forward to hearing about alternate resources.

Please let us know if there's anything we can do to help our application succeed.

**Comment by lfam** [comment]
Our request wasn't granted due to limited inventory. Thanks anyways!
