### ISSUE TITLE
Veracruz - Works On Arm Sponsored

### ISSUE THREAD

**Issue by ebeasant-arm** [WorksOnArm/cluster#255]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title
Edwin Beasant, edwin.beasant@arm.com, Arm, Staff Software Engineer
Dominic Mulligan, dominic.mulligan@arm.com, Arm, Principal Research Engineer.

Note that projects with two or more participants are preferred.

### Project Title and description
Veracruz: privacy-preserving collaborative compute

Veracruz is a framework for defining and deploying collaborative, privacy-preserving computations amongst a group of mutually mistrusting individuals. Some potential use-cases for Veracruz include:

Privacy-preserving collaborative machine learning,
Privacy-preserving delegated computations from a computationally weak device to a more capable (but potentially untrusted) edge device or server,
Secret auctions, elections or polls, surveys,
...and many more.

### Which members of the community would benefit from your work?
Confidential Computing, Rust, Wasm, WASI and security related work.

### Is the code that you’re going to run 100% open source? 
Yes

Provide the URLs where it is located, or a Git repository.
https://github.com/veracruz-project

### Does this project require ARMv8.2 (Yes/No/Not Sure)?
No

### What infrastructure (computing resources and network access) do you need?
1 eMAG - would like to use the current Google Project Oak shared machine, already provisioned.
Project Oak is in collaboration with Veracruz.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe the continuous integration (CI) system in use or desired for this project.
Currently Github Actions + Docker. 

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.
Not currently, but would be desirable

Are you using a hosted CI system for some or all of your existing testing? 
Not currently

### Please state your contributions to the open source community and any other relevant initiatives.
aarch64 integration of Google Project Oak, ksh93, Rust, Go (Open Solaris/Solaris 11/12), bit of Coreboot and SeaBios in the past.

Brag a little bit about yourself, please!
Working with Arm for 3 years on confidential compute platforms and support stacks, bringing projects together to co-operate and move forward together is very much my thing :-)

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Project renamed to Veracruz and enabled access so that project can use the shared machine, the existing eMag that was under Project Oak. New user access added for Dominic Mulligan.
