### ISSUE TITLE
Varnish Cache - Works On Arm Sponsored

### ISSUE THREAD

**Issue by bsdphk** [WorksOnArm/cluster#256]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title

Poul-Henning Kamp, phk@varnish-cache.org, project founder & architect

### Project Title and description

Varnish Cache

Varnish Cache is a HTTP accelerator which moves a significant fraction of all HTTP traffic in the world, (about 20% of the top 10K sites according to builtwith.com, and Fastly's CDN started from Varnish Cache.)

Varnish is also an attempt to write code with the highest realistic quality, to see if that actually makes a difference in the long run.  (Our CI covers 90.5% of all code lines.  And we have one of the lowest defect rates on Coverity)

### Which members of the community would benefit from your work?

Anybody wanting to run their Varnish on an Arm server.

### Is the code that you’re going to run 100% open source? 

Yes, BSD licensed.

https://github.com/varnishcache/varnish-cache/

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

In theory we should run on any moderately well-behaved OS+CPU, our current validated boundaries are (arm32, arm64, i386, x86, IBM zSeries), and (FreeBSD, Various Linux'en, SunOS).

### What infrastructure (computing resources and network access) do you need?

Currently we test arm64 on a RockPro64/FreeBSD, and arm32 on a BeagleBoneBlack, which shows how little we can get away with, but I would like to get a "real" arm64 machine, preferably with a different OS into our CI.

Needs:

* shell-access, preferably root, but unpriv will do.
* git pull from github
* ssh out to central collector.
* 1GB disk.
* At least one core (duh!), but preferably 4-8 with  ½GB ram per core.

### Describe the continuous integration (CI) system in use or desired for this project.

We use our own `vtest` because none of the "big guys" support all the OS/HW combinations we need.

http://varnish-cache.org/vtest/

vtest is a shell-script, it checks for updates every minute and does a build/make distcheck if anything have been commited.

(source: https://github.com/varnishcache/varnish-cache/blob/master/tools/vtest.sh)

### Please state your contributions to the open source community and any other relevant initiatives.

I wrote the first password-encryption to replace the v7 UNIX one ("md5crypt"), it protected approx half of all passwords on the net back in dot-com days.

I wrote the first VM-suitable and paranoid malloc ("phkmalloc")

I invented FreeBSD jails (the inspiration for containers).

I were the most produtive FreeBSD comitter for a decade, including release engineering for a handful of releases, and FreeBSD core member.

I was the first to synchronize a computer to UTC at tens of nanosecond precision.

I designed and wrote Varnish Cache.

Wrote several often quoted articles for ACM Queue.

I "exposed" NSA's Operation Orchestra and how it is used to trojan FOSS software and communities (https://www.youtube.com/watch?v=fwcl17Q0bpk)

In my spare time I am writing an emulator for the Rational R1000/s400 Ada computer. (https://datamuseum.dk/wiki/Rational/R1000s400) which executes Ada almost entirely in hardware and which had the first real "Integrated Development Environment" in the world.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
There are no details added to the ticket. Pls add or else it will be considered for closure.

**Comment by pgmwoa** [comment]
Thanks for details.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA program.
As communicated via email, we would not be able to support the project at this moment due to limited inventory and high number of competing projects.
Closing the ticket for now due to no response.
