### ISSUE TITLE
Kubernetes - Request 2 Ampere Altra machines for K8s e2e test

### ISSUE THREAD

**Issue by hejianet** [WorksOnArm/cluster#257]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

If you are just making a comment, ignore/delete those fields and file your issue.

Proposals will be evaluated on a biweekly cycle by Arm and Equinix Metal.

### Name, email, company, job title

Dave Chen <Dave.Chen@arm.com>
Howard Zhang <Howard.Zhang@arm.com>

### Project Title and description
Kubernetes e2e tests 
### Which members of the community would benefit from your work?
Dave Chen @chendave 
Howard Zhang @zhlhahaha
### Is the code that you’re going to run 100% open source? 
Yes
https://github.com/kubernetes/kubernetes
### Does this project require ARMv8.2 (Yes/No/Not Sure)?
No
### What infrastructure (computing resources and network access) do you need?
No

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.
No

Are you using a hosted CI system for some or all of your existing testing? 
Yes
### Please state your contributions to the open source community and any other relevant initiatives.
K8s scheduler preemption enhancement.
Dave Chen became the reviewer of K8s scheduler in 2020.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by hejianet** [comment]
Sorry, this request is on behalf of @justin-he
justin.he@arm.com
I logined on the github account with my gmail id.

**Comment by justin-he** [comment]
Confirmed, thanks

> Sorry, this request is on behalf of @justin-he
> [justin.he@arm.com](mailto:justin.he@arm.com)
> I logined on the github account with my gmail id.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
