### ISSUE TITLE
DynamoRIO - Works On Arm Sponsored

### ISSUE THREAD

**Issue by AssadHashmi** [WorksOnArm/cluster#258]
This is an access request for Works on Arm test and CI infrastructure for the DynamoRIO project.
We require v8.2 hardware for supporting newer machines.

### Name, email, company, job title
Assad Hashmi
assad.hashmi@arm.com
Arm
Software Engineer

Paul Walker
paul.walker@arm.com
Arm
Architect

### Project Title and description
DynamoRIO is a runtime code manipulation system that supports code transformations on any part of a program, while it executes. It's primary purpose is as a dynamic binary instrumentation framework (DBI) which enables developers to instrument binaries at runtime using a well-defined API. See https://dynamorio.org/index.html

### Which members of the community would benefit from your work?
All users and developers of DynamoRIO who want to use, maintain and improve it on Arm hardware.

### Is the code that you’re going to run 100% open source?
Yes 

Provide the URLs where it is located, or a Git repository.
https://github.com/DynamoRIO

### Does this project require ARMv8.2 (Yes/No/Not Sure)?
Yes

### What infrastructure (computing resources and network access) do you need?
This is a long-running project which requires support at the level of currently provided instances.

### Describe the continuous integration (CI) system in use or desired for this project.
Jenkins is currently being used for CI.

Are you testing every check-in on arm64?
Yes, we are testing every check-in on arm64 with a pre-commit test suite triggered from GitHub pull requests.

If so, share a public URL of a CI dashboard.
http://139.178.83.194:8080

### Please state your contributions to the open source community and any other relevant initiatives.
Arm added arm64 support to DynamoRIO in 2014 and have been contributing to DynamoRIO on a regular basis since then.
One of our publicly available products is based on DynamoRIO, the Arm Instruction Emulator. See the link on the DynamoRIO home page (https://dynamorio.org/index.html) to https://developer.arm.com/tools-and-software/server-and-hpc/arm-architecture-tools/arm-instruction-emulator

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by AssadHashmi** [comment]
> We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

Thanks @pgmwoa
Would it be possible to provision the machine with a Linux kernel version higher than 4.18 ?
That's because our development work requires the restartable sequences (`rseq`) feature of Linux.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers
