### ISSUE TITLE
Python-Pillow on ARM

### ISSUE THREAD

**Issue by wiredfool** [WorksOnArm/cluster#26]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

### Name, email, company, job title

Eric Soroos (@wiredfool), eric@soroos.net, Co-Maintainer, Pillow Project
Alex Clark (@aclark4life) , aclark@aclark.net, Co-Maintainer, Pillow Project

### Project Title and description

The Pillow Project is the maintained fork of the Python Imaging Library, an open source library for image manipulation in python. 

### Which members of the community would benefit from your work?

Any of our users who would be running on ARM hardware. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Open Source, https://github.com/python-pillow/Pillow

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We're currently interested in access to a Type 2A machine for the initial work, with ordinary networking access required for installing software and debugging the results.  It would be ideal if we could set up some form of CI for ongoing testing on this platform to ensure that the initial support continues to work.  

### Please state your contributions to the open source community and any other relevant initiatives

I've been part of the Python Community for 15 years, and a maintainer for Pillow for the last 3.

**Comment by vielmetti** [comment]
hi @wiredfool - can you list a second point of contact for this effort? always best to have two people (or three) involved so that there's continuity in case of any questions.

**Comment by wiredfool** [comment]
Updated.

**Comment by vielmetti** [comment]
Approved! I'm on deadline today, but if you want to jump on a call tomorrow I have open office hours at 0900 and 1600 Eastern (or via chat on the #worksonarm channel on IRC or Packet Community Slack) to get you oriented.

**Comment by wiredfool** [comment]
Thanks, I'll ping you tomorrow.

**Comment by vielmetti** [comment]
@wiredfool - can you give me an update on progress?

Also, if you are running a CI infrastructure on arm64 to help test this work, can you fill me in on details of how it works and what tooling you are using? I'm trying to collect that info from projects old and new.

**Comment by vielmetti** [comment]
@aclark4life this is the stalebot https://github.com/probot/stale very handy to have to keep on top of issues! You can crank the reply times up or down depending on the pace of the effort.

**Comment by wiredfool** [comment]
Rough progress -- got in to a machine once, gave it a whirl and generally found that the parallelisim was good, but single core perf was pretty bad. OpenMP certainly helped, and NEON would have as well. Unfortunately, real life has drastically cut down the amount of time I have to spend on Pillow, so this part is on the back burner for now.

**Comment by vielmetti** [comment]
Thanks for the update!

I'll close this issue for now (so that stalebot can take a rest). If you find yourself putting Pillow on the front burner again, ping me again - by then I'm hopeful we'll have a next generation of systems with better single core perf to look at.
