### ISSUE TITLE
Gentoo - Works On Arm Sponsored

### ISSUE THREAD

**Issue by mattst88** [WorksOnArm/cluster#261]
### Name, email, company, job title

Matt Turner \<mattst88@gentoo.org\>, Gentoo Linux, Developer.

### Project Title and description

Gentoo Linux is a Linux distribution built using the Portage package management system. Unlike a binary software distribution, the source code is compiled locally according to the user's preferences and is often optimized for the specific type of computer.

### Describe your use case for these machines

We will use the machines for testing packages on ARM as well as for building our ARM installation media, to allow users to install Gentoo on their own ARM computers.

### Which members of the community would benefit from your work?

Any users who use Gentoo Linux on ARM computers. Benefits non-Gentoo users of any free software packages that we contribute to as a result of our testing.

### Is the code that you’re going to run 100% open source? 

Yes.

Our `ebuild` repository (package recipes) is located here: https://gitweb.gentoo.org/repo/gentoo.git/
Our `catalyst` release building tool is located here: https://gitweb.gentoo.org/proj/catalyst.git/

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No, but would be helpful in case our users have such hardware and need support.

### What infrastructure (computing resources and network access) do you need?

This is a request for ongoing support. We'd appreciate high-core count (Gentoo Linux is a source-based distribution) and sufficient RAM to keep the cores busy!

The Gentoo Foundation is the legal entity that provides financial support for Gentoo Linux.

### Describe / Name the continuous integration (CI) system for this project.

The machine will not be used for CI but rather for package compilation and runtime testing.

Our CI results for the `ebuild` repository are available here: https://qa-reports.gentoo.org/output/gentoo-ci/output.html

### Please state your contributions to the open source community and any other relevant initiatives.

I've contributed to Gentoo Linux for 10 years where I'm the Lead of the Release Engineering team responsible for producing installation media for Gentoo Linux. I have contributed to a variety of free software projects: https://www.openhub.net/accounts/mattst88

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.

**Comment by pgmwoa** [comment]
@mattst88 , Need your attention on email sent related to Mt Snow upgrade.

We would like to update you that there is a new production silicon available from Ampere that needs to be upgraded in the Mt Snow system reserved for your project.

The new silicon will allow upgrade to the latest microcode, fixes for any security flaws and also occasional odd behaviors that you may have observed. This silicon upgrade will also help ensure that the latest microcode and firmware versions that Ampere supports can be installed on these systems to keep them up to date. We expect this upgrade to be agnostic to any software / applications you have been running.

The upgrade is being planned by Equinix in the week of 21st March.

Important points to be noted:
• The upgrade of the machine will take one week and during that time you will not be able to access or use those machines.
• We will do our best to retain the storage state of each machine but we can’t guarantee that some or all systems won’t have data lost. We advise you to plan backup of project data before the planned upgrade date, as risk mitigation.

We do understand that this may cause some inconvenience to you, we truly appreciate your cooperation. Please let us know in case you have any questions.

**Comment by shipra-ps** [comment]
Hi Team,

We had sent one important communication to you on 25th Jul'24 from email Shipra.Snehi@arm.com. Request you to acknowledge that.

Regards,
WoA Program Team
