### ISSUE TITLE
Ruby - Works On Arm Sponsored

### ISSUE THREAD

**Issue by junaruga** [WorksOnArm/cluster#262]
### Name, email, company, job title

Jun Aruga, jaruga [at] redhat.com (or jaruga [at] ruby-lang.org), Red Hat, Software Engineer

I am requesting on behalf of the Ruby project. We believe [Works On Arm is interested in supporting us](https://www.worksonarm.com/projects/).

### Project Title and description

Ruby - A dynamic, open source programming language with a focus on simplicity and productivity.

### Describe your use case for these machines

* To build and debug ruby/ruby to fix ARM specific issues with interactive debugging tools such as GDB.
* To set up self hosting type CI service called "Persistent Workers" of Cirrus CI.
  You can see the [page](https://cirrus-ci.org/guide/persistent-workers/), and the [Ruby ticket](https://bugs.ruby-lang.org/issues/17720) for detail.

### Which members of the community would benefit from your work?

Every people, communities and organizations using Ruby.

### Is the code that you’re going to run 100% open source? 

Yes.

> Provide the URLs where it is located, or a Git repository.

https://github.com/ruby
https://www.ruby-lang.org/

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not Sure.

### What infrastructure (computing resources and network access) do you need?

Long term, ongoing.

For organizations supporting where we can say publicly, you can see [this page](https://bugs.ruby-lang.org/projects/ruby/wiki/CIServers).

### Describe / Name the continuous integration (CI) system for this project.

> Will these machines be exclusively used for CI purposes?

No, mainly debugging purpose, later CI.

> Please share a public URL of the CI dashboard (if applicable).

I do not understand this question. A public URL of the Ruby's CI pages is  https://bugs.ruby-lang.org/projects/ruby/wiki/CIServers

### Please state your contributions to the open source community and any other relevant initiatives.

> Brag a little bit about yourself, please!

Well, I am not sure what the point of this question is. In the Ruby project, I started to work on CI and non-x86_64 things.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers

**Comment by fkorotkov** [comment]
Hey @junaruga, I'm founder of Cirrus CI and we will have managed arm64 instances pretty soon. I've emailed you with details if you are interested.

**Comment by junaruga** [comment]
@fkorotkov Hi I received your email. Sorry I didn't have time to reply. Please wait. Thanks.
