### ISSUE TITLE
OpenHPC - Works On Arm Sponsored

### ISSUE THREAD

**Issue by koomie** [WorksOnArm/cluster#263]
### Name, email, company, job title

Karl Schulz
karl@oden.utexas.edu
Research Associate Professor, University of Texas

Requesting on behalf of the OpenHPC Technical Steering Committee: https://github.com/openhpc/ohpc/wiki/Governance-Overview

### Project Title and description

OpenHPC: Community building blocks for HPC systems

### Describe your use case for these machines

These machines are used to provide build servers within our public Open Build Service infrastructure to build RPMs for `aarch64` for use by HPC systems worldwide.

### Which members of the community would benefit from your work?

Academic, lab, and industrial sites benefit from OpenHPC to obtain common HPC software components for system installation tools, compilers, MPI runtimes, and a variety of scientific libraries and performance tools.

### Is the code that you’re going to run 100% open source? 

Yes.

> Provide the URLs where it is located, or a Git repository.

https://github.com/openhpc/ohpc

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not sure. 

### What infrastructure (computing resources and network access) do you need?

Long term, ongoing (to replace our current Works on Arm infrastructure).

### Describe / Name the continuous integration (CI) system for this project.

We use a standalone instance of the [Open Build Service](https://openbuildservice.org) for performing automated CI RPM builds.  We use [Jenkins](https://test.openhpc.community:8443) for our installation testing CI infrastructure

> Will these machines be exclusively used for CI purposes?

Yes. These will be used as build systems.

> Please share a public URL of the CI dashboard (if applicable).

https://obs.openhpc.community

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!

General info on the community at http://openhpc.community.  I've been serving as the OpenHPC Project Lead since its inception in 2016.  University overview at: https://www.oden.utexas.edu/people/1595/

## Important reminders and logistics

We highlight Works on Arm directly on our CI infrastructure (OBS and Jenkins) - thank you for the support!

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers.

**Comment by shipra-ps** [comment]
Hi Team,

I had mailed to 'karl@ices.utexas.edu' about 2 months back to inform that the duration for the server has expired. I haven't heard from this mail id so far, hence raising the concern here.

Can anyone please provide us an update on the current server usage and future plans for the project builds on ARM?

**Comment by shipra-ps** [comment]
This is a follow-up on my previous comment. Request to confirm if your team is still using our servers.
I am afraid we will have to revoke the access to the server if we don’t receive any response by 31st May’24.

**Comment by koomie** [comment]
> This is a follow-up on my previous comment. Request to confirm if your team is still using our servers. I am afraid we will have to revoke the access to the server if we don’t receive any response by 31st May’24.

Also confirming the project is using this resource for arm-based builds.  Thank you!
