### ISSUE TITLE
PCL - Works On Arm Sponsored

### ISSUE THREAD

**Issue by kunaltyagi** [WorksOnArm/cluster#264]
### Name, email, company, job title
Maintainers:
1. @kunaltyagi, (tyagi.kunal at live.com)
2. @mvieth, (mvieth at techfak.uni-bielefeld.de)
3. @larshg, (larshg at gmail.com)

### Project Title and description
https://github.com/PointCloudLibrary/pcl

The Point Cloud Library (PCL) is a standalone, large scale, open project for 2D/3D image and point cloud processing.

### Describe your use case for these machines
1. Building and testing on ARM, as part of CI
2. Benchmarking, since cloud CI are not stable baseline

### Which members of the community would benefit from your work?
1. All users from better benchmarking
2. Developers and users with ARM platform (embedded, cloud, mobile and now Apple M1)

### Is the code that you’re going to run 100% open source? 

Yes. https://github.com/PointCloudLibrary (all initiatives are open source, including website)

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not sure

### What infrastructure (computing resources and network access) do you need?

This is a request for continuous ongoing support. Currently, we do not know of any foundation that can help us with long term needs.

For comparison with our current Linux CI, we have the following configuration:
* GCC + CUDA: build, test, install, ensure tutorials are working
* Clang: build and test

With ARM servers, we expect to add:
* ARM Baseline: build, create baseline for speed/memory
* ARM GCC CI: build and test. It'd be nice to use clang as well to be 1:1 with the Linux CI, but GCC CI is a bare minumum

### Describe / Name the continuous integration (CI) system for this project.

We currently use Azure for the CI, and might be adding some GitHub workflows

## Will these machines be exclusively used for CI purposes?

Yes. Having dedicated machine might enable us to create continuous benchmarks as well

Public URL: https://dev.azure.com/PointCloudLibrary/pcl/_build

### Please state your contributions to the open source community and any other relevant initiatives.

Not relevant since the request is for an open source project, not personal requirements.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA program.
As communicated via email, we would not be able to support the project at this moment due to limited inventory and high number of competing projects. Closing the ticket for now due to no response.
