### ISSUE TITLE
Kata Container - Works On Arm Sponsored

### ISSUE THREAD

**Issue by jongwu** [WorksOnArm/cluster#265]
### Name, email, company, job title

Jianyong Wu, jianyong.wu@arm.com, Arm, software engineer

### Project Title and description

Kata Containers

### Describe your use case for these machines

Now, 3 Arm servers have been reserved for Kata. But one of the servers, whose id is 136c9ed7-dace-43c8-8fe8-18ae952b8979, is a Qualcomm server and may be has hardware issue, I think, as I can't start a KVM virtual machine on it. So can I apply for another server, which is better from other device provider, e.g. Ampere, to replace this one?

### Which members of the community would benefit from your work?

All user of using Kata Containers, especially working on arm.

### Is the code that you’re going to run 100% open source? 

yes

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No
### Describe / Name the continuous integration (CI) system for this project.

jenkins CI only

see http://jenkins.katacontainers.io/

### Please state your contributions to the open source community and any other relevant initiatives.

I'm responsible for Kata Arm CI maintain work

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Duplicate. 
There is a new ticket filed #270 with latest / updated project information. Hence closing this old ticket.
