### ISSUE TITLE
APK Fission - Works On Arm Sponsored

### ISSUE THREAD

**Issue by Aerdan** [WorksOnArm/cluster#266]
### Name, email, company, job title

Síle Ekaterin Aman, sheila@vulpine.house, APK Fission, founder
Max Rees, me@maxre.es, APK Fission, contributor

### Project Title and description

APK Fission

APK Fission is intended to provide cross-APK infrastructure for Ubuntu-style personal package archives and RPM Fusion-style access to freely-distributable, but license-restricted or non-Free, software for APK-based distributions like Alpine Linux and Adélie Linux.

### Which members of the community would benefit from your work?

Users of Adélie Linux and Alpine Linux who want to use software by smaller teams and developers who don't have the resources for CI/CD, as well as partially-encumbered open-source software.

### Is the code that you’re going to run 100% open source?

Yes

Provide the URLs where it is located, or a Git repository.

https://git.adelielinux.org/sroracle/apkfoundry
https://git.apkfission.net

### Does this project require ARMv8.2 (Yes/No/Not Sure)?

No.

### What infrastructure (computing resources and network access) do you need?

Builders to build our packages for all our ARM architectures (we build native)
CI for all our ARM architectures

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Long term
### Describe the continuous integration (CI) system in use or desired for this project.

We use GitLab.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

https://git.apkfission.net

Are you using a hosted CI system for some or all of your existing testing?

I run my own gitlab-runner and APKFoundry install.

### Please state your contributions to the open source community and any other relevant initiatives.

I have been involved in open-source in a minor way since 2006, particularly as administration for atheme.org, but have contributed to ZSNES (few patches and support), Audacious Media Player (few patches), Angband (build system), Chromium (support), and packages for Alpine Linux and, in the past few years, Adélie Linux.

I am also participating in Microsoft's TEALS program for the 2021-22 school year.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA program.
As communicated via email, we would not be able to support the project at this moment due to limited inventory and high number of competing projects. Closing the ticket for now due to no response
