### ISSUE TITLE
Electron - Works On Arm Sponsored

### ISSUE THREAD

**Issue by jkleinsc** [WorksOnArm/cluster#267]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
John Kleinschmidt, jkleinsc@electronjs.org, Microsoft, Senior Software Engineer

Note that projects with two or more participants are preferred.

### Project Title and description
[Electron](https://www.electronjs.org/)
Electron allows developers to build cross platform desktop apps with JavaScript, HTML, and CSS. Supported platforms are macOS (intel and arm64), Windows (ia32, x64, arm64), and Linux (ia32, x64, armv7 and armv8).

### Describe your use case for these machines
These machines would be used to test armv7 and armv8 builds of Electron as part of Electron's CI.
Eg: https://github.visualstudio.com/electron/_build?definitionId=40&_a=summary and https://github.visualstudio.com/electron/_build?definitionId=41&_a=summary

### Which members of the community would benefit from your work?
Application developers who are looking to create desktop applications that run on armv7 and armv8 hardware.

### Is the code that you’re going to run 100% open source? 

Yes. https://github.com/electron/electron

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
No

### What infrastructure (computing resources and network access) do you need?
Ideally something that supports both armv7 and armv8.

The Electron project needs ongoing support for armv7/armv8 hardware.

### Describe / Name the continuous integration (CI) system for this project.
Azure Devops, though possibly will be moving to CircleCI with the new machine(s).

Will these machines be exclusively used for CI purposes?
Yes

Please share a public URL of the CI dashboard (if applicable).
https://github.visualstudio.com/electron/_build?definitionId=40&_a=summary and https://github.visualstudio.com/electron/_build?definitionId=41&_a=summary

### Please state your contributions to the open source community and any other relevant initiatives.

The Electron open source project is a member of the OpenJS foundation and consists of members from GitHub, Microsoft, Atlassian, and Slack as well as many open source contributors. Electron powers popular desktop applications like Skype, Visual Studio Code, Slack, and Atom. It is estimated that there are currently over 10,000 Electron applications that have been developed and that number grows everyday.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers (Ampere eMags) ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.
