### ISSUE TITLE
GNOME - Works On Arm Sponsored

### ISSUE THREAD

**Issue by barthalion** [WorksOnArm/cluster#268]
### Name, email, company, job title

Bartłomiej Piotrowski, bpiotrowski@gnome.org, GNOME Foundation, DevOps Engineer

### Project Title and description

The GNOME Foundation is a non-profit organization that believes in a world where everyone is empowered by technology they can trust. We do this by building a diverse and sustainable free software personal computing ecosystem.

### Describe your use case for these machines

The machine(s) will be used as GitLab CI runners, primarily for gnome-build-meta that is an integration test for GNOME components to ensure they're in buildable state before releasing. Another use case to keep CPU busy is generic ARM build tests for projects hosted on our GitLab.

### Which members of the community would benefit from your work?

GNOME Release team, and more widely all maintainers of GNOME projects.

### Is the code that you’re going to run 100% open source? 

Yes; https://gitlab.gnome.org

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not sure. Manisha Nigam told me that there should be a server with following spec available for us: `Ampere eMAG 8180 32 core @3.0Ghz, 128GB RAM, 1x480GB SSD, NIC 2x10Gbps Bonded ports.`, that will replace the current ARM machine we're using.

### What infrastructure (computing resources and network access) do you need?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe / Name the continuous integration (CI) system for this project.

GitLab CI. The machine will be used solely for that.

### Please state your contributions to the open source community and any other relevant initiatives.

I have been an Arch Linux developer for over 10 years, and was developing Alpine Linux at the time it was switching from uClibc to musl. These days I'm managing infrastructure for GNOME and Flathub.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers (Ampere eMag) ready for you. You will get an email as soon as the hardware is reserved and ready for use

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.
