### ISSUE TITLE
Freedesktop-sdk- Works On Arm Sponsored

### ISSUE THREAD

**Issue by jjardon** [WorksOnArm/cluster#269]
### Name, email, company, job title
- Javier Jardon, jjardon@gnome.org, Systems engineer

### Project Title and description
Freedesktop-sdk

The freedesktop-sdk is a project that provides Platform and SDK runtimes for Flatpak apps and runtimes based on FOSS modules.

We are also a dependency of the Flatpak project, which has over 96 contributors and 1000s of users across multiple distros.

See https://freedesktop-sdk.io/

### Describe your use case for these machines
The machine(s) will be used as GitLab CI runners, to be sure the aarch64 support in flatpak builds and works as expected

This is in order to keep testing/patching/improvement the base runtime SDK/Platform that all Flatpak applications will be running on in aarch64 environments

### Which members of the community would benefit from your work?
- All the flatpak ecosystem. This means GNOME, KDE, mozilla firefox and other projects that use flatpak as a app distribution method
- We have plans to support snap as well (currently in testing), so all the snap ecosystem as well

### Is the code that you’re going to run 100% open source? 
Yes this project is 100% free and open source, under the MIT license.

The project and code can be viewed here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Not sure. Manisha Nigam mentioned that there should be a server with following spec available for us: Ampere eMAG 8180 32 core @3.0Ghz, 128GB RAM, 1x480GB SSD, NIC 2x10Gbps Bonded ports., that will replace the current ARM machine we're using.

### What infrastructure (computing resources and network access) do you need?
See above

### Describe / Name the continuous integration (CI) system for this project.
GitLab-CI. The machine will be used solely for that.

See https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/pipelines

### Please state your contributions to the open source community and any other relevant initiatives.
- I've been GNOME contributor and then part of the GNOME Release Team since 2011 (I help setup the initial CI infra there as well)
- I've been working in freedesktop-sdk since 2018, and I'm currently one of the maintainers

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers (Ampere eMag) ready for you. You will get an email as soon as the hardware is reserved and ready for use

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources.

**Comment by shipra-ps** [comment]
Just wanted to check if you are still using our servers. If anyone else is using the servers from your team, then pls loop them in and help us with inputs.

**Comment by jjardon** [comment]
We are very much using them! crucial part of our build infrastructure for ARM

**Comment by shipra-ps** [comment]
Oh, thanks for your quick response. 
I had been mailing you from my email id shipra.snehi@arm.com since last few months but didn't get any revert. Can you pls revert on the email with subject line "Review : Freedesktop-SDK - Works on Arm Sponsored" so that I can make a note of it.

**Comment by shipra-ps** [comment]
If there is any change in email id for communication, let me know. I have just emailed on "jjardon@gnome.org" for your quick reference on the mail chain.
