### ISSUE TITLE
hlibc, the Ironwill toolchain build system and the Arbsh arbitrary precision math/POSIX `bc impl.

### ISSUE THREAD

**Issue by cmgraff** [WorksOnArm/cluster#27]
Christopher M. Graff, cm0graff@gmail.com
There are now 8 contributors working on hlibc and ronwill see hlibc/COPYING for details.
We also are writing a version of the arbitrary precision POSIX `bc'.

hlibc is a standalone libc which targets the linux syscall ABI
ironwill is a comprehensive toolchain build system that builds toolchains and root filesystems using musl, uClibc and glibc standard C libraries.

I and the other 7 contributors to hlibc, ironwill and arbsh/bc/arbprec would benefit from having access to modern arm systems.

The code is MIT licensed.
https://git.zv.io/me/hlibc/
http://www.csit.parkland.edu/~cgraff1/hlibc/

https://github.com/cmgraff/ironwill
http://www.csit.parkland.edu/~cgraff1/ironwill/

https://github.com/cmgraff/arbsh
http://www.csit.parkland.edu/~cgraff1/arbsh/

We need arm machines of all types, running linux and/or FreeBSD/NetBSD with ssh access.

This is a request for long-term contiguous support.

**Comment by vielmetti** [comment]
contacted via email

**Comment by vielmetti** [comment]
Project created, invite email sent.

**Comment by vielmetti** [comment]
Additional invites sent.

**Comment by vielmetti** [comment]
Work has started on the `hlibc` port, so closing this issue.
