### ISSUE TITLE
Kata Container - Works On Arm Sponsored

### ISSUE THREAD

**Issue by jongwu** [WorksOnArm/cluster#270]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Justin He, justin.he@arm.com, Arm, principle software engineer
Jianyong Wu, jianyong.wu@arm.com, Arm, software engineer

### Project Title and description

kata containers,
Kata Containers is an open source community working to build a secure container runtime with lightweight virtual machines that feel and perform like containers, but provide stronger workload isolation using hardware virtualization technology as a second layer of defense.

### Describe your use case for these machines

These machines will serve as Jenkins slave nodes to run Arm CI test for kata containers

### Which members of the community would benefit from your work?

The developers of kata containers and all of the people that will try kata container on Arm

### Is the code that you’re going to run 100% open source? 

Yeah, see https://github.com/kata-containers

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

For now, No

### What infrastructure (computing resources and network access) do you need?

It's better a Altra server.

### Describe / Name the continuous integration (CI) system for this project.

Jenkins CI

see http://jenkins.katacontainers.io/label/arm_node/

### Please state your contributions to the open source community and any other relevant initiatives.

Jianyong:
For now I works on kata container, cloud hypervisor and edk2. I focus on maintaining Arm CI, bug fix and feature enablement for  kata container on Arm side.

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by jongwu** [comment]
@justin-he

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
