### ISSUE TITLE
Request to upgrade previously provided AArch64 bare-metal instance for the Rust Language project

### ISSUE THREAD

**Issue by raw-bin** [WorksOnArm/cluster#272]
Kind attention: @pietroalbini, @ashleygwilliams, @vielmetti, @awafaa

### Name, email, company, job title

- Robin Randhawa, robin.randhawa@arm.com, Arm, Technical Director for System Software Architecture
- Pietro Albini, pietro@pietroalbini.org, Rust Core Team Member

### Project Title and description

The Rust Language.

### Describe your use case for these machines

Rust language compiler CI/CD pipelines. Arm AArch64 feature support in the Rust language. Rust language scalability on AArch64 Linux systems.

### Which members of the community would benefit from your work?

Any consumer of the Rust language targeting Arm AArch64 and associated architecture.

The intent here is for Arm, the Rust Language Core Team and the Rust community to continue collaboration to maintain Arm v8.x as a Tier-1 supported Rust platform.

This has important ramifications for the uptake of Rust in safety and security critical domains such as Automotives, Infrastructure, HPC, IoT.

### Is the code that you’re going to run 100% open source? 

Yes.

https://github.com/rust-lang/rust

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Yes. The Rust Language needs to introduce and extend support for all Arm architecture versions.

### What infrastructure (computing resources and network access) do you need?

- Preferable option: Dual Socket (Mt. Jade): 160 Cores, 256GB RAM (16 x 16GB), 2 x 1 TB NVMe U.2 SSD, 1x 25GbE NIC system
- Fallback option: Single Socket (Mt. Snow): 80 Cores, 128GB RAM (8x 16GB), 1TB NVMe U.2 SSD, 1x 25GbE NIC
- Short-term support
 
The request is to provide a bare-metal AArch64 instance which will be maintained by Arm and the Rust-lang team collaborating on the CI aspects and beyond.

As such - no long term support need is currently envisioned.

The instance itself should be required for a long term though (1 year +) and between Arm and the Rust-lang team we will periodically share how the instance is impacting the progression/improvement of Rust on AArch64. We have high confidence that access to this instance will be positively and significantly impactful for Rust on AArch64.

### Describe / Name the continuous integration (CI) system for this project.

Github Actions.

These machines will be primarily used for CI.

CI dashboard URL (example): https://github.com/rust-lang-ci/rust/actions/runs/917421534

### Please state your contributions to the open source community and any other relevant initiatives.

Robin:

Misc contributions over the years to the Android Linux kernel, FreeBSD kernel, u-boot and misc boot-chains. Robin was the OS power and performance lead at Arm Cambridge and oversaw the implementation of Linux kernel support for Arm's big.LITTLE designs and Linux's Energy Aware Scheduling framework among others. In his spare time Robin hacks on Redox OS (a microkernel based stack written in Rust) to port it to AArch64.

Pietro:

Pietro is the Rust Infrastructure Team Lead and a key Rust Core Team Member. 'nuff said! :) He also was the CI wiz who played a key role in getting AArch64 Linux to reach Tier-1 Rust supported platform status.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers (Mt Snow) ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. 
We will be looking forward for your feedback / experience on new servers.
