### ISSUE TITLE
Request to upgrade a previously provided AArch64 bare-metal instance for the wasmtime project

### ISSUE THREAD

**Issue by raw-bin** [WorksOnArm/cluster#273]
Kind attention: @vielmetti, @alexcrichton, @tschneidereit, @awafaa

### Name, email, company, job title

- Robin Randhawa, robin.randhawa@arm.com, Arm, Technical Director for System Software Architecture

- Alex Crichton, alex@crichton.co, Fastly, Senior Staff Engineer

### Project Title and description

The [wasmtime](https://wasmtime.dev/) run-time for [WebAssembly (WASM)](https://webassembly.org/) and [WASI (modular system interface for WebAssembly)](https://github.com/WebAssembly/WASI).

### Describe your use case for these machines

Wasmtime CI/CD pipelines. Arm AArch64 feature support in WASM.

### Which members of the community would benefit from your work?

Any consumer of the WebAssembly cluster of technologies targeting Arm AArch64 and associated architecture. 

The intent here is for Arm and the WASM communities to collaborate and make Arm v8.x a best in class target architecture for WASM.

This has important ramifications for multiple application domains from the edge to the cloud. A good overview of how these technology clusters are beneficial for safety and security is available [here](https://hacks.mozilla.org/2019/11/announcing-the-bytecode-alliance/).

### Is the code that you’re going to run 100% open source? 

Yes.

https://github.com/bytecodealliance/wasmtime/
and also: https://github.com/WebAssembly

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Yes. WASM needs to introduce and extend support for all Arm architecture versions.

### What infrastructure (computing resources and network access) do you need?

- Preferable option: Dual Socket (Mt. Jade): 160 Cores, 256GB RAM (16 x 16GB), 2 x 1 TB NVMe U.2 SSD, 1x 25GbE NIC system
- Fallback option: Single Socket (Mt. Snow): 80 Cores, 128GB RAM (8x 16GB), 1TB NVMe U.2 SSD, 1x 25GbE NIC
- Short-term support

The request is to provide a bare-metal AArch64 instance which will be maintained by Arm and the WASM team (represented presently by Alex Crichton) collaborating on the CI aspects and beyond.

As such - no long term support need is currently envisioned. 

The instance itself should be required for a long term though (1 year +) and between Arm and the WASM team we will periodically share how the instance is impacting the progression/improvement of WASM and WASI on AArch64. We have high confidence that access to this instance will be positively and significantly impactful for WASM and WASI on AArch64.

### Describe / Name the continuous integration (CI) system for this project.

Github actions.

The machine will primarily but not exclusively be used for CI.

### Please state your contributions to the open source community and any other relevant initiatives.

Robin: 

Misc contributions over the years to the Android Linux kernel, FreeBSD kernel, u-boot and misc boot-chains. Robin was the OS power and performance lead at Arm Cambridge and oversaw the implementation of Linux kernel support for Arm's big.LITTLE designs and Linux's Energy Aware Scheduling framework among others. In his spare time Robin hacks on Redox OS (a microkernel based stack written in Rust) to port it to AArch64.

Alex: 

Alex is a former member of the Rust Language core team and has his fingerprints on pretty much all of Rust and WASM! No kidding, Google it!

**Comment by pgmwoa** [comment]
We are in the process of getting the servers (Mt Snow) ready for you. You will get an email as soon as the hardware is reserved and ready for use.
