### ISSUE TITLE
CZ.NIC Labs - Works On Arm Sponsored

### ISSUE THREAD

**Issue by tomaskrizek** [WorksOnArm/cluster#274]
### Name, email, company, job title

Tomas Krizek tomas.krizek@nic.cz
CZ.NIC
Research Software Engineer

Daniel Salzman daniel.salzman@nic.cz
CZ.NIC
Research Software Engineer

Requesting on behalf of our organization, [CZ.NIC Labs](https://www.nic.cz/page/2049/projects-for-professionals/).

### Project Title and description

CZ.NIC Labs develops multiple free and open-source projects. These are the most notable ones which would get the greatest benefit from ARM test coverage.

- [Knot DNS](https://www.knot-dns.cz/) is a high-performance authoritative DNS server that is used world-wide by various top-level domain operators, root servers etc.
- [Knot Resolver](https://www.knot-resolver.cz/) is a recursive DNS server which is used by ISPs as well as home users often using armv7 or armv8 architectures (e.g. our hardware routers [Turris](https://www.turris.com/en/))
- [BIRD](https://bird.network.cz/) is a popular internet routing daemon that powers parts of the internet backbone. 

### Describe your use case for these machines

We'd like to make the machines part of our GitLab CI infrastructure to allow us to run automated builds and test suites on ARM.

### Which members of the community would benefit from your work?

Anyone who wishes to use our software on ARM architectures would benefit from greater upstream test coverage. If we can catch possible issues early, we can provide a higher quality releases and packages.

### Is the code that you’re going to run 100% open source?

Yes.

- https://gitlab.nic.cz/knot/knot-dns
- https://gitlab.nic.cz/knot/knot-resolver
- https://gitlab.nic.cz/labs/bird

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No

### What infrastructure (computing resources and network access) do you need?

We'd like to run our test coverage on every commit. We also plan to share these resources for all our FOSS projects that are interested in ARM test coverage - ideally, the gitlab runner would be able to handle 8-16 jobs in parallel.

Some of our extended test suites would require root access and shell executor to allow us to use network namespaces to simulate various network environments.

We'd also be interested in the possibility to run and test on ARMv7 as well as ARMv8.

This is a request for long term, ongoing support. In the future, it might be possible we'd acquire our own ARMv8 hardware.

### Describe / Name the continuous integration (CI) system for this project.

GitLab CI Runner

> Will these machines be exclusively used for CI purposes?

Yes

> Please share a public URL of the CI dashboard (if applicable).

- https://gitlab.nic.cz/knot/knot-dns/-/pipelines
- https://gitlab.nic.cz/knot/knot-resolver/-/pipelines
- https://gitlab.nic.cz/labs/bird/-/pipelines

### Please state your contributions to the open source community and any other relevant initiatives.

Our organization, CZ.NIC, the .cz TLD operator, develops multiple FOSS projects in our Labs department. We strive to create high-quality RFC-conforming software and contribute back to both the open-source and technical communities. Many of our colleagues are active members of the IETF and have contributed to various RFCs. We also host and organize technical conferences and share our expertise in these and other venues.

My personal contributions include development, testing and packaging of various projects such as Knot Resolver, Knot DNS, DNS Shotgun, dnsjit or respdiff. I'm also a Fedora contributor where I maintain a few packages, including the mentioned projects as well as some of their dependencies.

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA Program. The program team reviewed your ticket and the decision has been communicated via email, dated July 1, 2021.

**Comment by pgmwoa** [comment]
Closing the ticket as no response received.
