### ISSUE TITLE
Debian - Works On Arm Sponsored

### ISSUE THREAD

**Issue by zumbi** [WorksOnArm/cluster#275]
### Debian GNU/Linux

Debian GNU/Linux, is a Linux distribution composed of free and open-source software, developed by the community-supported Debian Project. www.debian.org

### Describe your use case for these machines

I would like to use Mt. Jade system to power up the backends for Debian CI (ci.debian.net) and Salsa CI (salsa.debian.org) and if needed for any other relevant service used by the Debian Project.

### Which members of the community would benefit from your work?

All Debian ecosystem and derivatives will benefit from this work as this is an on-going effort to enable developers and power part of the Debian QA infrastructure.

### Is the code that you’re going to run 100% open source? 

Yes, the code is 100% open source:
- https://salsa.debian.org/ci-team/debci
- https://salsa.debian.org/salsa-ci-team

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details

ARMv8.2 is not needed.

### What infrastructure (computing resources and network access) do you need?

This is a request for continuous ongoing support.

### Describe / Name the continuous integration (CI) system for this project.

The Debian continuous integration (debci) is an automated system that coordinates the execution of automated tests against packages in the Debian system. debci will continuously run autopkgtest test suites from source packages in the Debian archive.

The Salsa CI Team work aims to improve the Debian packaging lifecycle by providing Continuous Integration fully compatible with Debian packaging.

Will these machines be exclusively used for CI purposes? YES

- https://ci.debian.net/status/

### Please state your contributions to the open source community and any other relevant initiatives.

Directly related, I am part of Debian System Administrators (DSA) team, supporting the Debian infrastructure.
Indirectly, I am part of Software in Public Interest (SPI) board, legal entity that gives support to the Debian Project. I am part of Debian Treasurer as well as member of several package maintenance teams.

## Important reminders and logistics

I have read and understood those reminders.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers
