### ISSUE TITLE
Request to upgrade a previously provided AArch64 bare-metal instance for the haskell.nix project

### ISSUE THREAD

**Issue by angerman** [WorksOnArm/cluster#276]
### Name, email, company, job title

Moritz Angermann moritz.angermann@gmail.com, Tools Team Lead

### Project Title and description

[haskell.nix](https://github.com/input-output-hk/haskell.nix) is a very flexible solution to build haskell project with nix. This project was conceived to allow different teams using different package setups (either cabal or stack) to build their projects seamlessly in nix, while also providing all the infrastructure to cross compile projects. 

### Describe your use case for these machines

The machine will be used to pre-build aarch64 compiler, and run build validation across whole haskell package sets (e.g. stackage snapshots).  Subsequently providing pre-built artifacts for use.

The machine will further assist me in debugging and improving the AArch64 Native Code Generator in the Glasgow Haskell Compiler, which was finally [merged for the upcoming GHC 9.2 release just three (3) weeks ago](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5884)

### Which members of the community would benefit from your work?

Everyone who uses nix and haskell, and specifically everyone who uses those on arm. 

### Is the code that you’re going to run 100% open source? 

Yes. [haskell.nix](https://github.com/input-output-hk/haskell.nix) is fully open source. So is [GHC](https://gitlab.haskell.org/ghc/ghc).

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not sure yet. We might see if we can significantly improve the Native Code Generator with 8.2 features.

### What infrastructure (computing resources and network access) do you need?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe / Name the continuous integration (CI) system for this project.

- Mt Snow: 128GB (8x 16GB), 1TB SSD U.2, 1x 25GbE NIC

### Please state your contributions to the open source community and any other relevant initiatives.

- Initial author of haskell.nix
- Author of the static in-memory aarch64 linker for ELF and MachO in the Glasgow Haskell Compiler.
- Author of the Glasgow Haskell Compilers AArch64 Native Code Generator for Linux and macOS.

## Important reminders and logistics

I have read and understood those reminders.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
