### ISSUE TITLE
Linuxkit - Works On Arm Sponsored - request upgrade for existing

### ISSUE THREAD

**Issue by deitch** [WorksOnArm/cluster#277]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

**Note:** This is a replacement for an existing one, as suggested and requested by Manisha Nigam.

### Name, email, company, job title

Maintainers: 

* Avi Deitcher, Aptimia
* Justin Cormack, Docker
* Rolf Neugebauer, AWS
* David Scott, Docker
* Dave Tucker, RedHat

### Project Title and description

LinuxKit, a toolkit for building custom minimal, immutable Linux distributions.

### Describe your use case for these machines

We build linuxkit for aarch64/arm64, including the actual OSes and all of the packages. We use our arm builders to build packages and to build OS images.

### Which members of the community would benefit from your work?

Dozens of downstream projects, open and closed, that build immutable custom OSes based on LinuxKit

### Is the code that you’re going to run 100% open source? 

Yes

Provide the URLs where it is located, or a Git repository. https://github.com/linuxkit/linuxkit

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

Not sure

### What infrastructure (computing resources and network access) do you need?

Single node with general network access

### Describe / Name the continuous integration (CI) system for this project.

GitHub actions

Will these machines be exclusively used for CI purposes?

No, they also will be used by maintainers to test and/or build images

### Please state your contributions to the open source community and any other relevant initiatives.

Brag a little bit about yourself, please!

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
