### ISSUE TITLE
Apache Mesos - Works On Arm Sponsored

### ISSUE THREAD

**Issue by janisz** [WorksOnArm/cluster#278]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Name | Tomasz Janiszewski
---------|-------------------------------
Email | janiszt [at] gmail [dot] com 
Twitter | [@janiszt](https://twitter.com/janiszt)
Company | RedHat
Job Title | Software Engineer

### Project Title and description

[Apache Mesos](http://mesos.apache.org/) is a project to manage computer clusters. 
It can be compared to a Linux kernel but for Datacenter. 
Mesos is an abstraction layer over resources available in the cluster.

### Describe your use case for these machines

We need a CI for ARM and a place to build packages.
From time to time this machine could be used to debug issues

### Which members of the community would benefit from your work?

End users can run Mesos on Arm and hopefully easily download official packages for ARM-based distributions (there are no official packages at the moment but there is a plan to do it – [see](https://youtu.be/m7WzKia68Rg)). Mesos community will get feedback about patches compatibility with ARM64. 

Recent dev mailing list thread about [ARM CI](https://lists.apache.org/thread.html/r720d112407684bb6eace93bf956b069fb66b8987e7198f469a7f0913%40%3Cdev.mesos.apache.org%3E)

### Is the code that you’re going to run 100% open source?

✔️ Yes, Mesos is top level [Apache Foundation](https://apache.org/) project. It is licensed under [Apache License 2.0](https://github.com/apache/mesos/blob/master/LICENSE). 
Source code is publicly available at https://github.com/apache/mesos/ (mirrored from git://git.apache.org/mesos.git)

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No

### What infrastructure (computing resources and network access) do you need?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe / Name the continuous integration (CI) system for this project.

Will these machines be exclusively used for CI purposes?

Yes
https://builds.apache.org/job/Mesos/job/Mesos-Buildbot/buildTimeTrend

### Please state your contributions to the open source community and any other relevant initiatives.

My personal GitHub at @janisz lists most of the projects I'm involved with. I'm the lead of [allegro/bigcache](https://github.com/allegro/bigcache) and [allegro/marathon-consul](https://github.com/allegro/marathon-consul). I also contribute to [Apache Mesos](https://github.com/apache/mesos/commits?author=janisz)

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by janisz** [comment]
Previous request https://github.com/WorksOnArm/cluster/issues/9 (accepted)

**Comment by pgmwoa** [comment]
Thanks for your interest in WoA Program. The program team reviewed your ticket and the decision has been communicated via email, dated July 1, 2021.

**Comment by pgmwoa** [comment]
Closing the ticket as no response received.
