### ISSUE TITLE
Bincrafters C/C++ Library Packaging

### ISSUE THREAD

**Issue by solvingj** [WorksOnArm/cluster#28]
### Name, email, company, job title
Jerry Wiltse, jerrywiltse gmail, bincrafters.io, senior packager
Rene Rivera, grafikrobot gmail, senior packager

### Project Title and description
Bincrafters is an OSS team who work collectively, and use open-source CI services to precompile and package ubiquitous C and C++ libraries for windows/mac/linux.  After learning about WorksOnArm CI service, we feel it would be extremely valuable for both of our projects to add one or more ARM builds to the CI for our packages. 

For more information on our team and efforts, please see our blog : https://bincrafters.github.io/about/

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Each package we license is open-source.  The libraries use a variety of licenses, and we include the licenses in each package in accordance with the applicable license terms. 

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
TBD, we would likely try to be as conservative with the services which are available. 

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

We are looking for a long-term engagement.  We are currently engaged in discussion with two potential corporate sponsors who we will announce when confirmed.  Chances are very high that any costs of CI will be pledged by these sponsors.  Additionally, we have a burgeoning community, with a number of pledges to our Patreon account for sponsoring our CI.  Regarding Patreon, we are currently aiming to enroll in and switch to OpenConsortium to manage all contributions and payouts. 

### Please state your contributions to the open source community and any other relevant initiatives

In 5 months, the Bincrafters team has packaged over 200 C and C++ libraries for the Conan.io package manager.  The response from the C/C++/Conan community has been overwhelmingly positive on social media, slack, and at C++ conferences.  The Conan/Bintray/JFrog teams have also been highly supportive.  It seems that our service is proving highly valuable within the C/C++ community, and our support should continue to grow.

**Comment by vielmetti** [comment]
Thanks for reaching out! This is approved - we will need a list of the team members to add to the project before you provision your server.

**Comment by vielmetti** [comment]
https://www.conan.io/ is the Conan.IO package manager, for reference, and their Github is at https://github.com/conan-io/conan

**Comment by vielmetti** [comment]
Accounts invited, working with @solvingj to handle onboarding. Will call this "done" for the purposes of tracking.

**Comment by vielmetti** [comment]
Marked as "completed" per @solvingj . Good exploration of the problem space, and future work may expand this effort, depending on funding.
