### ISSUE TITLE
kubevirt/kubevirt CI - Works On Arm Sponsored

### ISSUE THREAD

**Issue by zhlhahaha** [WorksOnArm/cluster#280]
### Name, email, company, job title

Howard Zhang, howard.zhang@arm.com, Arm, senior software engineer

### Project Title and description
KubeVirt (https://github.com/kubevirt/kubevirt) is a virtual machine management add-on for Kubernetes. The aim is to provide a common ground for virtualization solutions on top of Kubernetes. Also Kubevirt is a CNCF project.

### Describe your use case for these machines
For kubevirt CI test

### Which members of the community would benefit from your work?
Currently there are a bunch of contributions for this project, and together there is a need to have the fundamental integration test and unit test publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support, and thus appeal more kubevirt developers to utilize this project.

### Is the code that you’re going to run 100% open source? 
Yes.

https://github.com/kubevirt/kubevirt

### What infrastructure (computing resources and network access) do you need?

one new Altra Mt Snow to replace the old emag

### Describe / Name the continuous integration (CI) system for this project.

prow and kubernetes

### Please state your contributions to the open source community and any other relevant initiatives.

Enable kubeVirt on ARM64 and related CI works

**Comment by zhlhahaha** [comment]
cc: @justin-he

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
