### ISSUE TITLE
google/gVisor CI - Works On Arm Sponsored

### ISSUE THREAD

**Issue by zhlhahaha** [WorksOnArm/cluster#281]
### Name, email, company, job title

Howard Zhang, howard.zhang@arm.com, Arm, senior software engineer

### Project Title and description

gVisor(https://github.com/google/gvisor) is a user-space kernel, written in Go, that implements a substantial portion of the Linux system surface.

### Describe your use case for these machines

CI test for gVisor

### Which members of the community would benefit from your work?

Currently there are a bunch of contributions for this project, and together there is a need to have the fundamental integration test and unit test publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support, and thus appeal more gViosr developers to utilize this project.
Also the google guys wants me to build an ARM CI for it.

### Is the code that you’re going to run 100% open source? 

Yes.

https://github.com/google/gvisor

### What infrastructure (computing resources and network access) do you need?

one new Altra Mt Snow to replace the old emag

### Describe / Name the continuous integration (CI) system for this project.

buildkite/pipeline

### Please state your contributions to the open source community and any other relevant initiatives.

bug fix and performance tuning for gVisor on ARM64

**Comment by zhlhahaha** [comment]
cc: @justion-he

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.
