### ISSUE TITLE
TensorFlow - Works On Arm Sponsored

### ISSUE THREAD

**Issue by yarri-oss** [WorksOnArm/cluster#284]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title
Douglas Yarrington, dyarrington@, Google, TensorFlow Team

Note that projects with two or more participants are preferred.

### Project Title and description
TensorFlow

### Describe your use case for these machines
ARMv8 CI Builds

### Which members of the community would benefit from your work?
All users of ARMv8 based TensorFlow users, both training and inferencing 

### Is the code that you’re going to run 100% open source? 
Yes, per the license at https://github.com/tensorflow/tensorflow

Provide the URLs where it is located, or a Git repository.
https://github.com/tensorflow/tensorflow

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Not Sure

### What infrastructure (computing resources and network access) do you need?
CI Build related

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe / Name the continuous integration (CI) system for this project.
Optional, Jenkins?

Will these machines be exclusively used for CI purposes?
I think so.

Please share a public URL of the CI dashboard (if applicable).
We use GitHub Actions and webhook callbacks

### Please state your contributions to the open source community and any other relevant initiatives.
We are working with Ian Chan at ARM to investigate this "Works on Arm" solution to improve ARMv8 user experience. 

Brag a little bit about yourself, please!

## Important reminders and logistics

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
Please update the project name / heading accordingly.

**Comment by yarri-oss** [comment]
@pgmwoa Sorry, done.

**Comment by pgmwoa** [comment]
Closing the ticket as they won’t be able to proceed with this for now and will only revisit sometime early next year.
