### ISSUE TITLE
Crystal Language - Works On Arm Sponsored

### ISSUE THREAD

**Issue by beta-ziliani** [WorksOnArm/cluster#286]
### Name, email, company, job title

Beta Ziliani, beta@manas.tech, Manas.Tech, Team Lead and Principal Engineer
Jonne Haß, me@jhass.eu, The Crystal Project, Core Member
Matias Garcia Isaia, mgarcia@manas.tech, Manas.Tech, Full-stack Engineer and Site Reliability Engineer
Johannes Müller, jmuller@manas.tech, Manas.Tech, Back-end Developer

### Project Title and description

The Crystal Programming Language. Fast as C, sleek as Ruby. A language for humans and computers that was born and raised at Manas.

### Describe your use case for these machines

For some while we have been unofficially supporting ARM architectures, testing our compiler in the older servers at WoA [see former ticket](https://github.com/WorksOnArm/cluster/issues/206). We are currently working full steam in supporting ARM officially, so we expect to grow the number of VMs to encompass the different targets.

### Which members of the community would benefit from your work?

We have numerous requests for supporting ARM officially, mostly for projects expecting to work in the AWS cloud or in Raspberry Pis.

### Is the code that you’re going to run 100% open source? 

Yes, and it will always be.
[The webpage](www.crystal-lang.org), [the repo](www.github.com/crystal/crystal), [the license](https://github.com/crystal-lang/crystal/blob/master/LICENSE).

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 
Not sure. We don't have this requirement at the moment.

### What infrastructure (computing resources and network access) do you need?

We are currently running 8 VMs with 8GB of RAM and 2 cores each, and in the near future we will likely double our needs. In terms of network bandwidth, our current usage is 20GB/month.

### Describe / Name the continuous integration (CI) system for this project.

We are currently using GitHub Actions for our CI (workflow)[https://github.com/crystal-lang/crystal/actions/workflows/aarch64.yml]. We will use the server just for these workflows.

### Please state your contributions to the open source community and any other relevant initiatives.

The Crystal project is an ongoing effort to provide a language that is easy to use and efficient to run. With the help of more than 400 contributors from all over the world, we reached the 1.0 status this past April. As a result, we are seeing a wide adoption of the language by different industries, as evidenced in our recent [Crystal Conf](www.crystal-lang.org/conference). There, we saw the language being used in areas such as: sciences and data processing, blockchain, machine learning, embedded devices, security, web development, and bioinformatics.

## Important reminders and logistics

_Kept for future reference_

Approved projects will be expected to provide credit back to Works on Arm
in the form of a logo display, blog post, Twitter post, news release, or
some other suitable acknowledgement.

Approved projects are subject to a 90 day review process for termination.

When resources are not required anymore or when the project ends, please add comments on this issue so that we can reuse the hardware for someone else!
In case a project goes through ownership change or key people leaving, please promptly inform the team by adding comments on this issue. Our team will maintain dialogue with  new members.

For more project information, see the following social channels:

* Twitter: [@ArmSoftwareDev](https://twitter.com/ArmSoftwareDev)
* Discord, [@Arm Developer Ecosystem](https://discord.gg/H5ETM7C)
* Arm Developer Community, [Infrastructure Solutions forum](https://community.arm.com/developer/f/infrastructure-solution)

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.

**Comment by shipra-ps** [comment]
Hi Team,

I have sent one important communication to you over email on 10th Jul'24. Request you to check that and acknowledge.

Regards,
Shipra Snehi
WoA Program Team
