### ISSUE TITLE
NixOS Community Aarch64 Host

### ISSUE THREAD

**Issue by grahamc** [WorksOnArm/cluster#30]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Graham Christensen
graham@grahamc.com

along with @dezgeg

Not affiated with a company.

### Project Title and description

NixOS on Aarch64

### Which members of the community would benefit from your work?

 - RPI users
 - Embedded system builders
 - Chromebook users

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes:

 - http://github.com/nixos/nixpkgs
 - http://github.com/nixos/nix

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Right now, Packet.net already provides one Type 2A for hydra.nixos.org's current build cluster However, NixOS's security model precludes granting community members to the build cluster at this time. This means we have a wonderful, powerful build cluster... but the members of the community are relegated to testing their patches on much less powerful machines, wasting lots of their time.

At this time, we would like to have a second Type 2A which we can use to:

 - provide better build resources to our community members who are committed to providing proper Aarch64 support to NixOS and Nixpkgs. Ideally, this would be longer term.
 - operate a @grahamcofborg test node, which is run on pull requests (see: https://github.com/NixOS/nixpkgs/pull/32289#pullrequestreview-81146265)

### Please state your contributions to the open source community and any other relevant initiatives

 - I founded the NixOS security team
 - develop / operate the NixOS PR checking infrastructure
 - currently operate the hydra.nixos.org aarch64 builder and help operate the darwin builders.

Dezgeg contributed mainline kernel patches to the tegra ARM soc several years ago (when working at nvidia) and sends nowadays sends stuff to the U-Boot bootloader as well on free time.

**Comment by vielmetti** [comment]
Looks great! Should have this going this week.

**Comment by vielmetti** [comment]
I think we can do this just by adding another machine to the "NixOS Sponsored Builds" project with the UUID ending with 0094.

**Comment by grahamc** [comment]
Alright! Thanks, @vielmetti. I'll get started on setting this up.

**Comment by vielmetti** [comment]
Up and running, so closing this issue. As ever, contact us if there are questions.

**Comment by vielmetti** [comment]
Adding monitoring info:

* https://status.nixos.org/prometheus/
* https://status.nixos.org/grafana/

**Comment by grahamc** [comment]
NixOS's community builder has been a real help. We also have other Aarch64 hardware for the build farm at hydra.nixos.org. Our build and release process requires every job scheduled to complete at least one attempt before the release can occur. We have noticed aarch64 is often delaying release, because of less available resources when compared to x86_64-linux. Adding more processing power to this would help us release more quickly. As we discussed, we're open to collaborating in many ways :). Thank you!

**Comment by vielmetti** [comment]
@grahamc -

I have added one of our Qualcomm Centriq servers to your account. This will be the first time you have touched this particular hardware, so I'll leave the item open and "in progress".

**Comment by grahamc** [comment]
Indeed! This evening I added a second instance, an Ampere system - 32 cores at (iirc) 3.3ghz and, well, the graphs agree!

**Comment by grahamc** [comment]
See https://twitter.com/grhmc/status/1091533108015452160?s=21 for pictures I tried to attach. 

Graphs at status.nixos.org
