### ISSUE TITLE
Kata Containers CI 

### ISSUE THREAD

**Issue by jmknyc06** [WorksOnArm/cluster#31]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
James Kulina, 
james@hyper.sh, 
Hyper.sh, 
COO

Note that projects with two or more participants are preferred.

### Project Title and description
Kata Containers 
Virtualized container runtime project aimed at securing containers through use of hypervisor and hardware enforced isolation. 

### Which members of the community would benefit from your work?
Current members of open source Kata Containers project include: Intel, Hyper.sh, ARM, Google, MSFT, Tencent, CoreOS and many others. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes. 
https://github.com/kata-containers

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Require access to ARM based Type 2A servers. Still in planning phase of how many, but starting off one or two should be sufficient. 

The Kata Containers project is managed by OpenStack Foundation. 
https://katacontainers.io/

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Please state your contributions to the open source community and any other relevant initiatives
Hyper.sh has been very active in the open source community, contributing to OpenStack, Docker, Kubernetes, Mesos and other infra related projects. 

Brag a little bit about yourself, please!

**Comment by vielmetti** [comment]
@jmknyc06 - 

Please create a new project on your existing Packet account, and then email me (ed@packet.net) with the project UUID so that I can mark it as part of Works on Arm and handle the accounting for it.

Let's schedule a short kickoff meeting for early next week (Monday afternoon or Tuesday any time) so we can sort out goals and requirements and any questions you might have.

If you have a preferred communication path (Slack, IRC, etc) let me know. There is a #worksonarm channel on Freenode IRC gatewayed to the Packet community Slack that's good for community work.

Glad to see this going forward!

**Comment by jmknyc06** [comment]
@vielmetti Hi Ed - We created new project. 
UUID:  49485b34-076f-4051-a42f-2775523fbc3d

**Comment by vielmetti** [comment]
Project created, last digits bc3d. Kickoff meeting scheduled for Monday.

**Comment by vielmetti** [comment]
Kickoff call all OK, ready to go.

**Comment by vielmetti** [comment]
https://github.com/kata-containers/ci/issues/30 is an update to the CI infrastructure.

**Comment by vielmetti** [comment]
https://github.com/kata-containers/ci/issues/42 also addresses the Kata Containers CI infrastructure, which is under active development. Still keeping this issue open.

**Comment by vielmetti** [comment]
Reopen to reflect that work is still going on in the Kata Containers CI infrastructure, with Zuul.

**Comment by vielmetti** [comment]
Reopen to reflect a continued interest in this effort.

**Comment by vielmetti** [comment]
Relevant thread at https://github.com/kata-containers/ci/issues/6

**Comment by grahamwhaley** [comment]
Hi @vielmetti,
 as discussed on https://github.com/kata-containers/ci/issues/6#issuecomment-413972071, I'm working on adding metrics CI ability to Kata Containers, and would like to utilise the packet.net resources.
Current metrics CI framework is set up to run with x86. I think we can get PR coverage running with a single Packet t1.small.x86, and then would likely need another one to cover master branch metrics tracking. I will caveat that the 8G of RAM on those might be a bit small for some of the metrics, but I think we can only find out by trying it...
Once that is proven stable, and the ARM QA CI is up and stable, we can also work on enabling metrics CI on ARM hardware.

I've created myself a packet.net account user `gwhaley`
/cc help@packet.net

Many thanks.

**Comment by vielmetti** [comment]
@grahamwhaley just to close out the loop here, we are set up under the CNCF cluster via https://github.com/cncf/cluster/issues/83 to provide a server for CI for Kata.
