### ISSUE TITLE
OPNFV Container4NFV CI 

### ISSUE THREAD

**Issue by songsh08** [WorksOnArm/cluster#32]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Song Zhu
song.zhu@arm.com
Arm
Principal Software Engineer

Note that projects with two or more participants are preferred.

### Project Title and description

OPNFV Container4NFV
Project “Container4NFV” works on the infrastructure of VNF-s partly or totally composed of containers. The project makes an analysis on the architecture options how to co-locate container and VM based VNF-s, provides a gap analysis against prominent open source projects in the domain and creates a set of OPNFV installation scenarios which enable the deployment of VNF-s partly or totally composed of containers.

### Which members of the community would benefit from your work?

Current members of open source OPNFV Container4NFV project include: China Mobile, Arm, NXP, Huawei, Ericsson, Nokia, ZTE, Intel.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes.
https://github.com/opnfv/container4nfv

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Require access to Arm based servers to run CI for OPNFV Container4NFV  test scenarios. One or two servers should be sufficient. We are planning to upstream our work to Container4NFV project aligning with OPNFV Fraser release. 

Open Platform for NFV (OPNFV) is a collaborative project under the Linux Foundation.
https://www.opnfv.org/

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Please state your contributions to the open source community and any other relevant initiatives

Our team has been very active in networking Open Source Software projects, contributing to OPNFV, DPDK, ODP, VPP and other projects.

Brag a little bit about yourself, please!

**Comment by vielmetti** [comment]
Hi @songsh08  -

Please list a second person who will have access to the Packet project that you will use for this effort. 

What date is the Fraser release scheduled for? I see on https://wiki.opnfv.org/display/SWREL/Fraser that there's an April 1 2018 target.

Which CI system will you be running? That sometimes presents its own questions that need to be answered.

**Comment by maiil22song** [comment]
Hi, @vielmetti 

Second person who will have access to the Packet project:
Yibo Cai
yibo.cai@arm.com
Arm
Staff Software Engineer

Our objective is to run our test scenarios in OPNFV Jenkins CI before March 2, 2018. This is required by OPNFV Fraser MS5 https://wiki.opnfv.org/display/SWREL/Fraser.

The link for OPNFV CI: https://build.opnfv.org/ci/.

**Comment by vielmetti** [comment]
Instructions sent by email - once you get accounts set up, email me the project UUID.

**Comment by vielmetti** [comment]
Apologies for delays in account setup, this should be all set to go and marked as part of the new portal's "Works on Arm" organization. That transition happened this morning. 

Our past experience suggests that Jenkins installs don't pose any unusual problems.

**Comment by vielmetti** [comment]
Hi @songsh08 @maiil22song - can I get a status update on this project? We have several projects now using DPDK and it would be good to understand where things are.

**Comment by vielmetti** [comment]
Also @songsh08 @maiil22song what CI system are you using, and is there a public status page that reflects the state of the builds?

**Comment by vielmetti** [comment]
Terrific @songsh08 @yibo-cai - I will mark this as closed since the CI system is fully up and running and you're getting successful builds!

**Comment by vielmetti** [comment]
Reopening to request a project status update.

**Comment by vielmetti** [comment]
CI systems are now

CI/CD jobs for Container4NFV on Arm:
- https://build.opnfv.org/ci/view/container4nfv/job/container4nfv-k8-multus-nofeature-noha-virtual-daily-master/
- https://build.opnfv.org/ci/view/container4nfv/job/container4nfv-k8-multus-nofeature-noha-virtual-daily-fraser/
- https://build.opnfv.org/ci/view/container4nfv/job/container4nfv-k8-sriov-nofeature-noha-virtual-daily-master/
- https://build.opnfv.org/ci/view/container4nfv/job/container4nfv-k8-sriov-nofeature-noha-virtual-daily-fraser/
