### ISSUE TITLE
Request to use armv8 to test GJS and John the Ripper

### ISSUE THREAD

**Issue by claudioandre** [WorksOnArm/cluster#33]
### ID

* Claudio André, claudioandre.br at gmail.com, OSS contributor at GNOME GJS and John the Ripper
  * Software Engineer at Lactum

Working on:
  * GNOME GJS:  based on Mozilla Spidermonkey javascript engine, it powers GNOME Shell, Polari,
GNOME Documents, and many other apps.
  * John the Ripper: OSS password auditing software (I already package this software to armhf and aarch64 using a Canonical build server).

### Which members of the community would benefit from your work?
* I'm willing to do some testing/CI using your hardware. I'm already doing CI for x86 using Travis and AppVeyor. I would like to improve this situation with more archs. 
* I was able to find bugs using Travis CI. Since GNOME software is in use by millions of users, a lot of people could benefit from this work.

Both projects I'm working on are 100% open source.
* https://gitlab.gnome.org/GNOME/gjs
* https://github.com/magnumripper/JohnTheRipper

### What infrastructure do you need? (see: https://www.packet.net/bare-metal/)?
* Only TYPE 2A with docker and access to ordinary sites: GitHub, main distros, ... 
* I mean, Travis CI offers x86_64 to me. I'm interested in doing what I can do using Travi,s but using a real ARM machine.

* Let us know if you need support.
  * If you guys have a CI (Jenkings, Buildbot, ...) installed, I can use it to do CI (e.g., once a week, if limited), I just need to read your instructions.
  * If this is more like a build farm (as GCC build farm), I'll need an SSH account on a machine with docker installed (to be able to test all target distros). Plus the rules.

### The GNOME foundation might be interested in accessing your ARM servers.

* GNOME is moving to GitLab. I'm involved in developing the CI tests in the new platform. 

* BTW: is it possible to install GitLab Runner (x86 and/or ARM) in your servers? If you do so and register it in the GNOME upstream, you will became the official hardware provider for ALL CI done by the GNOME modules [1]. 
* That will be impressive. GNOME only has **one** x86 server attending for CI right now.

My last point: just forget everything I wrote above. Could you donate hardware to do CI for the GNOME foundation? They need it. Read more in https://gitlab.gnome.org/GNOMEInfrastructure/GitLab/issues/1

[1] not all modules migrated to gitlab at this time.

**Comment by vielmetti** [comment]
Hi, we've had several requests for GNOME resources, and I've added to an issue in the GNOME repo to help coordinate.

https://gitlab.gnome.org/Infrastructure/GitLab/issues/1
