### ISSUE TITLE
ARM CI support for pyFFTW

### ISSUE THREAD

**Issue by hgomersall** [WorksOnArm/cluster#34]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Henry Gomersall; heng@smartacoustics.co.uk

Note that projects with two or more participants are preferred.

### Project Title and description
pyFFTW - a pythonic interface to FFTW, the fast FFT library.

### Which members of the community would benefit from your work?
Scientists, engineers, Python developers that want to use FFTW from Python.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
[Yup.](https://github.com/pyFFTW/pyFFTW/)

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
What we really want is to run CI of pyFFTW on linux on ARM with magic hooks to github (essentially Travis CI on ARM). Not sure what infrastructure (software or hardware) is best for this, though I imagine the more resources available the faster it would run.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.
This is a long term project.

### Please state your contributions to the open source community and any other relevant initiatives
Several of my [own projects](https://github.com/hgomersall?tab=repositories) in python signal processing and FPGA development, and contributions to other projects in those areas. A Stackoverflow score of [4861](https://stackoverflow.com/users/709852/henry-gomersall).

**Comment by vielmetti** [comment]
Henry - 

We're not quite at the point where we have a Travis CI equivalent for Arm, though that's something of active interest.

**Comment by hgomersall** [comment]
Where are you at currently with this? Are you after input?

**Comment by vielmetti** [comment]
@hgomersall - to update you -

We have several projects underway (not ready to release just yet) that would provide the sort of infrastructure you are looking for to do automated CI on arm without the burden of setting up a complete CI system.

If you have a link to an open issue or writeup in the pyFFTW repository that describes your current CI infrastructure, I'd be happy to review that and see what kinds of alternatives we can provide.

**Comment by vielmetti** [comment]
Hold this spot for a hosted CI on Arm equivalent - I'll update when there's availability for that.

**Comment by hgomersall** [comment]
Sorry for the delay. I've been away and also super busy. We're still very keen on ARM CI whenever its available.

**Comment by vielmetti** [comment]
Thanks @hgomersall - do you think that you can make use of the new Shippable Arm CI? 

http://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture is the news release

**Comment by vielmetti** [comment]
@hgomersall - any progress to report? the stale bot alerted me to this, want to make sure we are still moving forward if there's continued interest.
