### ISSUE TITLE
Arm ML stack

### ISSUE THREAD

**Issue by vrajeshbhavsar** [WorksOnArm/cluster#36]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Vrajesh Bhavsar
vrajesh.bhavsar@arm.com
Arm
Sr. Ecosystem Manager, Machine Learning

Mark O'Connor
mark.oconnor@arm.com
Arm
Director, Machine Learning

Note that projects with two or more participants are preferred.

### Project Title and description
Arm ML stack
As discussed with Jeff Underhill

### Which members of the community would benefit from your work?
Companies developing machine learning algorithms & models

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Some examples:
http://ci.tensorflow.org/view/Nightly/job/nightly-pi-zero/lastSuccessfulBuild/artifact/output-artifacts/
https://github.com/ARM-software/ML-examples

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
TYPE 2A & it's newer variants

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

We are looking for a long term solution that allows us to keep delivering open source stacks & tutorials for ML developers looking to move to Arm. Our work will help ecosystem companies test Arm based products for machine learning.

### Please state your contributions to the open source community and any other relevant initiatives

Brag a little bit about yourself, please!

**Comment by vielmetti** [comment]
Accounts are set up, awaiting first server creation and SSH key uploads.

**Comment by vielmetti** [comment]
Noted http://www.zdnet.com/article/arm-rolls-out-project-trillium-for-edge-device-computing/

**Comment by vielmetti** [comment]
Projects are up and running, looking forward to access to testing on systems with faster cores.

**Comment by vielmetti** [comment]
Reopen to determine current status.

**Comment by vielmetti** [comment]
OK to reclaim this infra and close out this project.

**Comment by vielmetti** [comment]
This project has been closed.
