### ISSUE TITLE
Requesting CI/CD resources for seastar and scylladb

### ISSUE THREAD

**Issue by avikivity** [WorksOnArm/cluster#37]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Avi Kivity (@avikivity), avi@scylladb.com, ScyllaDB, CTO

Note that projects with two or more participants are preferred.

### Project Title and description
Seastar - high performance I/O framework for C++, targeting highly parallel network, disk, and multicore applications
ScyllaDB - high performance NoSQL database, written using the Seastar framework

### Which members of the community would benefit from your work?
Users of Seastar and ScyllaDB who wish to run on ARMv8 platforms.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

100% open source

https://github.com/scylladb/seastar
https://github.com/scylladb/scylla

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Long-term CI. We'd need at least 8 cores and 32GB to be able to build and run tests (more is preferable, or course).

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Please state your contributions to the open source community and any other relevant initiatives

Brag a little bit about yourself, please!

I am the ex-maintainer and original author of the Linux KVM project, and a current maintainer and author of Seastar and Scylla.

**Comment by vielmetti** [comment]
Up and running (with Jenkins) so closing.
