### ISSUE TITLE
2A instances for Ubuntu Containers project

### ISSUE THREAD

**Issue by morphis** [WorksOnArm/cluster#38]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Simon Fels <simon.fels@canonical.com>, Canonical, Technical Architect

### Project Title and description

Ubuntu Containers

### Which members of the community would benefit from your work?

n/a

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

n/a

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Two type 2A servers

### Please state your contributions to the open source community and any other relevant initiatives

n/a

**Comment by vielmetti** [comment]
Up and running, so closing.
