### ISSUE TITLE
ARM CI for Julia

### ISSUE THREAD

**Issue by ViralBShah** [WorksOnArm/cluster#39]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Viral Shah (@ViralBShah)
viral@mayin.org
Julia Computing
CEO

Alex Arslan
alex.arslan@julialang.org (@ararslan)
NumFocus
Community Manager for Julia

Note that projects with two or more participants are preferred.

### Project Title and description

Julia - A fresh approach to numerical computing
http://julialang.org

### Which members of the community would benefit from your work?

We maintain our ARM port reasonably well, and there is a dedicated subset of the Julia community focussed on ARM.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes. http://github.com/JuliaLang/julia

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

bare-metal Type 1 would be great to have.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

We are happy setting it up ourselves, but may need help troubleshooting as we set up the CI.

### Please state your contributions to the open source community and any other relevant initiatives

I am one of the creators of Julia. Alex is a long time contributor to Julia.

Brag a little bit about yourself, please!

**Comment by vielmetti** [comment]
approved and ready to go

**Comment by vielmetti** [comment]
There's a request for 32-bit Arm infrastructure noted as well.
