### ISSUE TITLE
Proposal: Kubernetes end to end testing

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#4]
* Proposal: Kubernetes end to end testing
* Contacts: Lucas Käldström (Luxas Labs), Ed Vielmetti (Packet, Works on Arm)

The Kubernetes testgrid (https://k8s-testgrid.appspot.com/) is a dashboard endpoint for federated testing for Kubernetes. It provides a single screen from which a series of independent test efforts report results on their Kubernetes testing.

The proposed project will initially feed data into this testgrid that is derived from end-to-end testing of Kubernetes at Packet on a single Type 2A server. The tests will exercise the following structure:

1. Run`kubeadm init` to initialize the environment 
2. Run e2e tests, as described in detail at https://github.com/luxas/k8s-federated-tests .
3. Finally `kubeadm reset` to reset the enviornment.

Hardware required is one dedicated Packet Type 2A server, at $0.50/hr ($360/mo). Funding for this effort will come from the Works on Arm project. The server will be located in a Packet data center as part of the Works on Arm pool.

In the future, this proposal envisions additional use of on-demand use of Packet resources to take advantage of Packet's lower-cost "spot market' for interruptible resources.

Results can be seen as follows: https://k8s-testgrid.appspot.com/multi-platform#periodic-kubeadm-packet-arm64

**Comment by luxas** [comment]
Described more in detail here: https://github.com/luxas/k8s-federated-testing

Do you need any more information?
I don't know how you mean this would work with this...

**Comment by detiber** [comment]
@vielmetti It looks like the testgrid URL has been changed to: https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-multi-platform#Summary

@vielmetti @luxas I'd be interested in seeing if this effort can be extended beyond just a periodic job that tests conformance with kubeadm to also run post-submit jobs that could potentially be used for blocking releases.

**Comment by vielmetti** [comment]
@detiber I see that the summary web page mentioned above has "stale" results, wonder what's up.

Would be happy to extend this effort any way we can.

**Comment by vielmetti** [comment]
This project has completed, with results published at

https://github.com/luxas/k8s-federated-tests

Please wish @luxas good luck on his exams!

**Comment by vielmetti** [comment]
Noting for some completeness that there's an arm64 test for Kubernetes that's passing right now; it's running on AWS infrastructure.

https://k8s-testgrid.appspot.com/conformance-arm#Arm64%20AWS
