### ISSUE TITLE
Instances for Ubuntu Embedded project

### ISSUE THREAD

**Issue by kubiko** [WorksOnArm/cluster#40]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Ondrej Kubik, ondrej.kubik@canonical.com, Canonical, Technical Architect

### Project Title and description
Ubuntu Embedded

### Which members of the community would benefit from your work?
IOT

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
n/a

### Please state your contributions to the open source community and any other relevant initiatives
n/a

Working on embedded Ubuntu

**Comment by vielmetti** [comment]
Approved, awaiting details in email query.

**Comment by vielmetti** [comment]
This project is now closed.
