### ISSUE TITLE
Request machine for libgomp scaling issues

### ISSUE THREAD

**Issue by zatrazz** [WorksOnArm/cluster#41]
### Name, email, company, job title
Name: Adhemerval Zanella Netto
Email: adhemerval.zanella@linaro.org
Job title: Toolchain Software Engineer

### Project Title and description
This work is part of an investigation of poor scaling of libgomp on machine with high core counts. Libomp is the internal OMP implementation provided by GCC.

### Which members of the community would benefit from your work?
Any OMP workload which aims to use GCC on large machines.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, 100% opensource. The URL for the project is https://gcc.gnu.org/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
This work is focused on ARMv8 hardware, so I will need either a TYPE 2A or a D05 machine.

### Please state your contributions to the open source community and any other relevant initiatives
I am current a GLIBC maintainer (https://www.gnu.org/software/libc/), with some experience on LLVM side as well (mostly on backend support for powerpc and aarch64) and work currently on GNU toolchain projects.

**Comment by vielmetti** [comment]
Setup in progress

**Comment by vielmetti** [comment]
All set up on a 2A2, closing this as "complete".

**Comment by vielmetti** [comment]
Requested status report.
