### ISSUE TITLE
Request ARMv8 32-bit-capable machines for LLVM buildbot continuous integration

### ISSUE THREAD

**Issue by maxim-kuvyrkov** [WorksOnArm/cluster#42]
### Name, email, company, job title
Name: Maxim Kuvyrkov
Email: maxim.kuvyrkov@linaro.org
Company: Linaro
Job title: Toolchain Tech Lead

### Project Title and description
LLVM Buildbots for AArch64 and AArch32

### Which members of the community would benefit from your work?
LLVM community relies on buildbot infrastructure (http://lab.llvm.org:8011/) for continuous integration and testing of llvm projects.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, 100% open source: http://llvm.org/ .

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
I need 2x Type 2A2 (64-core Cortex-A72) HiSilicon machines.  Cavium and Qualcomm machines support only AArch64 instruction set, and LLVM buildbots need both AArch64 and AArch32 instruction sets.  Ideally, the two machines need to be in different colos to mitigate risk of network failure or other downtime.

This is going to be a long-time allocation.

### Please state your contributions to the open source community and any other relevant initiatives

I'm a long-time open-source developer with contributions to GCC, LLVM, Binutils, Glibc, and GDB.  My team at Linaro is the owner of AArch64 and AArch32 LLVM buildbots, which we want to migrate to Packet.net hardware.

Thank you!

**Comment by vielmetti** [comment]
Maxim, 

I think this is a dup of #24 -  would you be so good as to help me coordinate by email and make sure we coordinate efforts here?

**Comment by vielmetti** [comment]
We're good here - builds are underway. Keeping #24 open to coordinate independent efforts.
