### ISSUE TITLE
HHVM enablement

### ISSUE THREAD

**Issue by rhenwood-arm** [WorksOnArm/cluster#43]
### Name, email, company, job title
Dave Estes
cestes@qti.qualcomm.com
Qualcomm
Server Software Engineer

Richard Henwood
richard.henwood@arm.com
Arm Inc
Server Software Program Manager

### Project Title and description
HHVM and AArch64
HHVM is an important server application. The aim of this work is to resolve packaging issues and explore CI/CD for HHVM on AArch64.

### Which members of the community would benefit from your work?
End users who want HHVM conveniently available on AArch64 machines.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes. The application runs on top of a GNU/Linux distribution (expected to be Debian variety in our case) and is licensed 'under the PHP and Zend licenses except as otherwise noted'
Full license details and code can be found here: https://github.com/facebook/hhvm

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
TYPE 2A - this is expected to require an initial effort to make the build and package created. Once that is complete a plan for implementing CI/CD will be created.

### Please state your contributions to the open source community and any other relevant initiatives
The expected audience for this work is both HHVM users and the Debian/Ubuntu communities.

**Comment by vielmetti** [comment]
Approved, accounts set up.

**Comment by vielmetti** [comment]
Machine provisioned.
