### ISSUE TITLE
ARM CI for freedesktop-sdk

### ISSUE THREAD

**Issue by Wetrain** [WorksOnArm/cluster#44]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Adam Jones, adam.jones@codethink.co.uk, Codethink, Open Source Software Engineer.
Javier Jardon, jjardon@gnome.org

### Project Title and description

Freedesktop-sdk

The freedesktop-sdk is a project that provides Platform and SDK runtimes for [Flatpak](https://flatpak.org/) apps and runtimes based on freedesktop modules.

We are currently a team of 5 contributors, 2 full time and 3 part time, along with over 15 people dicussing the project on Freenode over at  #freedesktop-sdk.

We are also a dependency of the Flatpak project, which has over 96 contributors and 1000s of users across multiple distros.

### Which members of the community would benefit from your work?

Currently our project is facing the issues of not being able to test merge requests, due to our ARM CI infrastructure not being able to cope with the amount of builds needed to correctly ensure our platform is working on ARM.

Flatpak apps require our run-time to be stable and up to date on all platforms, with ARM being a very important platform to support.

Gaining stable infrastructure would enable us to more quickly deliver a tested and stable product to the Flatpak team, speeding up their release cycle.

The freedesktop-sdk also gains to become more reliable as we aim to merge the SDK into one format and automate the testing/updating of packages as new versions are released upstream.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes this project is 100% free and open source, under the MIT license.

The project and code can be viewed here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We require ongoing future support in order to keep testing/patching/improvement the base runtime SDK/Platform that all Flatpak applications will be running on.

At the moment we focusing on aarch64, so would require several 2A instances, allowing us to effectively test on ARM hardware, however if this is not possible, we could try to virtualise the process.

### Please state your contributions to the open source community and any other relevant initiatives

We are currently replacing the 1.6 Freedekstop-SDK that is used by Flatpak, relieving them of a large chunk of maintenance work and creating a more robust and contributor friendly platform/SDK release, which will be used by all Flatpak applications in the future.

**Comment by vielmetti** [comment]
Hi, we've had several requests for GNOME resources, and I've contributed to

https://gitlab.gnome.org/Infrastructure/GitLab/issues/1

to help coordinate there.

**Comment by vielmetti** [comment]
Approved and account information added for Adam and Javier.

**Comment by vielmetti** [comment]
Marking as closed (account is set up), please let me know how things are going!

**Comment by vielmetti** [comment]
Reopening this because we need to allocate a new machine (in EWR1) and reclaim the existing machine (in AMS1) for inventory purposes. I'll send email.

**Comment by jjardon** [comment]
@vielmetti only to let you know: CI is up and running at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/ ; you can see pipelines running here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/pipelines

aarch64 are now our faster runners :) Thanks!

PS: Does packet have, by any chance, any aarch64 machine that is able to compile for armv7l?

**Comment by vielmetti** [comment]
@jjardon - we have a "Type 2A2" machine that also handles 32-bit armv7 builds, but inventory is tight. I'll be looking at that inventory this week to see what kind of a timeline I can provide for access.

**Comment by vielmetti** [comment]
Closing as done (at least for the moment)
