### ISSUE TITLE
Request ARMv8 32-bit-capable machines for GNU Toolchain Jenkins continuous integration

### ISSUE THREAD

**Issue by maxim-kuvyrkov** [WorksOnArm/cluster#45]
### Name, email, company, job title

Name: Maxim Kuvyrkov
Email: maxim.kuvyrkov@linaro.org
Company: Linaro
Job title: Toolchain Tech Lead

### Project Title and description

GNU Toolchain Upstream continuous integration

### Which members of the community would benefit from your work?

ARM ecosystem relies on Linaro to provide production-quality toolchains for ARM 32-bit and AArch64 architectures.  These toolchains are imported in Ubuntu and used directly by most of ARM Linux community.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, 100% open-source: https://gcc.gnu.org/, https://www.gnu.org/software/binutils/, https://www.gnu.org/software/libc/, https://www.gnu.org/software/gdb/ .

Our CI harness is open-source as well.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We need 2x Type2A2 machines to be able to run both 64-bit and 32-bit testing / CI.

Our CI is already online: https://ci.linaro.org/view/tcwg-ci/ , so we are ready to utilize both machines from the get-go.

This is going to be a long-time allocation.

### Please state your contributions to the open source community and any other relevant initiatives

I'm a long-time open-source developer with contributions to GCC, LLVM, Binutils, Glibc, and GDB. My team at Linaro has been responsible for AArch64 and AArch32 production toolchains for over 5 years.

Thank you!

**Comment by vielmetti** [comment]
Checking availability for 2A2 systems.

**Comment by vielmetti** [comment]
We'll start with 1 2A and will get the 2A2 when it's available.

**Comment by vielmetti** [comment]
Closing (we are set up).
