### ISSUE TITLE
Open CORD ARM CI

### ISSUE THREAD

**Issue by ashleeyoung** [WorksOnArm/cluster#47]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Ash Young, ash@cachengo.com, Cachengo, Inc., CEO

Note that projects with two or more participants are preferred.

### Which members of the community would benefit from your work?
The Open CORD community wishing to utilize the CORD stack on ARM devices

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/opencord/cord

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
The reference instructions for a fully virtualized CORD implementation can be found [here](https://guide.opencord.org/install_virtual.html). Basically, we need the following to test the builds (aka CD target system from the guide):
- 48GB RAM
- 12+ CPU Cores
- 200GB+ Disk space
- Globally routable IP
- Ubuntu 16.04
- Sudo account capabilities

For compiling the components, we need at least 8GB of RAM, thought 32GB would be much appreciated as the Java components are pretty demanding. 

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

This would be an ongoing project. 
### Please state your contributions to the open source community and any other relevant initiatives
I am working on porting the components from x86 to ARM for the project and for the community. I have working in open source for 20+ years in a variety of capacities. If it's NFV, SDN, or open orchestration, then I work on it in some fashion. The same goes for open source ML/DL work, these days. Despite all of that, I still insist I am a storage guy, not a networking one.
Brag a little bit about yourself, please!

**Comment by vielmetti** [comment]
Invite sent to join a Packet account.

**Comment by ashleeyoung** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIwDqjYEVrKKM7QGPwg0ZkoDMD5rDf9SYKjQ0plEmNMTHmaZuMPWS/NIPAtsa40e7cztDUIrv3ts1YFl2l7xtqf7UFdyybqlKlxcsZ5hAISGeQqYCjxb7N7VicyaByjIHujyqu1znu9vfUYqsWnsjZxDfgTvFqjqNuN2x6TtfQN9RSvELSlcAT3IHizDCbxU3jhTyJe+hUUZrziEv9u08em4CsjtGw7lBzzdqcacczhts/vGHMTu1iXHqmfTqmxAmByhlQhP8jmiH0jYEcSPJBukbgQinu1KWyx0dpWSr8qGPWRJeTuLl57noMfPokjCUb3qQG7GjnhmDBydY7RRLz ash@trinity.local

**Comment by vielmetti** [comment]
Reopen as we have a hardware issue to overcome.

**Comment by vielmetti** [comment]
New system (c1.large.arm.xda in DFW2) assigned to @ashleeyoung and it's been provisioned. Closing as substantially complete, as always if there are any issues that come up let me know.

**Comment by vielmetti** [comment]
Per a conversation with @ashleeyoung this project has completed, and the reservation has been reclaimed.
