### ISSUE TITLE
LLDB builder and tester for ARM/ARM64 Linux

### ISSUE THREAD

**Issue by omjavaid** [WorksOnArm/cluster#49]
Omair Javaid, omair.javaid@linaro.org, Linaro Ltd, Toolchain Engineer

Project: LLDB - Debugger of LLVM Toolchain infrastructure

LLDB  is default debugger on FreeBSD, MacOSx, Xcode and Android studio. We currently have no LLDB tester running LInux ARM/ARM64.

LLDB is fully open-source and part of LLVM toolchain infrastructure.
SVN Repository: http://llvm.org/svn/llvm-project/lldb/trunk
Git Clone: http://llvm.org/git/lldb.git

c1.large.arm or similar (Basically need arm64 hardware with maximum possible cores and memory. And network access ofcourse)

We need to run this buildbot and tester for as long as possible.

I am a developer tools engineer working for Linaro Ltd. I contribute to LLDB, GDB and OpenOCD debugger tools.

**Comment by vielmetti** [comment]
This slipped through @omjavaid - sorry about that, and thanks to stalebot for catching it. I'll check inventory and report back on what we can do. It sounds like single machine, perpetual use, maximum memory would be the best config.

**Comment by omjavaid** [comment]
Thanks Edward.

Single machine with max no of cores and max memory is what we need for LLDB
builder/tester.

**Comment by vielmetti** [comment]
Approved. You should have an email with instructions to get a Packet account.

When you get online please deploy a single c1.large.arm into our EWR1 data center, and let me know here when the builder is up. That's a 96-core Cavium ThunderX machine with 128GB of memory.

There's useful getting started info at https://help.packet.net/faq/onboarding/portal

**Comment by vielmetti** [comment]
We hit a snag with the Packet account system, will update when that's sorted out.

**Comment by vielmetti** [comment]
Checking in - I think we have taken care of all of the outstanding account issues. 

@omjavaid if you have a brief update that would be helpful, especially any links to public URLs for the buildbot.  thanks!

**Comment by vielmetti** [comment]
This system will be integrated into already available infrastructure, reports @omjavaid , pending return of staff from holidays.

**Comment by vielmetti** [comment]
@omjavaid can you provide a brief update? What would be particularly useful would be a pointer to a public web page that shows build status.

**Comment by omjavaid** [comment]
Hi Ed,

I apologize for all the delay in bringing up this builder/tester.

This buildbot is still not up as my manager was on holiday and we want to
integrate this machine into our buildbot system for llvm and then dedicate
it for LLDB builds and testing.

I think Maxim my manager has already sent you an email about adding him to
work on Arm LLDB buildbot project. Kindly add maxim.kuvyrkov@linaro.org to
the project "LLDB Buildbot project" if not done already.

Once integrated Buildbot will be available on http://lab.llvm.org:8011/.

I will update you once we give a specific name to this buildbot.

Thanks

**Comment by vielmetti** [comment]
We're investigating an issue with zombie processes on the ThunderX system that's being used for builds.
