### ISSUE TITLE
ARM for continuous integration of snapd

### ISSUE THREAD

**Issue by niemeyer** [WorksOnArm/cluster#51]
### Name, email, company, job title

Name: Gustavo Niemeyer
Email: niemeyer at canonical com
Job Title: Software Architect
Company: Canonical / Ubuntu

> Note that projects with two or more participants are preferred.

I'm writing on behalf of the snapd development team. We have a core team of 7 people, and 108 contributors at the moment, according to GitHub.

### Project Title and description

The snapd project is the heart that makes snap packages work.

A more detailed description is available here: https://snapcraft.io

### Which members of the community would benefit from your work?

This is project is supported and used in many Linux distributions, allowing them to install arbitrary software published by the community in the form of snap packages. The snapd daemon shipped in Ubuntu 16.04, and will also ship in Ubuntu 18.04 next month, so millions of devices depend on it.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, the project itself is available at:

* https://github.com/snapcore/snapd

Our integration infrastructure which enables us to test every single change proposal across multiple Linux distributions and multiple architectures was also created by us, and is available at:

* https://github.com/snapcore/spread

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We need one _c1.large.arm_ server, that we will work on multiplexing with virtualization so that we can get faster turnarounds for tests, a lager variety of images, support for destructive testing (destructive for the image) without the burden of maintenance in the underlying OS, and also a better utilization of its resources overall (it's quite beefy).

This is an example run, from today:

https://travis-ci.org/snapcore/snapd/builds/357070013

Travis is just controlling the job dispatching. These 2000 jobs are spread through multiple Linux distributions in about 40 machines right now, in multiple architectures. None of these are ARM, and we want to change that.

For that reason, this would be a long term on-going project.

### Please state your contributions to the open source community and any other relevant initiatives

> Brag a little bit about yourself, please!

I have a pretty wide spectrum of relevant contributions to the open source community.

You can find some of these listed here: http://labix.org

**Comment by vielmetti** [comment]
Looking forward to working with you on this - I'll send an email.
