### ISSUE TITLE
AArch64 machine for DynamoRIO testing & development

### ISSUE THREAD

**Issue by fhahn** [WorksOnArm/cluster#52]
### Name, Email, Company, Job title
Derek Bruening @derekbruening
Florian Hahn, florian.hahn@arm.com, Arm @fhahn

and the DynamoRIO contributors.

### Project Title and description
DynamoRIO -  Dynamic Instrumentation Tool Platform 

DynamoRIO is a runtime code manipulation system that supports code transformations on any part of a program, while it executes. DynamoRIO exports an interface for building dynamic tools for a wide variety of uses: program analysis and understanding, profiling, instrumentation, optimization, translation, etc. Unlike many dynamic tool systems, DynamoRIO is not limited to insertion of callouts/trampolines and allows arbitrary modifications to application instructions via a powerful IA-32/AMD64/ARM/AArch64 instruction manipulation library. DynamoRIO provides efficient, transparent, and comprehensive manipulation of unmodified applications running on stock operating systems (Windows, Linux, or Android) and commodity IA-32, AMD64, ARM, and AArch64 hardware. Mac OSX support is in progress.

### Which members of the community would benefit from your work?

DynamoRIO provides a platform to build tools using dynamic instrumentation, so anybody interested an building such tools would benefit. Tools built using DynamoRIO include:

* The multi-process cache simulator and memory address trace collection and analysis platform  drcachesim http://dynamorio.org/docs/page_drcachesim.html
* The code coverage tool drcov http://dynamorio.org/docs/page_drcov.html
* The library tracing tool drltrace  https://github.com/DynamoRIO/drmemory/tree/master/drltrace
* The memory tracing tool memtrace   https://github.com/DynamoRIO/dynamorio/blob/master/api/samples/memtrace_simple.c 
* The basic block tracing tool bbbuf https://github.com/DynamoRIO/dynamorio/blob/master/api/samples/bbbuf.c

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, the DynamoRIO source code is available under a BSD license on Github: https://github.com/DynamoRIO/dynamorio

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

For DynamoRIO testing/development a medium-size AArch64 machine would be great (8-20 cores). We already have an small AArch64 machine for CI (http://jenkins.fhahn.com:8080/), but our testing already showed that different microarchitectures can expose problems with the AArch64 port of DynamoRIO. So having as much different microarchitectures to test on would be very valuable.

We would like to use this machine primarily for continuous automated testing to complement the existing AArch64 builder. To integrate it with the existing jenkins setup, we would need ssh access.

Some of the core developers do not have easy access to AArch64 hardware, so having a machine available to do manual testing could be valuable for them. I am happy to set everything up and maintain it myself

### Please state your contributions to the open source community and any other relevant initiatives

I am an active contributor to LLVM (https://github.com/llvm-mirror/llvm/commits?author=fhahn) and also to DynamoRIO's AArch64 port (https://github.com/DynamoRIO/dynamorio/commits?author=fhahn). I also maintain the ARM and AArch64 testing infrastructure for DynamoRIO.
Brag a little bit about yourself, please!

**Comment by vielmetti** [comment]
Approved! I've set up an account for @fhahn (you should see that in your inbox) - sending separate email to make sure we are in sync on anyone else who needs direct access.

**Comment by vielmetti** [comment]
Looks like this is moving along nicely, @fhahn - if you have a project update that would be great.

https://github.com/DynamoRIO/dynamorio/issues/3002 tracks a specific issue to add aarch64 support, and the general label https://github.com/DynamoRIO/dynamorio/labels/OpSys-AArch64 tracks a set of arm64/aarch64 issues that have been opened and are being worked.

**Comment by vielmetti** [comment]
Update via @fhahn -

* https://github.com/DynamoRIO/dynamorio/labels/OpSys-AArch64
 
List of all aarch64 (arm64) issues. "DynamoRIO's AArch64 port provides basic functionality, but there is still lots of future work: better optimizations, adding complete NEON and Arm-v8.1+ support to the encoder/decoder, implement missing bits from the instrumentation API and of course fixing outstanding bugs"

* https://github.com/DynamoRIO/dynamorio/issues/3005

A specific bug that gets in the way of integration with Jenkins on the ThunderX: "exclusive store workaround fails on some AArch64 hardware with multi-block sequences" (3005)

**Comment by vielmetti** [comment]
Progress, thanks @fhahn - let me know if you're looking for an additional set of eyes on this at any point.

**Comment by vielmetti** [comment]
Reopening as this is not yet resolved.
