### ISSUE TITLE
Proxmox VE ARMv8 CI

### ISSUE THREAD

**Issue by GamerSource** [WorksOnArm/cluster#53]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Thomas Lamprecht, t.lamprecht@proxmox.com , Proxmox Server Solutions GmbH, Software Developer & Head of ARMv8 Port

I'll get help from my colleagues and highly probably also from part of our developer/user community, which asked for ARMv8 support.

Note that projects with two or more participants are preferred.

### Which members of the community would benefit from your work?

All those wanting to use Proxmox VE on the ARMv8 (aarch64) platform for virtualization and containerization, hyper converged setups.
We got various inquiries about supporting ARMv8, e.g.: https://forum.proxmox.com/threads/arm-future-of-proxmox.37991/

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, all AGPLv3: https://git.proxmox.com/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We would need:
* Debian 9 with root access to build upon
* at least 32 GB memory, 64GB or more would be great but not a necessity
* A new generation ARMv8 would be good, we have some access to a APM X-Gene 1, which deem as quite slow, in comparison to x86_64 server hardware with the same or older age. So Thunder X2 or x-gene 3 would be really great.
* at least one public IP, if possible a small IP subnet

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

We would like to get access for at least one, ideally a few (3-4) months, to test, deploy and polish most rough edges on the platform, to be able to release a first packaged, known good, version to the public (code changes will always be straight public, naturally).

### Please state your contributions to the open source community and any other relevant initiatives

We help upstream, with source code contributions, bug reporting and testing on the following projects (among others):
* LXC
* QEMU
* ZFS on Linux
* ceph
* systemd
* LVM
* Linux Kernel and it tools (e.g. iproute2)
* corosync cluster engine

We allow a lot of people a relative easy and intuitive access to virtualization, clustering, HA. Our distribution powers hundreds of thousands servers used in home labs, small/big business, cloud providers, and also government organizations.

**Comment by vielmetti** [comment]
HI @GamerSource - is there an open issue or forum post tracking this work? I know it may take some time to accomplish, but I want to make sure that there is a spot in your environment that I can look at for progress.

**Comment by vielmetti** [comment]
There is a "proxmox-arm" PPA for Ubuntu with experimental builds.

https://launchpad.net/~proxmox-arm/+archive/ubuntu/proxmox-arm

Claudiu Popescu is a named point of contact.
