### ISSUE TITLE
OpenEBS on ARM64

### ISSUE THREAD

**Issue by muratkars** [WorksOnArm/cluster#54]
### Name, email, company, job title
Murat Karslioglu, murat@openebs.io, OpenEBS/MayaData, VP Solutions
~100+ contributors, over 600k Docker pulls, ~730 on Slack.

High traction with thriving community. Around ~5000 commits.

### Project Title and description
OpenEBS - Containerized Storage for Containers
OpenEBS is an open source storage platform that provides persistent and containerized 
block storage for DevOps and container environments.

### Which members of the community would benefit from your work?
Kubernetes users running stateful workloads, ARM hardware vendors, Containerized workloads running on Cloud/Edge/Fog devices based on ARM64 architecture, Packet.net customers and broader hobbyist community

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
100% open source
https://github.com/openebs/openebs
https://github.com/openebs/maya
https://github.com/openebs/jiva
https://github.com/openebs/openebs-k8s-provisioner
https://github.com/openebs/node-disk-manager

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

CI for official project builds and test cluster

One-time support required for OpenEBS contributors and maintainers.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Please state your contributions to the open source community and any other relevant initiatives

OpenEBS also leverages and contributes back to few other projects including Kubernetes (storage functionality), Weave Scope, OpenZFS, etc.

Brag a little bit about yourself, please!
OpenEBS is great :)

**Comment by vielmetti** [comment]
Approved. Email sent with account setup details.

**Comment by vielmetti** [comment]
The open issue tracking this is https://github.com/openebs/openebs/issues/1295 - the milestone to close this issue out is successful setup of a CI/CD pipeline for arm64 for OpenEBS.

**Comment by vielmetti** [comment]
Waiting for 0.6 release of OpenEBS to drop, per https://github.com/openebs/openebs/issues/1295#issuecomment-398768482

**Comment by vielmetti** [comment]
Reopen to address a resource issue and for a periodic review.

**Comment by everflux** [comment]
Any update on this?

**Comment by vielmetti** [comment]
The tracking issue is https://github.com/openebs/openebs/issues/1295

where the latest is "added for 0.9" - suggest @everflux that you check there
