### ISSUE TITLE
 ARM CI for GNOME

### ISSUE THREAD

**Issue by jjardon** [WorksOnArm/cluster#55]
### Name, email, company, job title

- Andrea Veri, av@gnome.org
- Javier Jardon, jjardon@gnome.org

### Project Title and description

GNOME

GNOME  is a desktop environment composed of free and open-source software that runs on Linux and most BSD derivatives.[8]

GNOME is developed by The GNOME Project, part of the GNU Project.[10] The GNOME Project is composed of both volunteers and paid contributors, the largest corporate contributor being Red Hat. It is an international project that aims to develop software frameworks for the development of software, to program end-user applications based on these frameworks, and to coordinate efforts for internationalization and localization and accessibility of that software.

### Which members of the community would benefit from your work?

GNOME is the default desktop environment on many major Linux distributions including Fedora, Debian, Ubuntu, SUSE Linux Enterprise (exclusively), Red Hat Enterprise Linux, CentOS, Oracle Linux, SteamOS, Tails, and Kali Linux; it is also default on Solaris Unix.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, 100%:
- https://git.gnome.org/ in process to be moved to https://gitlab.gnome.org/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We require ongoing future support in order to keep testing/patching/improve GNOME in several architectures

It would be great if we can build on aarch64, so would require several 2A instances, allowing us to effectively test on ARM hardware. If there is any hardware available to build for armv7 that would be great

Also we are interested in x86 hardware if available as well

### Please state your contributions to the open source community and any other relevant initiatives

Javier: He is part of the GNOME Release Team since 2011. He is helping setting up the CI infra now that is much more popular with the move to gitlab
Andrea: He is the lead of the GNOME Infra Team

**Comment by ramcq** [comment]
The lightly-documented Type 2A2 is a 64-bit ARMv8 machine which is also compatible with ARMv7, it's what we use for workers on Flathub. Previously in discussions with @vielmetti he suggested GNOME would be able to make use of Packet instances on x86 if we were using it in a cross-architecture CI system to ensure that ARM and X86 platforms had an equal status (this is the WorksOnArm project after all!). :)

**Comment by vielmetti** [comment]
Thanks for the query. I'm taking inventory of our available Type 2A and Type 2A2 servers and hope to have this taken care of promptly after that.

**Comment by vielmetti** [comment]
Approved!

Please start with one or two Type 2A (Cavium ThunderX) systems, otherwise known as "c1.large.arm", in our EWR1 data center. I've sent an email about some of the rest of the access.

**Comment by ramcq** [comment]
@vielmetti Can Flathub trade a Type 2A2 with GNOME so that GNOME CI has a 32-bit ARMv7 capable box as well as aarch64? If we take a 2A we can pin all our 64-bit builds to it and use our 2A2 for all the 32-bit.

**Comment by ramcq** [comment]
(also - woohoo! thanks!)

**Comment by jjardon** [comment]
Thank you very much @vielmetti !! :)

**Comment by vielmetti** [comment]
Thanks @jjardon ! Looks like the system didn't build because of `libhangul`, and when I try to build it myself from source at https://github.com/choehwanjin/libhangul I get stuck on what seems like an infinite set of dependencies. 

If you open up an issue to track the build problems I'll follow there.

**Comment by vielmetti** [comment]
https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/37 is open now. I'll close this issue as "finished" (as the machine is up and running) and we can follow the details within GNOME of getting it to work.

**Comment by vielmetti** [comment]
GNOME is working on this branch for arm64:

https://gitlab.gnome.org/GNOME/gnome-build-meta/merge_requests/28

**Comment by vielmetti** [comment]
GNOME build https://gitlab.gnome.org/GNOME/gnome-build-meta/-/jobs/28971 passed its CI tests.

**Comment by vielmetti** [comment]
Congratulations on the funding news.

https://betanews.com/2018/05/25/mystery-donor-1-million-gnome-foundation/
