### ISSUE TITLE
armv8 testing for PowerDNS

### ISSUE THREAD

**Issue by Habbie** [WorksOnArm/cluster#57]
### Name, email, company, job title
Peter van Dijk
peter.van.dijk@powerdns.com
Open-Xchange/PowerDNS
Senior Engineer

Pieter Lexis
pieter.lexis@powerdns.com
Open-Xchange/PowerDNS
Senior Engineer

### Project Title and description
PowerDNS is a DNS server, written in C++ and licensed under the GPL. It runs on most Unix derivatives. PowerDNS features a large number of different backends ranging from simple BIND style zonefiles to relational databases and load balancing/failover algorithms. A DNS recursor is provided as a separate program.

Also, dnsdist is a highly DNS-, DoS- and abuse-aware loadbalancer.

### Which members of the community would benefit from your work?

We have at least one bug report from a dnsdist user that he cannot reproduce outside of his ARM64 box, and I expect this will happen more as ARM64 gains prevalence.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes - https://github.com/PowerDNS/pdns

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

On other architectures, we've found that some of our builds do not succeed with less than 2GB of RAM. Looking at the page, I see you don't even have machines that small, so we're not picky!

Ideally we'd like ongoing access to armv8 hardware, but being able to spin up a machine for a few hours when needed would work for us as well.. Eventually we would love to set up CI/CD for armv8.

### Please state your contributions to the open source community and any other relevant initiatives

PowerDNS has been open source for almost 20 years, with a thriving community (https://github.com/PowerDNS/pdns/graphs/contributors). Additionally, we frequently contribute patches to other open source projects.

**Comment by vielmetti** [comment]
Let's do this! There's a new project 07155a16-9096-4ee2-a305-3775a62e94f0 ("Sponsored - PowerDNS") and I've added you both to the project. Use what you need for the first phase of testing and fixing, and when you're ready to go to CI/CD, let me know and I'll fill you in on the available alternatives for that.

**Comment by Habbie** [comment]
Thanks @vielmetti!

**Comment by vielmetti** [comment]
We're up and running ! The immediate issue is https://github.com/PowerDNS/pdns/pull/6512 which looks well underway.

**Comment by vielmetti** [comment]
In some medium term future time we'll have some more flexible CI/CD resources; until then, the suggested plan is to run `buildbot` on a system.

**Comment by vielmetti** [comment]
Closing as complete for now, and @Habbie and I have been communicating through the Packet community Slack to address future work.
