### ISSUE TITLE
Proposal: AdoptOpenJDK builds for OpenJDK-based Java runtimes

### ISSUE THREAD

**Issue by tellison** [WorksOnArm/cluster#6]
### Name, email, company, job title
Tim Ellison (t.p.ellison at gmail dot com)
Senior technical staff member, IBM UK Ltd.
and
George Adams (@gdams)

### Project Title and description
**AdoptOpenJDK** - adoptopenjdk is a project that builds, tests, and distributes Java runtime binaries that are based upon the open source [OpenJDK project](http://openjdk.java.net).

The project has an established Jenkins continuous integration farm that provides software builds across a number of CPU/OS combinations, and testing of function and application-level correctness.  The project distributes the resulting binaries via [its website](http://www.adoptopenjdk.net) that is a portal for high-quality OpenJDK binaries.

### Which members of the Works on Arm community and/or end-users would benefit from your work?
ARM is an important platform for Java users, representing a significant community of application end-users.  It remains important for Java to continue working on ARM, and by utilizing the AdoptOpenJDK infrastructure the project is able to provide prompt feedback to the language developers about the impact to ARM support and performance.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, the delivered code, tests and build systems themselves are open source at https://github.com/AdoptOpenJDK.  There is a minor exception, as we are obliged to run some proprietary code licensed directly from Oracle to pass the language compatibility test suites.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
We already have access to some machines (thank you!), so this request is to formalise their usage.
 - Two type2a machines for building and testing our ARM builds.
 - Two type 1 machines for hosting our key services such as the API and Keybox
 - Two ARM32 machines for building and testing Raspberry Pi builds of OpenJDK.
 - A handful on Type 0 machines for hosting test machines

### Please state your contributions to the open source community and any other relevant initiatives
The team contributions to the project can be seen via [the AdoptOpenJDK organization](ttps://github.com/orgs/AdoptOpenJDK/people) in GitHub; and the discussions that primarily take place [on Slack](https://adoptopenjdk.slackarchive.io/).

**Comment by vielmetti** [comment]
Adopt OpenJDK is now using the Works on Arm cluster machines for its arm64 build and test.

**Comment by gdams** [comment]
Seeking an 1 or 2 aarch linux machines to enable to run Oracle's JCK complicance tests on our aarch64 binaries. This is the test suite that allows us to legally call our binary "Java".

**Comment by vielmetti** [comment]
Marking this issue as "closed" as substantially all of the desired setup tasks are complete.

There's a note at https://www.worksonarm.com/explore/openjdk for the current status of all of the OpenJDK projects.

**Comment by vielmetti** [comment]
Per request added a Type 2A2 (Hisilicon Hi1616) system to the project.

**Comment by vielmetti** [comment]
Reopen to address request for additional Hi1616 for use with 32-bit builds.

**Comment by vielmetti** [comment]
A new Hi1616 system in DFW has been reserved for the account; I'll keep this issue open until it's been turned up.

**Comment by vielmetti** [comment]
The Hi1616 system turnup has been delayed due to the complexities of configuring Jenkins to support 32-bit Arm in its build environment. 

There are some notes (but not adequate notes) at https://github.com/WorksOnArm/cluster/blob/master/content/arm32/_index.md

**Comment by karianna** [comment]
@vielmetti any updates?

**Comment by vielmetti** [comment]
@karianna - I am traveling this week (LInaro Connect) and plan to engage with this next week.

**Comment by vielmetti** [comment]
In particular, there are some aspects of forcing a 32-bit build system that a few projects are wrestling with that I've helped solve before but are by no means obvious....

**Comment by karianna** [comment]
Not today bot!

**Comment by vielmetti** [comment]
An update of sorts to keep the bots at bay.

In the #arm channel of the Adopt OpenJDK Slack, @sxa555 (Stuart) and I are working out the details of getting `virt-manager` up and going to support pure 32-bit native guests on the 64/32 bit capable hardware these are running on. The last observation we had was that to successfully boot a UEFI-based system you had to do a `apt-get install qemu-efi` before setting up `virt-manager`, otherwise you get an error about a missing `QEMU_EFI.fd` or `AAVMF_CODE.fd` file.

**Comment by vielmetti** [comment]
A note that still is still open - I will contact @sxa555 out of band and assess and report on progress on the 32-bit build cycle.

**Comment by karianna** [comment]
@vielmetti I think the arm32's are up now yes?

**Comment by vielmetti** [comment]
@karianna --

All of the equipment for this project has been assigned and are "up", so I'm going to close this particular issue.

However, there is still an outstanding issue as far as I know about the necessary bits of documentation / virtualization / configuration to get a clean 32-bit Arm runtime for Jenkins on the 64/32 bit hardware this is running on.

ccing @edolnx on this - continuing to want to get this sorted out.

**Comment by karianna** [comment]
Great thanks!

Cheers,
Martijn

**Comment by vielmetti** [comment]
Noted at https://github.com/AdoptOpenJDK/openjdk-website/issues/562 that we'll be reviewing the current text of the acknowledgements on your sponsors page and will make sure that it adequately reflects reality (with current or new logos, and new copy).

**Comment by vielmetti** [comment]
Call being planned with @gdams - this can be tracked at the above 562 issue. Closing here.
