### ISSUE TITLE
Codefresh: ARM 32-bit cluster

### ISSUE THREAD

**Issue by Superfresh** [WorksOnArm/cluster#60]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title
Oleg Verhovsky, oleg@codefresh.io, Codefresh, CTO
Dan Garfield, dan@codefresh.io, Codefresh, VP of Marketing 

Note that projects with two or more participants are preferred.

### Project Title and description
Codefresh CI/CD for ARM
Codefresh will support image builds for ARM 32-bit and 64-bit.

### Which members of the community would benefit from your work?
Anyone building docker images for ARM

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
No, it'll be a mix of open and closed source.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
32-bit and 64-bit support. 

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Please state your contributions to the open source community and any other relevant initiatives
Chart Museum, Kubernetes, Helm, etc...

Brag a little bit about yourself, please!
We're the first CI/CD platform designed for Kubernetes. Check us out at codefresh.io

**Comment by vielmetti** [comment]
32/64 bit machine has been reserved, ready to provision. 

We have some other c1.large.arm infrastructure for Codefresh in a different project that will be brought over at some point soon.

**Comment by vielmetti** [comment]
Added an additional collaborator to the project.

**Comment by vielmetti** [comment]
Project is up and running in alpha test. @Superfresh can you provide more info about the alpha when you're ready to?

**Comment by vielmetti** [comment]
Not ready to close just yet, pending arrival of additional hardware into the cluster.
