### ISSUE TITLE
ARM platform support for Georgia Tech scheduling research

### ISSUE THREAD

**Issue by rudyjantz** [WorksOnArm/cluster#61]
### Name, email, company, job title
Amitkumar Patil, amitkumar.bvb@gmail.com, Georgia Institute of Technology, PhD student
Girish Mururu, girishmururu@gatech.edu, Georgia Institute of Technology, PhD student
Chris Porter, porter@gatech.edu, Georgia Institute of Technology, PhD student
Santosh Pande, santosh.pande@cc.gatech.edu, Georgia Institute of Technology, Professor

### Project Title and description
Compiler-assisted scheduling on ARM
We've been investigating predictive scheduling techniques that leverage the compiler. The gist of the solution is that the compiler has insights into program behavior that it can expose to runtime components. With higher core densities in these new ARM servers, we're interested in investigating how these artifacts and behaviors could be leveraged for process and container scheduling that leads to improvements in performance and latency of applications, along with better workload consolidation and balancing.

### Which members of the community would benefit from your work?
Compiler and systems researchers and enthusiasts will benefit from the successes (or failures) of this. If the results are good, then this could be another possible technique for making better use of increasing core counts. This could benefit data center operators (reduced energy and therefore cost by workload consolidation without compromise in performance) and their users (via strong SLA guarantees even with high job consolidation).

### Is the code that you're going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes, we'll open source all of it. Our present code base is disorganized and distributed among several computers, as is often the case in research. We'll start moving it under one umbrella for the purposes of this platform: https://github.com/rudyjantz/beacons

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
A Cavium ThunderX would work perfectly for the first round of experiments. In fact, we don't need both chips and all 96 cores. A single chip with 48 cores would be sufficient for starting. We need this for building the initial prototypes and benchmarks and for running the experiments. Essentially, we'd need it like a development machine. This is summer 2018 work. We'll probably need the machine an average of 4 hours per day.

### Please state your contributions to the open source community and any other relevant initiatives
We are all relatively junior researchers and have only dabbled in open source. This project would probably be the biggest contribution from any of us. Chris has a few small contributions to a MIPS emulator called "spim" and some early, small contributions to some C code at a start-up called "storj" (both on github.com/rudyjantz). Amit has made contributions to the Linux kernel main line during his time at Intel.

**Comment by vielmetti** [comment]
A few questions -

Which compiler are you targeting (GCC, LLVM?)

What other components are you looking at (kernels?)

Do you have any dependencies yet on specific versions of anything?

I ask all of this because I want to get some external review from folks who might be familiar with the problem domain and could share what they know of current work.

**Comment by rudyjantz** [comment]
**Which compiler are you targeting (GCC, LLVM?)**
LLVM only.

**What other components are you looking at (kernels?)**
This first work is about exposing cache/memory usage to scheduling. In the past, we've looked at interaction with the Linux kernel's scheduler. This could be effective, potentially. There are a few reasons not to do that here, though. For one, we won't have access to the physical board. So the idea here is to keep everything in user space and have the processes self-manage some of the scheduling.

**Do you have any dependencies yet on specific versions of anything?**
We will put LLVM 3.8 on the machine. I suspect there will be missing dependencies when we build the benchmarks, so we'll need to be able to install packages. A Debian box would be preferred, but any decently up-to-date Linux version is fine.

**Comment by vielmetti** [comment]
Project approved! 

I've sent email invites to the project participants listed above.

Please deploy a c1.large.arm server (96 core Cavium ThunderX) in our EWR1 data center. You should be able to provision Debian 9 on the system and run based on that.

Please have someone from the project join the Packet Community Slack or the IRC channel #worksonarm on Freenode. 

I've identified some LLVM on Arm developers that I'd like to introduce you to when you have something more to share - just say the word and I'll make those connections for you.

**Comment by rudyjantz** [comment]
Great! We'll give it a go and update you guys soon.

**Comment by vielmetti** [comment]
We ran into a snag with Debian 9.4 provisioning, which I'll update when it's ready to go.

**Comment by rudyjantz** [comment]
For posterity: It all got set up fine. We're off and running.

**Comment by vielmetti** [comment]
Setup phase is complete, so I'll mark this item as closed.
