### ISSUE TITLE
Open Source Swift coding language on aarch64 machines.

### ISSUE THREAD

**Issue by futurejones** [WorksOnArm/cluster#62]
### Project - Porting Open Source Swift coding language to aarch64 machines.

The Swift coding language was developed by Apple and released as open source in 2015.  
https://swift.org/about/

In 2016  http://swift-arm.slack.com was set up to port Swift to the RaspberryPi and other armv6/v7 devices.
This was achieved for Swift version 3 and many people having been coding with swift on RasberryPi's since then.

Here are some Swift on RaspberryPi tutorials - https://www.hackster.io/futurejones

We are now seeing a lot RasberryPi style SBC's with arm64/aarch64 cpu's, at the same time Swift is evolving and is now being used in many Server Side open source projects such as - 
- https://github.com/vapor/vapor
- https://github.com/IBM-Swift/Kitura
- https://github.com/PerfectlySoft/Perfect
- https://github.com/apple/swift-nio

The goal of this project is to not only port Swift to aarch64, but also port any build tools required for building Swift and other related software.

All of this will be made available in apt-get install packages at - 
- https://packagecloud.io/swift-arm

### Which members of the community would benefit from your work?
Anybody who wants to use the Swift coding language on an aarch64 machine.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes - https://github.com/apple/swift

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We would like to request long-term ongoing resources for -
- 1/ Manual Swift testing/development on aarch64.
- 2/ Adding an Aarch64 node to https://github.com/apple/swift-community-hosted-continuous-integration

Both of these should be easily handled by the https://www.packet.net/bare-metal/servers/c1-large-arm/ server.

Smaller aarch64 machines would also be suitable with 8+ cores and 32GB ram

### Please state your contributions to the open source community and any other relevant initiatives

I am an active contributor to the Swift open source project, a member of swift-arm slack team, and I setup and maintain https://packagecloud.io/swift-arm

Thankyou for considering this request.

**Comment by futurejones** [comment]
All setup and running with c1.large.arm Ubuntu 16.04 at NRT1.
I have submitted a pull request to add an aarch64 node to the Swift Community CI
https://github.com/apple/swift-community-hosted-continuous-integration/pull/10
Thanks again for your support. Having access to this level of hardware is going to make a huge difference to what we can achieve.

**Comment by vielmetti** [comment]
Closing this issue (as the hardware is set up), looking forward to the CI setup too.

**Comment by vielmetti** [comment]
CI is set up as described above, with Jenkins.

An open issue that's in the way of a successful build currently is https://github.com/apple/swift/pull/15174 - I'm reopening this issue, with a closing criteria when the build is green, so we can track that to completion.

**Comment by vielmetti** [comment]
The relevent issues in the Swift JIRA are

* https://bugs.swift.org/browse/SR-221 - port to aarch64
* https://bugs.swift.org/browse/SR-2239 - the va_list issue referenced in https://github.com/apple/swift/pull/15174

**Comment by vielmetti** [comment]
There's progress in https://github.com/apple/swift/pull/15174 as of recently, with several people engaged. If you know Swift internals and arm64 this would be an excellent place to jump in.

**Comment by vielmetti** [comment]
Work is sufficiently underway on this that it's not necessary to keep this issue open - good luck @futurejones with the porting efforts!

**Comment by lag-linaro** [comment]
Any update on this?  I still do not see Swift in the Works-On-Arm support project list.

**Comment by vielmetti** [comment]
@lag-linaro -- there is an active "Swift on Arm" community where a bunch of this daily discussion is going on.

https://launchpass.com/swift-arm

**Comment by lag-linaro** [comment]
I believe that Swift now works on AArch64.  Any chance of getting it on WorkOnArm?
