### ISSUE TITLE
Memcached: ARMv8/etc

### ISSUE THREAD

**Issue by dormando** [WorksOnArm/cluster#63]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Dormando. no company or job title.

Note that projects with two or more participants are preferred.

### Project Title and description

Memcached. https://memcached.org - you probably know what this is. Recently ran tests for intel's optane, been recently fixing bugs and build problems for ARM hosts.

### Which members of the community would benefit from your work?

Me, so 100% of the developers :) Any users who wish to lower power usage for caches could stand to benefit as well.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes. https://memcached.org/ - links from here.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

At least a 64bit machine occasionally to run CI on, as I've had some failing builds recently.

As far as permanence, it's up to you folks. Packet already provides some intel servers which I use for release validation, burn-in and fuzz testing of new features, etc. The more I can do that on ARM the faster and more reliable it should perform... that said my usage is sporadic, I might use it constantly for a couple weeks on a burn-in or during development, and then not at all for a month or two beyond CI.

There is a separate need for CI, which is lighter and basically once a month kind of thing. I'm not sure how this best works out.

### Please state your contributions to the open source community and any other relevant initiatives

Memcached for ten years. MogileFS, Perlbal, Gearman, MySQL community, lots of infrastructure stuff.

just did an optane test and posted the results. would love to do more of those tests on machines which aren't locked under NDA (or if the hardware company is willing to work with me on it). I've received at least one patch from qualcomm, so maybe they're interested.

**Comment by vielmetti** [comment]
@dormando - what kind of software do you have in mind for CI? Describe the existing tooling, and what you might expect it to be once this project is up and running.

**Comment by dormando** [comment]
Whoops, forgot to mention specifically: I use a custom buildbot setup to cover a mix of cloud instances and physical hardware.

**Comment by vielmetti** [comment]
Project approved. Please take a look at https://github.com/WorksOnArm/cluster/blob/master/ACKNOWLEDGEMENT.md (which is new) so that when you're ready to publish something about this we can work together on that.

**Comment by vielmetti** [comment]
I'll mark this issue as "closed" when buildbot is up and running in some form.

**Comment by dormando** [comment]
planning this for next week

**Comment by vielmetti** [comment]
Hi @dormando - if you can make it, please join us for Office Hours, details at #83 for the July 11 edition.

**Comment by dormando** [comment]
can't make it this week, a bit busy with the optane system, sorry!
