### ISSUE TITLE
Proposal: Docker Official Images building

### ISSUE THREAD

**Issue by tianon** [WorksOnArm/cluster#7]
### Name, email, company, job title

Tianon Gravi, tianon@dockerproject.org
InfoSiftr, SVP of Operations

### Project Title and description

Docker's Official Images program

> The Docker Official Repositories are a curated set of Docker repositories that are promoted on Docker Hub.

### Which members of the Works on Arm community and/or end-users would benefit from your work?

Any who wish to use Docker on ARM! :smile: :innocent:

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, absolutely!  The main entrypoint is at https://github.com/docker-library/official-images, which currently includes the canonical tool used to build the official images (`bashbrew`), but also is the primary source-of-truth for the source of every image built, each pulled directly from their own respective (public) Git repository.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We currently have decent hardware for building `arm64` images, but our `arm32` builds are really struggling.  What we'd like to do is either move the `arm32` builds to a nicer machine, or move the `arm64` builds to a nicer machine and move the `arm32` builds to _that_ machine, which is likely what'll end up happening if we can get access to some beefy Packet hardware (since we really like having `arm64` builds be fast -- would love if we could get `arm64` hardware that's able to compete with the performance of the `s390x` box we've got). :innocent:

### Please state your contributions to the open source community and any other relevant initiatives

I'm personally involved very heavily (as the chief steward) in the Official Images project (as described here), but I'm also involved elsewhere in the container community (OCI, etc).  In addition, I'm a Debian Developer and help maintain a number of packages over there (and several downstream in Ubuntu as well).

**Comment by vielmetti** [comment]
Noted by @tianon the instant interest in this because a number of arm32v7 builds are currently failing; see https://doi-janky.infosiftr.net/job/multiarch/job/arm32v7/ for the Jenkins build info.

**Comment by vielmetti** [comment]
Talked to @tianon and provisioned a 2A2 server, so the setup process starts.

**Comment by vielmetti** [comment]
There's a brief writeup here:

https://github.com/WorksOnArm/worksonarm-news/blob/master/2017-W40.md#building-32-bit-arm-official-docker-images

and a juicy quote from @tianon 

> Our multi-week backlogged queue was completely caught up literally overnight for arm32v7, we were able to add arm32v5 and get it caught up in just about the same amount of time, and we were even able to re-enable arm32v5 support on several images where it was previously prohibitively slow such as python, php, ruby, and even gcc!

**Comment by vielmetti** [comment]
Closing as "setup complete".

**Comment by tianon** [comment]
Copying my comment from https://github.com/docker-library/official-images/issues/6490#issuecomment-522147233 here (for lack of a more appropriate place -- happy to redirect if there's a better place to send/put this :heart:):

> @vielmetti I believe when our server was provisioned we discussed that our storage space could potentially be increased later if we determined we needed more? Is that something that could be considered so that we run into this issue less frequently? Is there an official process for requesting something like that?

**Comment by vielmetti** [comment]
Hi @tianon -

Please review https://support.packet.com/kb/articles/elastic-block-storage for attachable block storage. I'd pick the "performance" tier for anything being used actively, or the "standard" tier for long-term storage.

**Comment by tianon** [comment]
It's for `/var/lib/docker` (multiple different `/var/lib/docker`s, really since we run separate daemons for separate target arches), so definitely pretty active when a build is actually running, but we don't want to be a burden so would be perfectly happy with the "standard" tier (especially given that storage capacity is generally the thing we run up against the limits of and the cost difference isn't exactly negligible :sweat_smile:).

Is this something I should just go ahead and create through the portal, or do you need to do something first?

**Comment by vielmetti** [comment]
You can just create it through the portal, @tianon - I'd A/B test standard vs performance configurations to see what the difference is, and then select accordingly. (If standard gives you "good enough" build times, and if performance doesn't make it much better, then we can make a choice.)

You should also know that we have had some successful configuration, notably @avsm in an OCaml build environment, use a temporary RAM-backed filesystem for the hot cache. These systems have 128G of memory, and some builds don't come near to using all that, so if you can tolerate a filesystem that would disappear upon reboot it would be an interesting thing to look into.

**Comment by tianon** [comment]
Nice, did some testing and for our use the performance is really pretty equivalent (we're CPU-bound more often than IO-bound, but on this server we're rarely bound much by either :smile: :metal:), so we'll go with the less expensive version. :+1:

Regarding RAM-backed filesystems, that would be super killer, although for the way we build it would really need to be something built into Docker itself, ideally putting all read-write layers on the RAM-backed filesystem with committed layers going to persistent storage, so not very realistic for us today, but perhaps something we could consider more as containerd gains more foothold in those aspects of Docker! :smile:

**Comment by tianon** [comment]
(Going to close this again given the above; thanks @vielmetti!! :heart: :exclamation:)

**Comment by cayu53** [comment]
Hi Ed, Tianon,

Sorry for the delay, happy for this to proceed from the Arm side too.

Best,
Philippe
