### ISSUE TITLE
builder for Linaro

### ISSUE THREAD

**Issue by fboudra** [WorksOnArm/cluster#77]
### Project Title and description

Linaro CI build slaves

Linaro is a collaborative engineering organization consolidating and optimizing open source software and tools for the Arm architecture. Linaro engineering works with upstream (and downstream) projects on a set of requirements that are determined by the Technical Steering Committee (TSC).

At Linaro, the System Technologies group provides infrastructure and software solutions to Linaro engineering in order to support their efforts into improving the open source eco system on Arm.
We provide a Jenkins instance (https://ci.linaro.org/)

### Which members of the community would benefit from your work?

Linaro is contributing to various open source projects. To name a few: the Linux Kernel, the GNU Compiler Collection (GCC), Zephyr, AOSP, UEFI, OP-TEE, OpenEmbedded, Debian and many others.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

In addition to the upstream projects repositories that we're using, our repositories can be found on:
* https://git.linaro.org/
* https://github.com/linaro
* https://github.com/96boards

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We'll need access to a c1 large arm instance (https://www.packet.net/bare-metal/servers/c1-large-arm/).

### Describe the continuous integration (CI) system in use or desired for this project.

The system will be connected to ci.linaro.org as a Jenkins slave, running docker nodes.

### Please state your contributions to the open source community and any other relevant initiatives

My personal contributions to the open source community goes from Debian, Qt, KDE, OpenEmbedded to the Linux Kernel (and many other open source projects). I've been a long time open source contributor and an open source advocate. As for the company I work for, Linaro is regularly in the top 10 contributors to the Linux kernel, next to companies 10+ times its size :)

**Comment by vielmetti** [comment]
Thanks @fboudra ! This looks good.

We are coordinating a number of projects with Linaro. Can you take a look at #45 from @maxim-kuvyrkov which appears to cover the same Jenkins infrastructure? I'm happy to provide capacity as needed, but I want to be sure you know what else is already going on between Packet and Linaro re Jenkins CI.

**Comment by fboudra** [comment]
@vielmetti Thanks, I'm aware of @maxim-kuvyrkov request. We're in sync. The toolchain working group request is covering the resource needed for the GNU toolchain CI. My request covers a general purpose slave used by the remaining working groups. They don't overlap. Sorry for the confusion and I hope it helps to clarify.

**Comment by vielmetti** [comment]
Invite sent! It should be self-explanatory from here, if anything is not, please let me know here or via email or Slack or your favorite channel.

**Comment by fboudra** [comment]
@vielmetti Thanks! The server is up and running. Can you add systems@linaro.org to the project? It's our infrastructure team.

**Comment by bhcopeland** [comment]
Thanks Ed, have accepted the request. Although I am not sure if came through correctly.

() invited you (systems@linaro.org) to the “” .

Also - after logging into my packet.net account no servers seem to be showing. Not sure how it is setup, but systems@linaro.org should be our "main" linaro account.

**Comment by bhcopeland** [comment]
Thanks @vielmetti. It does seem to be a system issue, I have replied back the details in a email to you.

**Comment by vielmetti** [comment]
Hi @fboudra @bhcopeland - if you can make it, please join us for Office Hours, details at #83 for the July 11 edition.
