### ISSUE TITLE
Stackhatch, Inc - Open Cloud Platform & CaaS managed services for Open Source 

### ISSUE THREAD

**Issue by jbanimineni** [WorksOnArm/cluster#78]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

**Name:** JayaBabu
**Email:**  jbanimineni@stackhatch.org
**Company:**  [Stackhatch, Inc](https://stackhatch.org)
**Job Title:** Founder & Architect

**Name:** Nagesh
**Email:** nanimineni@stackhatch.org
**Company:** [Stackhatch, Inc](https://stackhatch.org)
**Job Title:** DevOps Engineer & Developer
Note that projects with two or more participants are preferred.

### Project Title and description

**Project Title:** Open Cloud Platform
**Description:**
 1. Open Cloud Platform provides a solutions to automate & Orchestrate hybrid cloud platform with free  
of cost.
2. Providing CaaS(Container as a Services) based kubernetes infrastructure for open source projects to build, test, deploy their applications on ARM with free of cost.
3. Will provides managed services on all hybrid cloud platforms. 
4. Providing support services to anyone on Open Source Tools like Docker, Jenkins, Kubernetes etc..
5. Requires infrastructure to evaluate open source CI/CD Tools to suggest better one for Open Source Projects.

### Which members of the community would benefit from your work?

Anyone who wants to building their open source projects on docker images & deploying kubernetes cluster will gets benefit without setting up infrastructure

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, Stackhatch, Inc developed all projects licensed under [Apache License.](https://gitlab.com/stackhatch-org/container-services/centos/blob/master/LICENSE)

**Projects Hosted on Gitlab:** https://gitlab.com/stackhatch-org
**Latest Release:** https://gitlab.com/stackhatch-org/container-services/centos

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

We required ARM Servers https://www.packet.net/bare-metal/servers/c1-large-arm/

for kubernetes cluster setup with HA.

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe the continuous integration (CI) system in use or desired for this project.

We will use Jenkins as our CI System for our projects

### Please state your contributions to the open source community and any other relevant initiatives

Contributing to Stackahtch, Inc since 2016

Brag a little bit about yourself, please!

This is **JayaBabu**, I'm started my journey with [Stackhatch, Inc](https://stackhatch.org) since 2016 on designing & implementing to build Open Source Projects to automate and Orchestrate Hybrid cloud platform.

Our goal is that to maintain Open Source Tools infrastructure free of cost for developers & entrepreneurs etc..with free of cost. If they got any issues on infra or development side we are here to help through [Support](http://support.stackhatch.org).

**Comment by vielmetti** [comment]
Hi @jbanimineni - if you can make it, please join us for Office Hours, details at #83 for the July 11 edition.
