### ISSUE TITLE
Bring up of ARM64 Container CI support

### ISSUE THREAD

**Issue by glevand** [WorksOnArm/cluster#8]
### Name, email, company, job title

Geoff Levand, geoff@infradead.org, Cavium, Engineer
Zi Lim, zlim@caviumnetworks.com, Cavium, Engineer

### Project Title and description

**Bring up of ARM64 Container CI support**

Bring up of continuous integration testing for CoreOS Container Linux and other container related projects (etcd, mantle, rkt, etc.) on ARM64 machines.  Note that this request is not for hosting for a continuous integration system, but for machines to use in testing newly developed software that will allow open source projects to run their continuous integration tests on ARM64 machines.

### Which members of the Works on Arm community and/or end-users would benefit from your work?

Anyone using container related technologies on ARM64 machines.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes.
https://github.com/coreos/etcd
https://github.com/coreos/mantle
https://github.com/coreos/jenkins-os
https://github.com/rkt/rkt

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Several TYPE 2A for testing newly developed software support.
Several TYPE 1 for regression testing.

### Please state your contributions to the open source community and any other relevant initiatives

Please see:
https://github.com/coreos/etcd/issues?q=author%3Aglevand
https://github.com/coreos/mantle/issues?q=author%3Aglevand
https://github.com/coreos/jenkins-os/issues?q=author%3Aglevand
https://github.com/rkt/rkt/issues?q=author%3Aglevand

cc: @zlim

**Comment by vielmetti** [comment]
Geoff @glevand - thanks for the proposal!

One of the things that I've added in the newest proposal template - see #14 - is a request for people making proposals to identify a team with more than one person working on it - this is especially true for code that's from a foundation that may be available to provide additional support for the effort.

Do you need several systems right away, or would it be possible to start with one for bringup?

**Comment by glevand** [comment]
@vielmetti I've added @zlim to the project.  I think one TYPE 2A and one TYPE 1 would be enough to get things setup.

**Comment by vielmetti** [comment]
Ready to move forward on this!

**Comment by glevand** [comment]
@vielmetti  I've created a new Packet project `ARM64 CI Testing` to use for this work.  The first step will be to bring up a recent CoreOS Container Linux release.

**Comment by vielmetti** [comment]
Set up for free spot market use - let me know any needs for long-lived servers, and we can arrange for those as well.

**Comment by vielmetti** [comment]
@glevand @zlim - this issue popped up as stale, and I'd like to understand if you have all of the resources and access you'd need to tackle this. Some of our processes have changed since Nov 2017 so it may be worth revisiting this.

**Comment by vielmetti** [comment]
Reopening to address any issues raised by Fedora CoreOS and the new directions of Container Linux.

**Comment by vielmetti** [comment]
For context, Fedora CoreOS (FCOS) has weekly meetings, and @glevand and I are routinely attending.
