### ISSUE TITLE
Memory walls: Application for getting access to Cavium's ThunderX2

### ISSUE THREAD

**Issue by FrancescAlted** [WorksOnArm/cluster#80]
### Name, email, company, job title

Francesc Alted <francesc@blosc.org>
Consultant Freelancer

Aleix Alcacer <al312972@uji.es>
Graduate student
Programmer

### Project Title and description

Check that memory walls can be break down.

I am looking for use cases and CPUs that can use compression so as to bypass the bandwidth limits of computers.  There is a description on what I am after in my blog at:  http://blosc.org/posts/breaking-memory-walls/

I would like to complete the study with the newest Cavium's ThunderX2.

### Which members of the community would benefit from your work?

Blosc is an open source project, and right now is used in a lot of packages, mainly in the Python ecosystem (but not only that).  Some examples that use Blosc are:

* http://www.pytables.org
* http://bcolz.readthedocs.io/en/latest/
* http://zarr.readthedocs.io/en/stable/
* Houdini (http://www.sidefx.com/docs/houdini/index.html), a tool for producing animation movies.   http://www.sidefx.com/docs/houdini/render/ifd_workflows.html#blosc

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, this study is using 100% open source.  You can access to all the sources in: https://github.com/Blosc/c-blosc2 

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Access to Cavium's ThunderX2 boxes.  This will be needed for short term access (typically several runs that should take no longer than a few hours).

### Describe the continuous integration (CI) system in use or desired for this project.

No need.

### Please state your contributions to the open source community and any other relevant initiatives

I am an independent consultant and developer with more than 25 years of experience wrestling with Big Data in many different ways, as well as leveraging compression techniques for accelerating I/O. 

I am a long term regular contributor to the open source community, and produced several, heavily used packages, including:

* https://github.com/Blosc/c-blosc
* https://github.com/Blosc/c-blosc2
* http://www.pytables.org
* http://bcolz.readthedocs.io/

You can have a look at my resumé here:

http://www.blosc.org/pages/francesc-alted-resume/

Thanks!

**Comment by vielmetti** [comment]
Looks good to me - I've asked a reviewer to take a look too.

**Comment by vielmetti** [comment]
Hi @FrancescAlted - if you can make it, please join us for Office Hours, details at #83 for the July 11 edition.

**Comment by FrancescAlted** [comment]
I can try to join you, but it's a bit late here (Spain).  I tried both http://slack.packet.net and https://slack.packet.net, but I cannot login.  Which my credentials should be?

**Comment by FrancescAlted** [comment]
Ok. I figured that out.  Talk to you in some minutes!

**Comment by vielmetti** [comment]
Project approved, @FrancescAlted . We have some work to do on the ThunderX2 to get their firmware all up to date and to figure out all of the logistics, but you should be able to start by accepting the invitation to join the project. I'll keep this item open for questions.

**Comment by vielmetti** [comment]
Issue "Upgrade ThunderX2 firmware" #85 will track the firmware issue.

**Comment by FrancescAlted** [comment]
Cool!  Many thanks.  I have accepted the invitation and logged in with my current packet account which has a gmail email (faltet@gmail.com) instead of my more 'corporate' one (francesc@blosc.org).  Hope this is ok?

**Comment by vielmetti** [comment]
That's ideal to reuse the existing Packet account, yes thanks.

**Comment by vielmetti** [comment]
As an update, we are still waiting on a firmware upgrade for the ThunderX systems. Updates to that will be in #85.

**Comment by FrancescAlted** [comment]
I see in #85 that you hav a 7.0 release for that.  Please keep me informed about progress on this because I am very interested in testing this machine.  Thanks!

**Comment by FrancescAlted** [comment]
Hi, any news on this?  Can this be reopened, or ThunderX is available somewhere for trying it out already?

**Comment by vielmetti** [comment]
I think I now have a ThunderX2 for your use, it's going through a provision/deprovision cycle as I type. I'll update with availability shortly.

**Comment by FrancescAlted** [comment]
That's great news.  Thanks!

**Comment by vielmetti** [comment]
Machine assigned to project, we'll count this as closed when you report back as all-ok @FrancescAlted

**Comment by vielmetti** [comment]
Reported preliminary results so close this out!

**Comment by vielmetti** [comment]
Results published!

http://blosc.org/posts/arm-memory-walls-followup/
