### ISSUE TITLE
Rethinkdb 2.3.6

### ISSUE THREAD

**Issue by gounthar** [WorksOnArm/cluster#81]
### Name, email, company, job title
Bruno Verachten, gounthar@gmail.com, Worldline by Atos, Analyst.

### Project Title and description
I have tons of projects around ARM, but it's difficult to build them on *PI.
One of them is version 2.3.6 of rethinkDB https://github.com/gounthar/docker-rethinkdb .
The 2.3.5 version already exists, but I haven't managed to compile the 2.3.6 version yet.
I am also working on node, but can't compile it : https://github.com/nodejs/node/issues/21190 .
I am also building ARM Docker images on [DockerHub](https://hub.docker.com/u/gounthar/) thanks to the resin.io work, but would like to build them on ARM Hardware.
My goal is to be able to run openSTF on ARM devices: https://github.com/openstf/stf/issues/820 
I already own OrangePi Zero, OnePlus, Raspberry Pi 3B, Nano Pi Fire3, Odroid XU4...
I already use a gitlab-runner image on one of my SBC.
I would also like to test a real ARM server as a gitlab-runner.

### Which members of the community would benefit from your work?
Anyone interested in the openSTF project, or building and using Docker images on ARM machines. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
https://github.com/openstf/stf
https://github.com/rethinkdb/rethinkdb
https://github.com/nodejs/node
https://github.com/gounthar?tab=repositories

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?
c1.large.arm

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

### Describe the continuous integration (CI) system in use or desired for this project.
gitlab-ci would be perfect...

### Please state your contributions to the open source community and any other relevant initiatives
My goal is to promote the use of ARM devices in the company I work for and elsewhere. I am implicated in the continuous integration for mobile application development (gitlab-ci).
The repositories you can see in my github account are all linked to openSTF somehow. I need to be able to build Linux distros (I am trying to help Armbian) for my ARM devices, build Docker images and ARM applications too.
In my company, we are already using tons of X86 servers, and I want to experiment with ARMV8 servers too (but I have to prove first that ARM SBCs are a must-have in the company...).
I try to evangelize in my company by giving [talks](https://twitter.com/i/moments/1014591620841340929), and so on...

**Comment by vielmetti** [comment]
Hi @gounthar - if you can make it, please join us for Office Hours, details at #83 for the July 11 edition.

**Comment by gounthar** [comment]
Sorry, I haven'( been able to join. I will listen to the recorded call.

**Comment by vielmetti** [comment]
Thanks @gounthar - there's also info at 

https://www.worksonarm.com/community/

on how to join various channels that are not so much real time (IRC, Slack, weekly newsletter &c).

**Comment by mmarmm** [comment]
@gounthar Hi Bruno, there are public CI resources you can now use, I don't know if you're aware of them but see below for details.

As far as RethinkDB is concerned, could you help us resolve and issue to provide Docker Official Images?: https://github.com/rethinkdb/rethinkdb/issues/6678

FYI - Shippable and CodeFresh have free support for one Arm64 (& 32-bit) pipelines if that helps, if not and you can help us resolve the RethinkDB issue above I can see what I can do to get you build system access. I also see your building node, is there any reason you're not using this: https://hub.docker.com/_/node/ ?

http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/ (three free parallel builds)
https://thenewstack.io/shippable-brings-continuous-integration-and-delivery-to-arm-servers/

CodeFresh Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

Scaleway does also offer paid Arm64 resources: https://www.scaleway.com/virtual-cloud-servers/#anchor_arm

Thank you again for supplying the Arm images and contributing to the ecosystem!

**Comment by gounthar** [comment]
Thanks @mmarmm. I am already using Shippable for ARM, but there is one limitation : we can't build ARM Docker images with them (for now). I have sent an email asking for some help, but got no answer yet.
As for node, I am trying to update [openSTF] which depends on node. I could maybe import files from the node Docker image instead of rebuilding it by myself...

Thanks for the links!
[openSTF]: https://github.com/openstf/

**Comment by gounthar** [comment]
It looks like shippable will allow Docker builds very soon.
Stay tuned...

**Comment by vielmetti** [comment]
Thanks @gounthar - if you get an update for this it would be appreciated.

**Comment by gounthar** [comment]
It should be ok this week, or at least, that's what I've been told.
I will try it again and let you know.

**Comment by gounthar** [comment]
It was supposed to be available this week, but we're only on monday...
` /root/5fbbd442-9a68-4cef-b279-b649ecf0b24f.sh: line 79: docker: command not found`

**Comment by gounthar** [comment]
I got an email today: 

> Docker support is now enabled for the shared Arm node pool. Please try it and let me know if it works as expected for you.

**Comment by gounthar** [comment]
I'm working on the RethinkDB 2.3.x on Shippable's aarch64. [https://github.com/rethinkdb/rethinkdb/issues/6699](url)

**Comment by mmarmm** [comment]
@gounthar Hi Bruno, any updates on progress getting rethink to build on arm64? Is Shippable working well for you? Thanks.

**Comment by gounthar** [comment]
For the time being, my build is always stuck at Shippable... and I don't have much logs to help.
I'm trying to find another aarch64 CI system to try.
```bash
/install.witness'.
                      Must remake target 'build/external/bluebird_2.9.32/install.witness'.
Putting child 0x2a1fe700 (build/external/bluebird_2.9.32/install.witness) PID 21327 on the chain.
Live child 0x2a1fe700 (build/external/bluebird_2.9.32/install.witness) PID 21327 
    [9/454] BUILD bluebird_2.9.32
Reaping winning child 0x2a1fe700 PID 21327 
Live child 0x2a1fe700 (build/external/bluebird_2.9.32/install.witness) PID 21652 
```

**Comment by gounthar** [comment]
My issue at rethinkdb has disappeared, but it appears that the subject is still interesting for some: https://github.com/rethinkdb/rethinkdb/issues/28

**Comment by vielmetti** [comment]
Thanks for the update, @gounthar  - I'll keep this closed for now.

**Comment by gounthar** [comment]
I tried to build the "next" branch today. I only got one error, and commented the existing issue: https://github.com/rethinkdb/rethinkdb/issues/28

**Comment by gounthar** [comment]
Problem solved: https://github.com/rethinkdb/rethinkdb/issues/28#issuecomment-433414543 .
Now to the Docker image...
