### ISSUE TITLE
QEMU: docker build testing and non-x86 KVM

### ISSUE THREAD

**Issue by stsquad** [WorksOnArm/cluster#87]
### Contacts

Alex Bennée @stsquad <alex.bennee@linaro.org>, Linaro, Virtualization Engineer
Philippe Mathieu-Daudé @philmd <f4bug@amsat.org>, Red Hat, Senior Engineer

### QEMU docker support and non-x86 KVM testing

QEMU has a growing amount of docker support in it's build system for various cross-build configurations as well as building test cases. However it is very much based on the default assumption that developers are using x86 build hosts. We have already experimented with using QEMU linux-user powered solutions on x86 where cross compilers aren't available but we can certainly use this for non-x86 systems as well.

Also most of our CI testing is focused on x86 (Travis,Shipable) so it would be good to expand the testing to more non-x86 setups.

### Which members of the community would benefit from your work?

The work should benefit all users developing and running on non-x86 hardware although obviously Linaro has a particular interest in ARM. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, all totally open and free:

  https://git.qemu.org/?p=qemu.git;a=summary

and others sub-projects hosted/mirrored on https://git.qemu.org/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

As we need to run docker (and maybe KVM) we need host OS access and a reasonable amount of disk space to store images. This is currently envisioned as boot-strapping support to get stuff up and running and shake out the bugs. It would be nice to get some CI stuff set-up later but this might be better done via Linaro's CI infrastructure.

### Describe the continuous integration (CI) system in use or desired for this project.

This is currently going to be for development work, once the bugs are shaken out we shall need to think about CI loops. Currently QEMU uses a hodge-podge of:

  Travis
  Shippable
  Patchew
  LAVA

See https://wiki.qemu.org/Template:CIStatus

### Please state your contributions to the open source community and any other relevant initiatives

I've been working on QEMU for about 5 years since joining Linaro, mostly on TCG (cross-architecture virtualisation) although I've also worked on KVM. When I joined I worked in the initial AArch64 TCG bring-up before moving on to the MTTCG project which removed the single-threaded nature of system emulation. Through that time I've been on a bit of a mission to improve QEMU's automated testing story most recently re-enabling the TCG tests by removing the need to make developers set up a cross compiler environment.

Philippe is a relatively new member of the community but has already made a significant impact across the whole code base from implementing new features, many code wide clean-ups as well as an active interest in the Docker build subsystem.

**Comment by vielmetti** [comment]
Approved! I've sent invites. You'll want to provision a c1.large.arm for your dev purposes.

Please do be aware that we also have new support for Shippable on Arm. I'm working on some text to describe how exactly to use it, but for now you can look at 

http://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture

for instructions and intake on that to integrate into your CI system.

**Comment by vielmetti** [comment]
Hi @stsquad ! Hoping you can provide an update on progress!

**Comment by stsquad** [comment]
Sure. I spent a lot of time on fixing up binfmt_misc support which is currently on list at:

  https://patchew.org/QEMU/20180718100505.7546-1-alex.bennee@linaro.org/

v2 of the series is currently being prepared.

We have also been doing some SVE testing (AArch64 on AArch64). @philmd has also been using the box extensively, I'll leave him to summarize on what.

**Comment by vielmetti** [comment]
(stale bot keeping me honest) -

Just following up with @philmd on the work done on SVE testing.

**Comment by stsquad** [comment]
Well I've been doing some testing of the x86 MTTCG patches this week, but mainly to check they don't turn on by mistake on AArch64 ;-) I'll probably be on the box this week once I'm at Connect in Vancouver.

**Comment by stsquad** [comment]
In a quest to improve cross compiler coverage in Debian (which qemu uses in it's build system) we've been building compilers. I've also added an additional user to the box @rth7680 who's also doing QEMU work (and a bit of gcc/glibc).

**Comment by vielmetti** [comment]
Sounds like good progress! I'm going to close this out (so that the stale bot does not nag us forever)
