### ISSUE TITLE
Evaluating performance cost of SC on Aarch64

### ISSUE THREAD

**Issue by Lun-Liu** [WorksOnArm/cluster#88]
### Name, email, company, job title

Lun Liu, lunliu93@cs.ucla.edu, UCLA, Ph.D. Student
Todd Millstein, todd@cs.ucla.edu, UCLA, Professor
Madan Musuvathi, madanm@microsoft.com, Microsoft Research Redmond, Principal Researcher

### Project Title and description

A Volatile-by-Default Java Virtual Machine for ARM

Java has a complex and unintuitive memory model, which determines the behaviors of reads and writes in the presence of multiple threads. As part of Ph.D. student Liu's dissertation research, co-advised by Millstein and Musuvathi, we recently introduced the volatile-by-default semantics as a natural form of sequential consistency (SC) for Java and showed that it incurs relatively modest overheads versus the Java memory model on Intel x86 hardware, via a modified version of Oracle's HotSpot Java virtual machine.  In this project we are evaluating the performance cost of the volatile-by-default semantics for Java on ARM hardware.  Such an evaluation is critical due to the popularity of the ARM platform and the fact that it has a much weaker memory model than x86.

### Which members of the community would benefit from your work?

Evaluating the performance cost of stronger memory models for Java has the potential to provide a better understanding of the tradeoffs in memory model design, and thereby to inform the evolution of Java's memory model.  This will then benefit Java programmers, ideally providing them with a simpler and stronger concurrency semantics.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Our JVM for ARM is currently not open sourced. It will be open source when we submit our paper.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

For our performance evaluation we need a variety of dedicated AArch64 machines (e.g. with different # of cores, # of sockets, microarchitectures, etc.). We already tested our project on an Overdrive 3000 server (a machine with 8 ARM Cortex A57 Cores). We would love to have access to more different hardwares.

### Please state your contributions to the open source community and any other relevant initiatives
We are pretty new to the community. Our modified version of HotSpot JVM that can provides Sequential Consistency semantics for Java on X86 is open sourced here: https://github.com/SC-HotSpot/VBD-HotSpot. We plan to do the same for our Aarch64 port.

**Comment by vielmetti** [comment]
First external reviewer said "super interesting - is there an early paper we can read?" I'm happy to make a private introduction.

**Comment by pakkaliu** [comment]
Yes. Our previous results are published on OOPSLA 17, you can read it here: http://web.cs.ucla.edu/~lunliu93/assets/vbd.pdf

Also we are happy to get introduced to the external reviewer.

**Comment by vielmetti** [comment]
Apologies for delay, this is now set up. I'll be available for check-in in a week's time.

**Comment by vielmetti** [comment]
@pakkaliu I am interested in any interim results or confirmation that you have been able to make any progress here! thanks

**Comment by pakkaliu** [comment]
Yes, since last time we talked on email I have been running another scalability test and got some interim results, but some of the results of that test is a bit strange. I am now running other tests as sanity checks and also trying to figure out the cause of the unexpected behavior.
