### ISSUE TITLE
UniKraft Project with Integration test and future CI on ARM

### ISSUE THREAD

**Issue by kalyxin02** [WorksOnArm/cluster#89]
### Name, email, company, job title

Wei Chen Wei.Chen@arm.com, ARM, Staff engineer
Simon Kuenzer <simon.kuenzer@neclab.eu>, NecLab, Tech lead/Maintainer

### UniKraft

UniKraft is a project aims to provide code base easily to develop Unikernels applications.
The fundamental drawback of unikernels is that they require that applications be manually ported to the underlying minimalistic OS (e.g. having to port nginx, snort, mysql or memcached to MiniOS or OSv); this requires both expert work and often considerable amount of time. In essence, we need to pick between either high performance with unikernels, or no porting effort but decreased performance and decreased efficiency with standard OS/VM images. The goal of this proposal is to change this status quo by providing a highly configurable unikernel code base; we call this base Unikraft.

### Which members of the community would benefit from your work?

Currently there are a bunch of contributions for this project, and together there is a need to have the fundamental integration test and unit test publicly now and furthermore the CI infrastructure in the future. This will encourage the contribution on multi-arch support, and thus appeal more Unikernels developers to utilize this project.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, the project is 100% open source. Please refer to:
Wiki: https://wiki.xenproject.org/wiki/Category:Unikraft
Code: http://xenbits.xen.org/gitweb/?a=project_list;pf=unikraft

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Require access to one ARMv8 based server now in current stage.
This project is sponsored by Xen project. 
See https://www.xenproject.org/developers/teams/unikraft.html.

### Describe the continuous integration (CI) system in use or desired for this project.

Currently it doesn't have the CI setup yet, but it's in future plan.

### Please state your contributions to the open source community and any other relevant initiatives

ARM is very actively in open source community and contributes a lot in various open source projects, like UniKraft, kata-container, OpenJDK, DPDK, OpenStack, Kubernetes, etc.

**Comment by vielmetti** [comment]
Hi Kaly @kalyxin02 ! I have received your proposal and am planning to address it after I return from time OOO.

How does your project differ from Linuxkit? See #12, #15 for some previous unikernel work done here.

**Comment by kalyxin02** [comment]
Hi @vielmetti , for your question, per my understanding, the Unikraft project is quite different from the LinuxKit. UniKraft can be seen as a kind of SDK to generate unikernel image, also it maintains/develops a lot of unikernel libraries.  For LinuxKit, it doesn't relate to unikernel concept. It's just a kind of minimalist Linux distribution and utilize container concepts in all the aspects includes running all the basic services in container and providing container runtime to run applications in container. Thanks!

**Comment by vielmetti** [comment]
Thanks @kalyxin02 this is back on my list and I will get things set up this week once I have reviewed the incoming proposals.

**Comment by vielmetti** [comment]
Stale bot keeping me honest, this is back in queue to be addressed.

**Comment by vielmetti** [comment]
Apologies for some delays. This is approved, and I've set up access for Wei Chen. For some reason there is a difficulty adding access for simon.kuenzer@neclab.eu , working on that as well.

**Comment by vielmetti** [comment]
Simon has been successfully invited to the project.

**Comment by vielmetti** [comment]
ssh logins have been resolved, so this is now ready to go. Closing.
