### ISSUE TITLE
Proposal: Mesos on ARM

### ISSUE THREAD

**Issue by janisz** [WorksOnArm/cluster#9]
Name | Tomasz Janiszewski
---------|-------------------------------
Email | janiszt@gmail.com 
Twitter | [@janiszt](https://twitter.com/janiszt)
Company | [Allegro](https://github.com/allegro)
Job Title | Software Engineer

### Project Title and description

[Apache Mesos](http://mesos.apache.org/) is a project to manage computer clusters. It can be compared to a Linux kernel but for Datacenter. Mesos is an abstraction layer over resources available in the cluster.

[Mesos Community Proposal to support ARM64 aka Mesos on ARM (MoA)](https://docs.google.com/document/d/1Hs40tGSUyoQa78ifVvn7VO5iSqe8nMc7VYWSugOqGFw/edit?usp=sharing)

### Which members of the Works on Arm community and/or end-users would benefit from your work?

End users can run Mesos on Arm and hopefully easily download official packages for ARM-based distributions (there are no official packages at the moment but there is a plan to do it – [see](https://youtu.be/m7WzKia68Rg)). Mesos community will get feedback about patches compatibility with ARM64. 

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, Mesos is top level [Apache Foundation](https://apache.org/) project. It is licensed under [Apache License 2.0](https://github.com/apache/mesos/blob/master/LICENSE). Source code is publicly available at https://github.com/apache/mesos/ (mirrored from git://git.apache.org/mesos.git)

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Type 2A machine should be enough to run CI.

### Please state your contributions to the open source community and any other relevant initiatives

My personal GitHub at @janisz lists most of the projects I'm involved with. I'm the lead of [allegro/bigcache](https://github.com/allegro/bigcache) and [allegro/marathon-consul](https://github.com/allegro/marathon-consul). I also contribute to [Apache Mesos](https://github.com/apache/mesos/commits?author=janisz)

### Notes

JIRA for INFRA is https://issues.apache.org/jira/browse/INFRA-15261

**Comment by vielmetti** [comment]
Thanks @janisz ! I understand there is going to be further discussion on this at Mesoscon Europe http://events.linuxfoundation.org/events/mesoscon-europe and I have referred several people to this item to provide comments.

**Comment by janisz** [comment]
I've talked at Mesos Developer Meeting and shared proposal for Mesos on Arm with whole community. From ASF perspective best if we can "donate" machines. This means they need to be added to Jenkins workers pool. Machines could be donated remotely.

 @vielmetti Is it doable? What more needs to be done to get machines?

**Comment by vielmetti** [comment]
Thanks @janisz - is there a link to the existing Jenkins effort that's public? And, do you anticipate that the ASF Jenkins pool might handle projects beyond Mesos through the same infrastructure? 

I see Buildbot at https://ci.apache.org/buildbot.html - was this the particular system you had in mind?

**Comment by vinodkone** [comment]
Hi. Mesos committer here. We use ASF Jenkins for building Mesos. This is different from the ASF buildbot.

For instructions on how to add a remote note to Jenkins pool see https://reference.apache.org/committer/node-hosting

Once you create INFRA ticket, please add me as a watcher so I can track progress and help where needed.

**Comment by vielmetti** [comment]
We're ready to get this started. 

Proposed order of events:

* assign @janisz some credits on the Packet system so that he can get started with whatever is necessary to do this work; @janisz if you can create a Packet account, I'll take care of next steps from that
* identify formal sponsorship arrangement with ASF (logos and etc); that will make it clear which corporate identity we're providing infrastructure to. @vinodkone can you refer me to the right person there?
* set up JIRA account, create INFRA ticket, track usage.

Sound good?

**Comment by vinodkone** [comment]
I don't know if we need anything special for 2) above. Just file an INFRA ticket and ask any questions. They ASF INFRA folks also hangout on http://infra.chat which is a hipchat room if any synchronous communication is needed.

**Comment by vielmetti** [comment]
Please look at https://issues.apache.org/jira/browse/INFRA-15261 for the associated JIRA.

**Comment by janisz** [comment]
A host is up and running. I created dedicated repository to keep its configuration https://github.com/janisz/mesos-on-arm-playbook Now waiting for ASF to join it into Jenkins pool and create Mesos Build Job.

**Comment by vielmetti** [comment]
Julio Suarez has a blog post about getting Mesos and Marathon running on Arm. I'll invite him here to compare notes.

https://community.arm.com/tools/b/blog/posts/deploying-mesos-and-marathon-on-an-arm-cluster

**Comment by janisz** [comment]
The server is plugged into Apache Jenkins Cluster and build are passing https://builds.apache.org/job/Mesos-Buildbot-ARM/

**Comment by vielmetti** [comment]
Builds passing! Good work @janisz !

**Comment by vielmetti** [comment]
Per https://builds.apache.org/job/Mesos-Buildbot-ARM/ it looks like builds are currently failing.

@janisz let me know if this is a project of continued interest for you, and I will plan accordingly.
