### ISSUE TITLE
Application for OpenHPC build support

### ISSUE THREAD

**Issue by koomie** [WorksOnArm/cluster#90]
### Name, email, company, job title
Karl W. Schulz, Research Associate Professor, University of Texas at Austin
OpenHPC Technical Steering Committee (TSC) Member

Additional TSC members at: https://github.com/openhpc/ohpc/wiki/Governance-Overview

### Project Title and description

OpenHPC: Community Building Blocks for HPC systems
http://openhpc.community
https://github.com/openhpc/ohpc

### Which members of the community would benefit from your work?

OpenHPC is a Linux Foundation collaborative project that provides a variety of common, pre-built ingredients required to deploy and manage an HPC Linux cluster including provisioning tools, resource management, I/O clients, runtimes, development tools, and a variety of scientific libraries. We currently support ARM and x86_64 on two OS distributions. Any site interested in deploying an HPC cluster on ARM can potentially benefit from one or more packaged components and/or validated installation recipes.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

OpenHPC itself is Apache-2.0 but relies on a number of upstream components which have their own open source licenses.

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Our build system is based on a standalone instance of the Open Build Service that is at https://build.openhpc.community. We aggregate OBS build workers from various geographic locations but are severely hampered by the lack of sufficient ARM resources. This request is to access a `c1.large.arm` instance to run OpenSUSE for the OBS build farm to support dedicated ARM builds. At least one instance is requested for continuous support, although we could release when not in the middle of a release cycle with a heavy build backlog. Ideally, we would like to spin up multiple instances during heavy build time as we do similarly for x86_64.

### Describe the continuous integration (CI) system in use or desired for this project.

We use Jenkins CI to repeatedly perform bare-metal installation installs on small clusters which are currently housed at the University of Texas. 

### Please state your contributions to the open source community and any other relevant initiatives

Have been involved with OpenHPC since the beginning, working with folks from ARM and Linaro to include ARM support.

Thanks for the consideration.

**Comment by vielmetti** [comment]
This is approved. Please contact me by email or Slack and we can schedule a kickoff call. I am traveling to Santa Clara for an Arm HPC workshop on Wednesday next and would love to have something to show by then.

**Comment by vielmetti** [comment]
Account set up. I'll keep this issue open for any questions, with an all-OK criteria to close when the OpenHPC system adds a c1.large.arm to the OBS build farm.

**Comment by koomie** [comment]
Thanks a bunch for the support and access to the arm instance. I had a chance to get some OBS workers setup and talking to our central server. Attached is a screen shot of builders in action from last night.

<img width="967" alt="armbuilder" src="https://user-images.githubusercontent.com/889417/43006010-2cf4600e-8bfa-11e8-913f-44a21e0bcdfc.png">

**Comment by vielmetti** [comment]
Reopening, as I have a task to write this up (and to write up HPC resources in general) for the Works on Arm website.
