### ISSUE TITLE
Works on Arm Office Hours July 25 at 2000 UTC 1600 Eastern 1300 Pacific (2018-W30-3)

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#91]
placeholder for Works on Arm call announcement. Previous week was #84 .

I will be in Santa Clara, CA for the Linaro HiSilicon Arm HPC workshop that day.

**Comment by gounthar** [comment]
@vielmetti could you please add an ICS file so that I can be there at the right time? 
Thanks.

**Comment by vielmetti** [comment]
@gounthar I will be working to improve notifications etc for this call when I come back from a week of PTO in early August.

**Comment by gounthar** [comment]
Thanks @vielmetti !
