### ISSUE TITLE
ARM platform support for Georgia Tech scheduling research

### ISSUE THREAD

**Issue by GirishMururu** [WorksOnArm/cluster#94]
### Name, email, company, job title

Amitkumar Patil, amitkumar.bvb@gmail.com, Georgia Institute of Technology, PhD student
Girish Mururu, girishmururu@gatech.edu, Georgia Institute of Technology, PhD student
Chris Porter, porter@gatech.edu, Georgia Institute of Technology, PhD student
Santosh Pande, santosh.pande@cc.gatech.edu, Georgia Institute of Technology, Professor
Note that projects with two or more participants are preferred.

### Project Title and description

Compiler-assisted scheduling on ARM
We've been investigating predictive scheduling techniques that leverage the compiler. The gist of the solution is that the compiler has insights into program behavior that it can expose to runtime components. With higher core densities in these new ARM servers, we're interested in investigating how these artifacts and behaviors could be leveraged for process and container scheduling that leads to improvements in performance and latency of applications, along with better workload consolidation and balancing.

### Which members of the community would benefit from your work?

Compiler and systems researchers and enthusiasts will benefit from the successes (or failures) of this. If the results are good, then this could be another possible technique for making better use of increasing core counts. This could benefit data center operators (reduced energy and therefore cost by workload consolidation without compromise in performance) and their users (via strong SLA guarantees even with high job consolidation).

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes, we'll open source all of it. Our present code base for the purposes of this platform is moved into: https://github.com/rudyjantz/beacons

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

First, thank you again for providing us with a ThunderX to do some exploratory research this summer (issue: https://github.com/worksonarm/cluster/issues/61). We originally proposed to work on a scheduling problem. Before diving into it, though, we spent the last month examining the cache contention among applications in a multi-process environment. We used multiple benchmarks, and only a few of them showed cache contention (and not much at that). We performed several experiments to determine if the cache was partitioned, and we also involved a team from Cavium. We were able to conclude there is no cache partitioning.

The team at Cavium is interested in this, and they’ve asked us to try this on a ThunderX2 machine. The ThunderX2’s behavior is better defined, and it should be much more interesting to study. Cavium itself does not have a remote setup available, so they’ve instead asked us if we can carry out another round of experiments through WorksOnArm. Do you house any ThunderX2’s yet? If so, is it possible for us to swap to a Thunderx2 machine with 96 cores? 

### Please state your contributions to the open source community and any other relevant initiatives

We are all relatively junior researchers and have only dabbled in open source. This project would probably be the biggest contribution from any of us. Chris has a few small contributions to a MIPS emulator called "spim" and some early, small contributions to some C code at a start-up called "storj" (both on github.com/rudyjantz). Amit has made contributions to the Linux kernel main line during his time at Intel. Girish has contributed to prototyping c++17 constructs on llvm-clang.

### Which compiler are you targeting (GCC, LLVM?)
LLVM only.

### What other components are you looking at (kernels?)
This first work is about exposing cache/memory usage to scheduling. In the past, we've looked at interaction with the Linux kernel's scheduler. This could be effective, potentially. There are a few reasons not to do that here, though. For one, we won't have access to the physical board. So the idea here is to keep everything in user space and have the processes self-manage some of the scheduling.

### Do you have any dependencies yet on specific versions of anything?
We will put LLVM 3.8 on the machine. I suspect there will be missing dependencies when we build the benchmarks, so we'll need to be able to install packages. A Debian box would be preferred, but any decently up-to-date Linux version is fine.

**Comment by vielmetti** [comment]
Back at it and ready to start this project out - I'm reviewing all of the ThunderX2 projects now and hope to have a schedule ready by the time we talk.

**Comment by vielmetti** [comment]
Per our call, this is scheduled to get turned up as soon as there's machine availability.

**Comment by vielmetti** [comment]
ThunderX2 system has been provisioned and tests are underway.

**Comment by vielmetti** [comment]
ThunderX2 assigned to the project, expected duration of use 4-6 weeks; I'll check in 1 April 2020.
