### ISSUE TITLE
WorksOnArm Proposal - Clinical Trial Image Curation and Enrollment with Edge AI

### ISSUE THREAD

**Issue by derekmerck** [WorksOnArm/cluster#95]
### Contacts

Derek Merck PhD  
Rhode Island Hospital and Brown University  
Providence, RI  
<derek_merck@brown.edu>  

Numerous clinical and student collaborators at Rhode Island Hospital, University of Michigan Hospital, and Johns Hopkins

### Background

Radiological AI has recently emerged as an area of immense potential.  However, exploration of the space is largely limited to "big players" with access to the massive amounts of patient data necessary to train sophisticated models.  Although a huge amount of relevant imaging is collected through publicly funded clinical trials in the US, very little of it is properly organized or ultimately becomes available for public review and analysis.  We have a unique opportunity to develop and test a system for automatic image data curation for large multi-site trials.  We believe that implementing this system will result in more efficient clinical trial workflows, better use of federal healthcare research money, and the eventual publication of numerous well-organized, labelled image data sets suitable for citizen-science.

### Beneficiaries

- Image AI researchers
- Medical trialists and coordinators
- Citizen-scientists and patients someday, we hope!

### Open-source Commitment

The service stack and dockerized-components are all open-source or free, but the configuration is still very much in alpha.  A secondary goal is to document and share a medical image data curation system that can be implemented inexpensively by anyone.

https://github.com/derekmerck/diana_plus
https://diana.readthedocs.io

### Infrastructure

- 1 amd64 small
- 1 armv8 large
- elastic storage, approx. 2-3TB yr 1
- 10-20 arm single-board computers

Intent is to conduct a 6 month to 1 year pilot with partial funding, followed by an application to [NIH NCATS](https://ncats.nih.gov) and other agencies for full funding to continue and expand the program.

Prefer an arm server with the ability to compile for arm32v7 depending on final choice of sbc (i.e., Pi-like vs. Jetson)

Because all image data collected is deidentified as part of the clinical trial enrollment process, we believe that no specific HIPAA certification is required beyond demonstrating best practices with respect to hardware security and system hardening.

### Description

There are 3 components of the proposed project:

1. Central Cloud Service - Provides web interfaces for direct upload, image review, and summary dashboards, manages data archive and index, updates AI models if gpu's are available

2. Remote In-Hospital Services - Monitor local radiology IS for relevant patient imaging, automatically collect images, determine patient eligibility with pre-trained AI models, deidentify data and forward for aggregation.

3. CI compilation, containerization, and testing using a staging environment that mocks interactions between the central and remote services as part of development and maintenance. 

First two components are independent but synergistic. 

### Contributions

I direct the Medical Image Analysis Research Program at Rhode Island Hospital.  A major area of our work is related to organizing the huge amounts of patient data collected by hospitals into labelled corpuses so that they can be used efficiently for reproducible science. Previously I taught computer science at public institutions for 4 years and introduced hundreds of students to Linux and the open source community.

**Comment by vielmetti** [comment]
Stale bot keeping me honest, this is back on the radar to set up (at least for a start).

**Comment by derekmerck** [comment]
Huzzah for stalebot!  D-

**Comment by vielmetti** [comment]
@derekmerck - this is approved under the name "Sponsored - DIANA" - when you get in, let me know if the project name is suitable. 

We are working on a variety of systems to come newly into the Works on Arm pool, including some 32-bit capable systems. If as you deploy gear for Arm you realize that there might be something more suitable coming down the pipeline that would be a useful set of assumptions to make.

**Comment by derekmerck** [comment]
Ed, here is an artifact that the WorksOnArm support helped me develop over the last month:
https://github.com/derekmerck/docker-orthanc-xarch

This is a cross-architecture Docker image for the open source DICOM file handler that we use.  Image runs on Raspberry Pi's as well as Packet's Intel and ARM servers.

**Comment by vielmetti** [comment]
Thanks @derekmerck ! I'm going to call the issue closed for now.
