### ISSUE TITLE
Request for ci with upstream gnu toolchain

### ISSUE THREAD

**Issue by u99127** [WorksOnArm/cluster#98]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below, or contact Ed Vielmetti at ed@packet.net with questions.

If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Ramana Radhakrishnan
Ramana.radhakrishnan@arm.com
Principal Software Engineer
Note that projects with two or more participants are preferred.

### Project Title and description
GNU Toolchain (GCC, binutils, glibc and gdb)

### Which members of the community would benefit from your work?
All 
### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?
Yes
### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

1 Huawei taishan would be good to have access to
1 thunderx2 would also be good to have access to improve testing on a non Armv8 only system. 

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

Continuous. Arm. Please talk to Jeff U.

### Describe the continuous integration (CI) system in use or desired for this project.

Buildbot Slaves for glibc and gdb for upstream buildbot masters at http://sourceware.org/glibc and http://sourceware.org/gdb
Regular tester for GCC running on a v8.1 default configuration and submitting results at https://gcc.gnu.org/ml/gcc-testresults 
Would like shell access for developers who have access to GCC compile farm here to build and test on Aarch64. 
Integrate and work with developers to get Aarch64 slaves into GCC buildbot.
https://gcc-buildbot.linki.tools/#/

### Please state your contributions to the open source community and any other relevant initiatives

- one of the original authors of the GNU toolchain for AArch64
- Tech lead GNU toolchain Arm/ AArch64
- Maintainer GCC Backend for Arm
- Steering committee member GCC .

**Comment by vielmetti** [comment]
There is an existing allocation to @zatrazz in #41 for a machine dedicated to GCC issues (specifically libgomp) that was repurpose to LLVM. If you could collaborate to see if there is some opportunity to work together that would be great.

I am OOO next week and traveling today, I will do my best to get this moving forward.

**Comment by vielmetti** [comment]
@u99127 have you had a chance to collaborate with @zatrazz ? Let me know so that I can proceed.

**Comment by u99127** [comment]
@vielmetti - I spoke with Maxim the tech-lead at Linaro and he was saying that he expects that these machines are fully loaded already with their CI, so I think we would need separate machines.

**Comment by u99127** [comment]
Any updates ?

**Comment by vielmetti** [comment]
Going to sort this all out at Linaro Connect.

**Comment by vielmetti** [comment]
Access set up to a single machine, we're sorting out name service issues at the moment and when that's taken care of I should be able to mark this as OK.

**Comment by vielmetti** [comment]
Reopen to address a hardware issue.

**Comment by vielmetti** [comment]
The tentative plan is to swap out one (or perhaps two, uncertain) ThunderX systems in EWR and replace them with new HiSilicon Hi1616 based systems in DFW. Details via email.

**Comment by vielmetti** [comment]
@u99127 - the update in 85f97a0 has bare-bones links to the projects - if you have any public URLs with live links to the status of these systems (e.g. for CI system reports) that would be quite useful.

**Comment by u99127** [comment]
https://www.gnu.org/software/libc/waterfall/
http://sourceware.org/gdb/wiki/BuildBot

The AArch64 workers are from worksonarm.

regards
Ramana

**Comment by vielmetti** [comment]
Reopening this as we have a ThunderX2 system now available.
